-- BluefinDecryptxP2pe SDK public client (generated by @voxgig/sdkgen).
--
-- Constructors (newSdk / testSdk) and one op namespace per entity. Entities are
-- generic: every op delegates to the config-driven SdkRuntime, so the pipeline
-- is identical for every entity and every API.

import VoxgigStruct
import SdkRuntime
import SdkConfig

open VoxgigStruct

namespace Sdk

/-- Construct a live client from an options map (empty map = defaults). -/
def newSdk (options : Value) : SIO Value :=
  SdkRuntime.mkClientV options SdkConfig.configJson

/-- No-argument convenience constructor. -/
def newSdk0 : SIO Value := do newSdk (← emptyMap)

/-- Construct a test-mode client: operations are answered from an in-memory
    store seeded with the entity test data, so no server is needed. -/
def testSdk (seed : Value) (options : Value) : SIO Value :=
  SdkRuntime.mkTestClientV options SdkConfig.configJson seed

/-- Test client with default options. -/
def testSdk0 (seed : Value) : SIO Value := do testSdk seed (← emptyMap)

end Sdk

namespace Attestation
  def create (c d co : Value) : SIO Value := SdkRuntime.opCreate c "attestation" d co
  def list (c m co : Value) : SIO Value := SdkRuntime.opList c "attestation" m co
  def load (c m co : Value) : SIO Value := SdkRuntime.opLoad c "attestation" m co
end Attestation

namespace Client
  def create (c d co : Value) : SIO Value := SdkRuntime.opCreate c "client" d co
  def list (c m co : Value) : SIO Value := SdkRuntime.opList c "client" m co
  def load (c m co : Value) : SIO Value := SdkRuntime.opLoad c "client" m co
  def remove (c m co : Value) : SIO Value := SdkRuntime.opRemove c "client" m co
end Client

namespace Create_result
  def create (c d co : Value) : SIO Value := SdkRuntime.opCreate c "create_result" d co
end Create_result

namespace Decryption
  def create (c d co : Value) : SIO Value := SdkRuntime.opCreate c "decryption" d co
end Decryption

namespace Device
  def create (c d co : Value) : SIO Value := SdkRuntime.opCreate c "device" d co
  def list (c m co : Value) : SIO Value := SdkRuntime.opList c "device" m co
  def load (c m co : Value) : SIO Value := SdkRuntime.opLoad c "device" m co
end Device

namespace Device_build
  def list (c m co : Value) : SIO Value := SdkRuntime.opList c "device_build" m co
  def load (c m co : Value) : SIO Value := SdkRuntime.opLoad c "device_build" m co
end Device_build

namespace Device_custody_detail
  def load (c m co : Value) : SIO Value := SdkRuntime.opLoad c "device_custody_detail" m co
end Device_custody_detail

namespace Device_custody_list
  def list (c m co : Value) : SIO Value := SdkRuntime.opList c "device_custody_list" m co
end Device_custody_list

namespace Device_list
  def load (c m co : Value) : SIO Value := SdkRuntime.opLoad c "device_list" m co
end Device_list

namespace Device_receive_result
  def create (c d co : Value) : SIO Value := SdkRuntime.opCreate c "device_receive_result" d co
end Device_receive_result

namespace Device_rki_activate_result
  def create (c d co : Value) : SIO Value := SdkRuntime.opCreate c "device_rki_activate_result" d co
end Device_rki_activate_result

namespace Device_state
  def list (c m co : Value) : SIO Value := SdkRuntime.opList c "device_state" m co
end Device_state

namespace Device_type
  def list (c m co : Value) : SIO Value := SdkRuntime.opList c "device_type" m co
  def load (c m co : Value) : SIO Value := SdkRuntime.opLoad c "device_type" m co
end Device_type

namespace Inject_key
  def list (c m co : Value) : SIO Value := SdkRuntime.opList c "inject_key" m co
  def load (c m co : Value) : SIO Value := SdkRuntime.opLoad c "inject_key" m co
end Inject_key

namespace Kif
  def list (c m co : Value) : SIO Value := SdkRuntime.opList c "kif" m co
end Kif

namespace Location
  def create (c d co : Value) : SIO Value := SdkRuntime.opCreate c "location" d co
  def list (c m co : Value) : SIO Value := SdkRuntime.opList c "location" m co
  def load (c m co : Value) : SIO Value := SdkRuntime.opLoad c "location" m co
  def remove (c m co : Value) : SIO Value := SdkRuntime.opRemove c "location" m co
end Location

namespace Partner
  def create (c d co : Value) : SIO Value := SdkRuntime.opCreate c "partner" d co
  def list (c m co : Value) : SIO Value := SdkRuntime.opList c "partner" m co
  def load (c m co : Value) : SIO Value := SdkRuntime.opLoad c "partner" m co
end Partner

namespace Shipment
  def create (c d co : Value) : SIO Value := SdkRuntime.opCreate c "shipment" d co
  def list (c m co : Value) : SIO Value := SdkRuntime.opList c "shipment" m co
  def load (c m co : Value) : SIO Value := SdkRuntime.opLoad c "shipment" m co
end Shipment

namespace Success
  def create (c d co : Value) : SIO Value := SdkRuntime.opCreate c "success" d co
  def remove (c m co : Value) : SIO Value := SdkRuntime.opRemove c "success" m co
end Success

namespace Transaction
  def create (c d co : Value) : SIO Value := SdkRuntime.opCreate c "transaction" d co
  def list (c m co : Value) : SIO Value := SdkRuntime.opList c "transaction" m co
  def load (c m co : Value) : SIO Value := SdkRuntime.opLoad c "transaction" m co
end Transaction

namespace Update_result
  def create (c d co : Value) : SIO Value := SdkRuntime.opCreate c "update_result" d co
  def list (c m co : Value) : SIO Value := SdkRuntime.opList c "update_result" m co
  def update (c m d co : Value) : SIO Value := SdkRuntime.opUpdate c "update_result" m d co
end Update_result

namespace User
  def load (c m co : Value) : SIO Value := SdkRuntime.opLoad c "user" m co
  def remove (c m co : Value) : SIO Value := SdkRuntime.opRemove c "user" m co
end User

