// Generated API configuration (mirrors core/config.go).

#include "api.h"

#include <string.h>

voxgig_value* make_config(void) {
  return cmap(4,
    "main", cmap(1,
      "name", v_str("BluefinDecryptxP2pe")),
    "feature", cmap(1,
      "test", cmap(1,
        "options", cmap(1,
          "active", v_bool(false)))),
    "options", cmap(4,
      "base", v_str("https://apis.p2pemanager.com/api/v1"),
      "headers", cmap(1,
        "content-type", v_str("application/json")),
      "entity", cmap(22,
        "attestation", v_map(),
        "client", v_map(),
        "create_result", v_map(),
        "decryption", v_map(),
        "device", v_map(),
        "device_build", v_map(),
        "device_custody_detail", v_map(),
        "device_custody_list", v_map(),
        "device_list", v_map(),
        "device_receive_result", v_map(),
        "device_rki_activate_result", v_map(),
        "device_state", v_map(),
        "device_type", v_map(),
        "inject_key", v_map(),
        "kif", v_map(),
        "location", v_map(),
        "partner", v_map(),
        "shipment", v_map(),
        "success", v_map(),
        "transaction", v_map(),
        "update_result", v_map(),
        "user", v_map()),
      "auth", cmap(1,
        "prefix", v_str("Basic"))),
    "entity", cmap(22,
      "attestation", cmap(4,
        "fields", clist(7,
          cmap(2,
            "name", v_str("client"),
            "type", v_str("`$OBJECT`")),
          cmap(2,
            "name", v_str("completeDate"),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("created"),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("device"),
            "type", v_str("`$OBJECT`")),
          cmap(2,
            "name", v_str("id"),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("name"),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("notes"),
            "type", v_str("`$STRING`"))),
        "name", v_str("attestation"),
        "op", cmap(3,
          "create", cmap(3,
            "input", v_str("data"),
            "name", v_str("create"),
            "points", clist(1,
              cmap(7,
                "args", v_map(),
                "kind", v_str("http"),
                "method", v_str("POST"),
                "orig", v_str("/attestations"),
                "parts", clist(1,
                  v_str("attestations")),
                "select", v_map(),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`"))))),
          "list", cmap(3,
            "input", v_str("data"),
            "name", v_str("list"),
            "points", clist(1,
              cmap(7,
                "args", cmap(1,
                  "query", clist(3,
                    cmap(5,
                      "kind", v_str("query"),
                      "name", v_str("client"),
                      "orig", v_str("client"),
                      "reqd", v_bool(true),
                      "type", v_str("`$STRING`")),
                    cmap(5,
                      "example", v_num(0),
                      "kind", v_str("query"),
                      "name", v_str("skip"),
                      "orig", v_str("skip"),
                      "type", v_str("`$INTEGER`")),
                    cmap(5,
                      "example", v_num(10),
                      "kind", v_str("query"),
                      "name", v_str("take"),
                      "orig", v_str("take"),
                      "type", v_str("`$INTEGER`")))),
                "kind", v_str("http"),
                "method", v_str("GET"),
                "orig", v_str("/attestations"),
                "parts", clist(1,
                  v_str("attestations")),
                "select", cmap(1,
                  "exist", clist(3,
                    v_str("client"),
                    v_str("skip"),
                    v_str("take"))),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`"))))),
          "load", cmap(3,
            "input", v_str("data"),
            "name", v_str("load"),
            "points", clist(1,
              cmap(7,
                "args", cmap(1,
                  "params", clist(1,
                    cmap(5,
                      "kind", v_str("param"),
                      "name", v_str("id"),
                      "orig", v_str("id"),
                      "reqd", v_bool(true),
                      "type", v_str("`$STRING`")))),
                "kind", v_str("http"),
                "method", v_str("GET"),
                "orig", v_str("/attestations/{id}"),
                "parts", clist(2,
                  v_str("attestations"),
                  v_str("{id}")),
                "select", cmap(1,
                  "exist", clist(1,
                    v_str("id"))),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")))))),
        "relations", cmap(1,
          "ancestors", v_list())),
      "client", cmap(4,
        "fields", clist(11,
          cmap(3,
            "name", v_str("contact"),
            "op", cmap(1,
              "list", cmap(2,
                "req", v_bool(true),
                "type", v_str("`$OBJECT`"))),
            "type", v_str("`$OBJECT`")),
          cmap(2,
            "name", v_str("created"),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("directPartner"),
            "type", v_str("`$OBJECT`")),
          cmap(2,
            "name", v_str("id"),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("isActive"),
            "type", v_str("`$BOOLEAN`")),
          cmap(3,
            "name", v_str("location"),
            "req", v_bool(true),
            "type", v_str("`$OBJECT`")),
          cmap(2,
            "name", v_str("mid"),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("modified"),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("name"),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("partner"),
            "type", v_str("`$OBJECT`")),
          cmap(2,
            "name", v_str("version"),
            "type", v_str("`$INTEGER`"))),
        "name", v_str("client"),
        "op", cmap(4,
          "create", cmap(3,
            "input", v_str("data"),
            "name", v_str("create"),
            "points", clist(1,
              cmap(7,
                "args", v_map(),
                "kind", v_str("http"),
                "method", v_str("POST"),
                "orig", v_str("/clients"),
                "parts", clist(1,
                  v_str("clients")),
                "select", v_map(),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`"))))),
          "list", cmap(3,
            "input", v_str("data"),
            "name", v_str("list"),
            "points", clist(1,
              cmap(7,
                "args", cmap(1,
                  "query", clist(3,
                    cmap(5,
                      "kind", v_str("query"),
                      "name", v_str("partner"),
                      "orig", v_str("partner"),
                      "reqd", v_bool(true),
                      "type", v_str("`$STRING`")),
                    cmap(5,
                      "example", v_num(0),
                      "kind", v_str("query"),
                      "name", v_str("skip"),
                      "orig", v_str("skip"),
                      "type", v_str("`$INTEGER`")),
                    cmap(5,
                      "example", v_num(10),
                      "kind", v_str("query"),
                      "name", v_str("take"),
                      "orig", v_str("take"),
                      "type", v_str("`$INTEGER`")))),
                "kind", v_str("http"),
                "method", v_str("GET"),
                "orig", v_str("/clients"),
                "parts", clist(1,
                  v_str("clients")),
                "select", cmap(1,
                  "exist", clist(3,
                    v_str("partner"),
                    v_str("skip"),
                    v_str("take"))),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`"))))),
          "load", cmap(3,
            "input", v_str("data"),
            "name", v_str("load"),
            "points", clist(1,
              cmap(7,
                "args", cmap(1,
                  "params", clist(1,
                    cmap(5,
                      "kind", v_str("param"),
                      "name", v_str("id"),
                      "orig", v_str("id"),
                      "reqd", v_bool(true),
                      "type", v_str("`$STRING`")))),
                "kind", v_str("http"),
                "method", v_str("GET"),
                "orig", v_str("/clients/{id}"),
                "parts", clist(2,
                  v_str("clients"),
                  v_str("{id}")),
                "select", cmap(1,
                  "exist", clist(1,
                    v_str("id"))),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`"))))),
          "remove", cmap(3,
            "input", v_str("data"),
            "name", v_str("remove"),
            "points", clist(1,
              cmap(7,
                "args", cmap(1,
                  "params", clist(1,
                    cmap(5,
                      "kind", v_str("param"),
                      "name", v_str("id"),
                      "orig", v_str("id"),
                      "reqd", v_bool(true),
                      "type", v_str("`$STRING`")))),
                "kind", v_str("http"),
                "method", v_str("DELETE"),
                "orig", v_str("/clients/{id}"),
                "parts", clist(2,
                  v_str("clients"),
                  v_str("{id}")),
                "select", cmap(1,
                  "exist", clist(1,
                    v_str("id"))),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")))))),
        "relations", cmap(1,
          "ancestors", v_list())),
      "create_result", cmap(4,
        "fields", v_list(),
        "name", v_str("create_result"),
        "op", cmap(1,
          "create", cmap(3,
            "input", v_str("data"),
            "name", v_str("create"),
            "points", clist(1,
              cmap(8,
                "args", cmap(1,
                  "params", clist(2,
                    cmap(5,
                      "kind", v_str("param"),
                      "name", v_str("device_type"),
                      "orig", v_str("device_type"),
                      "reqd", v_bool(true),
                      "type", v_str("`$STRING`")),
                    cmap(5,
                      "kind", v_str("param"),
                      "name", v_str("serial_number"),
                      "orig", v_str("serial_number"),
                      "reqd", v_bool(true),
                      "type", v_str("`$STRING`")))),
                "kind", v_str("http"),
                "method", v_str("POST"),
                "orig", v_str("/devices/{serialNumber}/{deviceType}/custody"),
                "parts", clist(4,
                  v_str("devices"),
                  v_str("{serial_number}"),
                  v_str("{device_type}"),
                  v_str("custody")),
                "rename", cmap(1,
                  "param", cmap(2,
                    "deviceType", v_str("device_type"),
                    "serialNumber", v_str("serial_number"))),
                "select", cmap(1,
                  "exist", clist(2,
                    v_str("device_type"),
                    v_str("serial_number"))),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")))))),
        "relations", cmap(1,
          "ancestors", clist(1,
            clist(1,
              v_str("device"))))),
      "decryption", cmap(4,
        "fields", clist(1,
          cmap(2,
            "name", v_str("success"),
            "type", v_str("`$BOOLEAN`"))),
        "name", v_str("decryption"),
        "op", cmap(1,
          "create", cmap(3,
            "input", v_str("data"),
            "name", v_str("create"),
            "points", clist(1,
              cmap(7,
                "args", v_map(),
                "kind", v_str("http"),
                "method", v_str("POST"),
                "orig", v_str("/decryption"),
                "parts", clist(1,
                  v_str("decryption")),
                "select", v_map(),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")))))),
        "relations", cmap(1,
          "ancestors", v_list())),
      "device", cmap(4,
        "fields", clist(28,
          cmap(3,
            "name", v_str("activatedBy"),
            "req", v_bool(true),
            "type", v_str("`$OBJECT`")),
          cmap(2,
            "name", v_str("activationDate"),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("alternateKey"),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("auditNextDate"),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("auditNotificationDate"),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("client"),
            "type", v_str("`$OBJECT`")),
          cmap(2,
            "name", v_str("created"),
            "type", v_str("`$STRING`")),
          cmap(3,
            "name", v_str("createdBy"),
            "req", v_bool(true),
            "type", v_str("`$OBJECT`")),
          cmap(2,
            "name", v_str("deviceBuild"),
            "type", v_str("`$OBJECT`")),
          cmap(2,
            "name", v_str("deviceState"),
            "type", v_str("`$OBJECT`")),
          cmap(2,
            "name", v_str("deviceType"),
            "type", v_str("`$OBJECT`")),
          cmap(2,
            "name", v_str("errorCounter"),
            "type", v_str("`$INTEGER`")),
          cmap(2,
            "name", v_str("errorLastDate"),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("id"),
            "type", v_str("`$STRING`")),
          cmap(3,
            "name", v_str("initializedBy"),
            "req", v_bool(true),
            "type", v_str("`$OBJECT`")),
          cmap(2,
            "name", v_str("initializedDate"),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("injectKey"),
            "type", v_str("`$OBJECT`")),
          cmap(2,
            "name", v_str("isVirtual"),
            "type", v_str("`$BOOLEAN`")),
          cmap(2,
            "name", v_str("kif"),
            "type", v_str("`$OBJECT`")),
          cmap(2,
            "name", v_str("lastActivityDate"),
            "type", v_str("`$STRING`")),
          cmap(3,
            "name", v_str("location"),
            "req", v_bool(true),
            "type", v_str("`$OBJECT`")),
          cmap(2,
            "name", v_str("modified"),
            "type", v_str("`$STRING`")),
          cmap(3,
            "name", v_str("modifiedBy"),
            "req", v_bool(true),
            "type", v_str("`$OBJECT`")),
          cmap(2,
            "name", v_str("name"),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("notes"),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("partner"),
            "type", v_str("`$OBJECT`")),
          cmap(2,
            "name", v_str("serialNumber"),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("version"),
            "type", v_str("`$INTEGER`"))),
        "name", v_str("device"),
        "op", cmap(3,
          "create", cmap(3,
            "input", v_str("data"),
            "name", v_str("create"),
            "points", clist(1,
              cmap(7,
                "args", v_map(),
                "kind", v_str("http"),
                "method", v_str("POST"),
                "orig", v_str("/devices"),
                "parts", clist(1,
                  v_str("devices")),
                "select", v_map(),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`"))))),
          "list", cmap(3,
            "input", v_str("data"),
            "name", v_str("list"),
            "points", clist(1,
              cmap(7,
                "args", cmap(1,
                  "query", clist(9,
                    cmap(4,
                      "kind", v_str("query"),
                      "name", v_str("client"),
                      "orig", v_str("client"),
                      "type", v_str("`$STRING`")),
                    cmap(4,
                      "kind", v_str("query"),
                      "name", v_str("device_state"),
                      "orig", v_str("device_state"),
                      "type", v_str("`$STRING`")),
                    cmap(4,
                      "kind", v_str("query"),
                      "name", v_str("kif"),
                      "orig", v_str("kif"),
                      "type", v_str("`$STRING`")),
                    cmap(4,
                      "kind", v_str("query"),
                      "name", v_str("partner"),
                      "orig", v_str("partner"),
                      "type", v_str("`$STRING`")),
                    cmap(4,
                      "kind", v_str("query"),
                      "name", v_str("serial_number"),
                      "orig", v_str("serial_number"),
                      "type", v_str("`$STRING`")),
                    cmap(5,
                      "example", v_num(0),
                      "kind", v_str("query"),
                      "name", v_str("skip"),
                      "orig", v_str("skip"),
                      "type", v_str("`$INTEGER`")),
                    cmap(5,
                      "example", v_str("asc"),
                      "kind", v_str("query"),
                      "name", v_str("sorting_direction"),
                      "orig", v_str("sorting_direction"),
                      "type", v_str("`$STRING`")),
                    cmap(5,
                      "example", v_str("serialnumber"),
                      "kind", v_str("query"),
                      "name", v_str("sorting_field"),
                      "orig", v_str("sorting_field"),
                      "type", v_str("`$STRING`")),
                    cmap(5,
                      "example", v_num(10),
                      "kind", v_str("query"),
                      "name", v_str("take"),
                      "orig", v_str("take"),
                      "type", v_str("`$INTEGER`")))),
                "kind", v_str("http"),
                "method", v_str("GET"),
                "orig", v_str("/devices"),
                "parts", clist(1,
                  v_str("devices")),
                "select", cmap(1,
                  "exist", clist(9,
                    v_str("client"),
                    v_str("device_state"),
                    v_str("kif"),
                    v_str("partner"),
                    v_str("serial_number"),
                    v_str("skip"),
                    v_str("sorting_direction"),
                    v_str("sorting_field"),
                    v_str("take"))),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`"))))),
          "load", cmap(3,
            "input", v_str("data"),
            "name", v_str("load"),
            "points", clist(2,
              cmap(8,
                "args", cmap(1,
                  "params", clist(2,
                    cmap(5,
                      "kind", v_str("param"),
                      "name", v_str("device_type"),
                      "orig", v_str("device_type"),
                      "reqd", v_bool(true),
                      "type", v_str("`$STRING`")),
                    cmap(5,
                      "kind", v_str("param"),
                      "name", v_str("serial_number"),
                      "orig", v_str("serial_number"),
                      "reqd", v_bool(true),
                      "type", v_str("`$STRING`")))),
                "kind", v_str("http"),
                "method", v_str("GET"),
                "orig", v_str("/devices/{serialNumber}/{deviceType}"),
                "parts", clist(3,
                  v_str("devices"),
                  v_str("{serial_number}"),
                  v_str("{device_type}")),
                "rename", cmap(1,
                  "param", cmap(2,
                    "deviceType", v_str("device_type"),
                    "serialNumber", v_str("serial_number"))),
                "select", cmap(1,
                  "exist", clist(2,
                    v_str("device_type"),
                    v_str("serial_number"))),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`"))),
              cmap(7,
                "args", cmap(1,
                  "params", clist(1,
                    cmap(5,
                      "kind", v_str("param"),
                      "name", v_str("id"),
                      "orig", v_str("id"),
                      "reqd", v_bool(true),
                      "type", v_str("`$STRING`")))),
                "kind", v_str("http"),
                "method", v_str("GET"),
                "orig", v_str("/devices/{id}"),
                "parts", clist(2,
                  v_str("devices"),
                  v_str("{id}")),
                "select", cmap(1,
                  "exist", clist(1,
                    v_str("id"))),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")))))),
        "relations", cmap(1,
          "ancestors", clist(1,
            clist(1,
              v_str("device"))))),
      "device_build", cmap(4,
        "fields", clist(15,
          cmap(2,
            "name", v_str("appVersion"),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("buildNumber"),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("configFileName"),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("created"),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("deviceType"),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("firmwareVersion"),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("hardwareVersion"),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("id"),
            "type", v_str("`$INTEGER`")),
          cmap(2,
            "name", v_str("isActive"),
            "type", v_str("`$BOOLEAN`")),
          cmap(2,
            "name", v_str("modified"),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("name"),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("notes"),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("version"),
            "type", v_str("`$INTEGER`")),
          cmap(2,
            "name", v_str("whiteListingBinRanges"),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("whiteListingUsed"),
            "type", v_str("`$BOOLEAN`"))),
        "name", v_str("device_build"),
        "op", cmap(2,
          "list", cmap(3,
            "input", v_str("data"),
            "name", v_str("list"),
            "points", clist(1,
              cmap(7,
                "args", cmap(1,
                  "query", clist(3,
                    cmap(4,
                      "kind", v_str("query"),
                      "name", v_str("device_type"),
                      "orig", v_str("device_type"),
                      "type", v_str("`$STRING`")),
                    cmap(5,
                      "example", v_num(0),
                      "kind", v_str("query"),
                      "name", v_str("skip"),
                      "orig", v_str("skip"),
                      "type", v_str("`$INTEGER`")),
                    cmap(5,
                      "example", v_num(10),
                      "kind", v_str("query"),
                      "name", v_str("take"),
                      "orig", v_str("take"),
                      "type", v_str("`$INTEGER`")))),
                "kind", v_str("http"),
                "method", v_str("GET"),
                "orig", v_str("/deviceBuilds"),
                "parts", clist(1,
                  v_str("deviceBuilds")),
                "select", cmap(1,
                  "exist", clist(3,
                    v_str("device_type"),
                    v_str("skip"),
                    v_str("take"))),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`"))))),
          "load", cmap(3,
            "input", v_str("data"),
            "name", v_str("load"),
            "points", clist(1,
              cmap(7,
                "args", cmap(1,
                  "params", clist(1,
                    cmap(5,
                      "kind", v_str("param"),
                      "name", v_str("id"),
                      "orig", v_str("id"),
                      "reqd", v_bool(true),
                      "type", v_str("`$STRING`")))),
                "kind", v_str("http"),
                "method", v_str("GET"),
                "orig", v_str("/deviceBuilds/{id}"),
                "parts", clist(2,
                  v_str("deviceBuilds"),
                  v_str("{id}")),
                "select", cmap(1,
                  "exist", clist(1,
                    v_str("id"))),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")))))),
        "relations", cmap(1,
          "ancestors", v_list())),
      "device_custody_detail", cmap(4,
        "fields", clist(13,
          cmap(2,
            "name", v_str("completeDate"),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("created"),
            "type", v_str("`$STRING`")),
          cmap(3,
            "name", v_str("createdBy"),
            "req", v_bool(true),
            "type", v_str("`$OBJECT`")),
          cmap(3,
            "name", v_str("custodian"),
            "req", v_bool(true),
            "type", v_str("`$OBJECT`")),
          cmap(2,
            "name", v_str("device"),
            "type", v_str("`$OBJECT`")),
          cmap(2,
            "name", v_str("id"),
            "type", v_str("`$INTEGER`")),
          cmap(3,
            "name", v_str("location"),
            "req", v_bool(true),
            "type", v_str("`$OBJECT`")),
          cmap(2,
            "name", v_str("modified"),
            "type", v_str("`$STRING`")),
          cmap(3,
            "name", v_str("modifiedBy"),
            "req", v_bool(true),
            "type", v_str("`$OBJECT`")),
          cmap(2,
            "name", v_str("notes"),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("status"),
            "type", v_str("`$OBJECT`")),
          cmap(2,
            "name", v_str("transferMethod"),
            "type", v_str("`$OBJECT`")),
          cmap(2,
            "name", v_str("version"),
            "type", v_str("`$INTEGER`"))),
        "name", v_str("device_custody_detail"),
        "op", cmap(1,
          "load", cmap(3,
            "input", v_str("data"),
            "name", v_str("load"),
            "points", clist(1,
              cmap(8,
                "args", cmap(1,
                  "params", clist(3,
                    cmap(5,
                      "kind", v_str("param"),
                      "name", v_str("device_type"),
                      "orig", v_str("device_type"),
                      "reqd", v_bool(true),
                      "type", v_str("`$STRING`")),
                    cmap(5,
                      "kind", v_str("param"),
                      "name", v_str("id"),
                      "orig", v_str("id"),
                      "reqd", v_bool(true),
                      "type", v_str("`$STRING`")),
                    cmap(5,
                      "kind", v_str("param"),
                      "name", v_str("serial_number"),
                      "orig", v_str("serial_number"),
                      "reqd", v_bool(true),
                      "type", v_str("`$STRING`")))),
                "kind", v_str("http"),
                "method", v_str("GET"),
                "orig", v_str("/devices/{serialNumber}/{deviceType}/custody/{id}"),
                "parts", clist(5,
                  v_str("devices"),
                  v_str("{serial_number}"),
                  v_str("{device_type}"),
                  v_str("custody"),
                  v_str("{id}")),
                "rename", cmap(1,
                  "param", cmap(2,
                    "deviceType", v_str("device_type"),
                    "serialNumber", v_str("serial_number"))),
                "select", cmap(1,
                  "exist", clist(3,
                    v_str("device_type"),
                    v_str("id"),
                    v_str("serial_number"))),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")))))),
        "relations", cmap(1,
          "ancestors", clist(1,
            clist(1,
              v_str("device"))))),
      "device_custody_list", cmap(4,
        "fields", clist(13,
          cmap(2,
            "name", v_str("completeDate"),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("created"),
            "type", v_str("`$STRING`")),
          cmap(3,
            "name", v_str("createdBy"),
            "req", v_bool(true),
            "type", v_str("`$OBJECT`")),
          cmap(3,
            "name", v_str("custodian"),
            "req", v_bool(true),
            "type", v_str("`$OBJECT`")),
          cmap(2,
            "name", v_str("device"),
            "type", v_str("`$OBJECT`")),
          cmap(2,
            "name", v_str("id"),
            "type", v_str("`$INTEGER`")),
          cmap(3,
            "name", v_str("location"),
            "req", v_bool(true),
            "type", v_str("`$OBJECT`")),
          cmap(2,
            "name", v_str("modified"),
            "type", v_str("`$STRING`")),
          cmap(3,
            "name", v_str("modifiedBy"),
            "req", v_bool(true),
            "type", v_str("`$OBJECT`")),
          cmap(2,
            "name", v_str("notes"),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("status"),
            "type", v_str("`$OBJECT`")),
          cmap(2,
            "name", v_str("transferMethod"),
            "type", v_str("`$OBJECT`")),
          cmap(2,
            "name", v_str("version"),
            "type", v_str("`$INTEGER`"))),
        "name", v_str("device_custody_list"),
        "op", cmap(1,
          "list", cmap(3,
            "input", v_str("data"),
            "name", v_str("list"),
            "points", clist(1,
              cmap(8,
                "args", cmap(2,
                  "params", clist(2,
                    cmap(5,
                      "kind", v_str("param"),
                      "name", v_str("device_type"),
                      "orig", v_str("device_type"),
                      "reqd", v_bool(true),
                      "type", v_str("`$STRING`")),
                    cmap(5,
                      "kind", v_str("param"),
                      "name", v_str("serial_number"),
                      "orig", v_str("serial_number"),
                      "reqd", v_bool(true),
                      "type", v_str("`$STRING`"))),
                  "query", clist(2,
                    cmap(5,
                      "example", v_num(0),
                      "kind", v_str("query"),
                      "name", v_str("skip"),
                      "orig", v_str("skip"),
                      "type", v_str("`$INTEGER`")),
                    cmap(5,
                      "example", v_num(10),
                      "kind", v_str("query"),
                      "name", v_str("take"),
                      "orig", v_str("take"),
                      "type", v_str("`$INTEGER`")))),
                "kind", v_str("http"),
                "method", v_str("GET"),
                "orig", v_str("/devices/{serialNumber}/{deviceType}/custody"),
                "parts", clist(4,
                  v_str("devices"),
                  v_str("{serial_number}"),
                  v_str("{device_type}"),
                  v_str("custody")),
                "rename", cmap(1,
                  "param", cmap(2,
                    "deviceType", v_str("device_type"),
                    "serialNumber", v_str("serial_number"))),
                "select", cmap(1,
                  "exist", clist(4,
                    v_str("device_type"),
                    v_str("serial_number"),
                    v_str("skip"),
                    v_str("take"))),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")))))),
        "relations", cmap(1,
          "ancestors", clist(1,
            clist(1,
              v_str("device"))))),
      "device_list", cmap(4,
        "fields", clist(2,
          cmap(2,
            "name", v_str("data"),
            "type", v_str("`$ARRAY`")),
          cmap(2,
            "name", v_str("total"),
            "type", v_str("`$INTEGER`"))),
        "name", v_str("device_list"),
        "op", cmap(1,
          "load", cmap(3,
            "input", v_str("data"),
            "name", v_str("load"),
            "points", clist(1,
              cmap(8,
                "args", cmap(2,
                  "params", clist(1,
                    cmap(5,
                      "kind", v_str("param"),
                      "name", v_str("share_partner_to"),
                      "orig", v_str("share_partner_to"),
                      "reqd", v_bool(true),
                      "type", v_str("`$STRING`"))),
                  "query", clist(4,
                    cmap(5,
                      "example", v_num(0),
                      "kind", v_str("query"),
                      "name", v_str("skip"),
                      "orig", v_str("skip"),
                      "type", v_str("`$INTEGER`")),
                    cmap(5,
                      "example", v_str("asc"),
                      "kind", v_str("query"),
                      "name", v_str("sorting_direction"),
                      "orig", v_str("sorting_direction"),
                      "type", v_str("`$STRING`")),
                    cmap(5,
                      "example", v_str("serialnumber"),
                      "kind", v_str("query"),
                      "name", v_str("sorting_field"),
                      "orig", v_str("sorting_field"),
                      "type", v_str("`$STRING`")),
                    cmap(5,
                      "example", v_num(10),
                      "kind", v_str("query"),
                      "name", v_str("take"),
                      "orig", v_str("take"),
                      "type", v_str("`$INTEGER`")))),
                "kind", v_str("http"),
                "method", v_str("GET"),
                "orig", v_str("/virtualDevices/{sharePartnerTo}"),
                "parts", clist(2,
                  v_str("virtualDevices"),
                  v_str("{share_partner_to}")),
                "rename", cmap(1,
                  "param", cmap(1,
                    "sharePartnerTo", v_str("share_partner_to"))),
                "select", cmap(1,
                  "exist", clist(5,
                    v_str("share_partner_to"),
                    v_str("skip"),
                    v_str("sorting_direction"),
                    v_str("sorting_field"),
                    v_str("take"))),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")))))),
        "relations", cmap(1,
          "ancestors", clist(1,
            clist(1,
              v_str("virtual_device"))))),
      "device_receive_result", cmap(4,
        "fields", clist(1,
          cmap(3,
            "name", v_str("success"),
            "req", v_bool(true),
            "type", v_str("`$BOOLEAN`"))),
        "name", v_str("device_receive_result"),
        "op", cmap(1,
          "create", cmap(3,
            "input", v_str("data"),
            "name", v_str("create"),
            "points", clist(1,
              cmap(7,
                "args", v_map(),
                "kind", v_str("http"),
                "method", v_str("POST"),
                "orig", v_str("/devices/receive"),
                "parts", clist(2,
                  v_str("devices"),
                  v_str("receive")),
                "select", v_map(),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")))))),
        "relations", cmap(1,
          "ancestors", v_list())),
      "device_rki_activate_result", cmap(4,
        "fields", clist(1,
          cmap(3,
            "name", v_str("success"),
            "req", v_bool(true),
            "type", v_str("`$BOOLEAN`"))),
        "name", v_str("device_rki_activate_result"),
        "op", cmap(1,
          "create", cmap(3,
            "input", v_str("data"),
            "name", v_str("create"),
            "points", clist(1,
              cmap(7,
                "args", v_map(),
                "kind", v_str("http"),
                "method", v_str("POST"),
                "orig", v_str("/devices/rki/activate"),
                "parts", clist(3,
                  v_str("devices"),
                  v_str("rki"),
                  v_str("activate")),
                "select", v_map(),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")))))),
        "relations", cmap(1,
          "ancestors", v_list())),
      "device_state", cmap(4,
        "fields", clist(2,
          cmap(2,
            "name", v_str("id"),
            "type", v_str("`$INTEGER`")),
          cmap(2,
            "name", v_str("name"),
            "type", v_str("`$STRING`"))),
        "name", v_str("device_state"),
        "op", cmap(1,
          "list", cmap(3,
            "input", v_str("data"),
            "name", v_str("list"),
            "points", clist(1,
              cmap(7,
                "args", v_map(),
                "kind", v_str("http"),
                "method", v_str("GET"),
                "orig", v_str("/deviceStates"),
                "parts", clist(1,
                  v_str("deviceStates")),
                "select", v_map(),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")))))),
        "relations", cmap(1,
          "ancestors", v_list())),
      "device_type", cmap(4,
        "fields", clist(12,
          cmap(2,
            "name", v_str("created"),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("deviceTypeMode"),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("hardwareVersion"),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("id"),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("isActive"),
            "type", v_str("`$BOOLEAN`")),
          cmap(2,
            "name", v_str("manufacturer"),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("model"),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("modified"),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("name"),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("photoUrl"),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("productName"),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("version"),
            "type", v_str("`$INTEGER`"))),
        "name", v_str("device_type"),
        "op", cmap(2,
          "list", cmap(3,
            "input", v_str("data"),
            "name", v_str("list"),
            "points", clist(1,
              cmap(7,
                "args", v_map(),
                "kind", v_str("http"),
                "method", v_str("GET"),
                "orig", v_str("/deviceTypes"),
                "parts", clist(1,
                  v_str("deviceTypes")),
                "select", v_map(),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`"))))),
          "load", cmap(3,
            "input", v_str("data"),
            "name", v_str("load"),
            "points", clist(1,
              cmap(7,
                "args", cmap(1,
                  "params", clist(1,
                    cmap(5,
                      "kind", v_str("param"),
                      "name", v_str("id"),
                      "orig", v_str("id"),
                      "reqd", v_bool(true),
                      "type", v_str("`$STRING`")))),
                "kind", v_str("http"),
                "method", v_str("GET"),
                "orig", v_str("/deviceTypes/{id}"),
                "parts", clist(2,
                  v_str("deviceTypes"),
                  v_str("{id}")),
                "select", cmap(1,
                  "exist", clist(1,
                    v_str("id"))),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")))))),
        "relations", cmap(1,
          "ancestors", v_list())),
      "inject_key", cmap(4,
        "fields", clist(8,
          cmap(2,
            "name", v_str("created"),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("id"),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("isActive"),
            "type", v_str("`$BOOLEAN`")),
          cmap(2,
            "name", v_str("isP2PE"),
            "type", v_str("`$BOOLEAN`")),
          cmap(2,
            "name", v_str("keyType"),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("modified"),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("name"),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("version"),
            "type", v_str("`$INTEGER`"))),
        "name", v_str("inject_key"),
        "op", cmap(2,
          "list", cmap(3,
            "input", v_str("data"),
            "name", v_str("list"),
            "points", clist(1,
              cmap(7,
                "args", v_map(),
                "kind", v_str("http"),
                "method", v_str("GET"),
                "orig", v_str("/injectKeys"),
                "parts", clist(1,
                  v_str("injectKeys")),
                "select", v_map(),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`"))))),
          "load", cmap(3,
            "input", v_str("data"),
            "name", v_str("load"),
            "points", clist(1,
              cmap(7,
                "args", cmap(1,
                  "params", clist(1,
                    cmap(5,
                      "kind", v_str("param"),
                      "name", v_str("id"),
                      "orig", v_str("id"),
                      "reqd", v_bool(true),
                      "type", v_str("`$STRING`")))),
                "kind", v_str("http"),
                "method", v_str("GET"),
                "orig", v_str("/injectKeys/{id}"),
                "parts", clist(2,
                  v_str("injectKeys"),
                  v_str("{id}")),
                "select", cmap(1,
                  "exist", clist(1,
                    v_str("id"))),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")))))),
        "relations", cmap(1,
          "ancestors", v_list())),
      "kif", cmap(4,
        "fields", clist(2,
          cmap(2,
            "name", v_str("id"),
            "type", v_str("`$INTEGER`")),
          cmap(2,
            "name", v_str("name"),
            "type", v_str("`$STRING`"))),
        "name", v_str("kif"),
        "op", cmap(1,
          "list", cmap(3,
            "input", v_str("data"),
            "name", v_str("list"),
            "points", clist(1,
              cmap(7,
                "args", v_map(),
                "kind", v_str("http"),
                "method", v_str("GET"),
                "orig", v_str("/kifs"),
                "parts", clist(1,
                  v_str("kifs")),
                "select", v_map(),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")))))),
        "relations", cmap(1,
          "ancestors", v_list())),
      "location", cmap(4,
        "fields", clist(23,
          cmap(2,
            "name", v_str("address1"),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("address2"),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("billingId"),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("city"),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("country"),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("created"),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("customReference"),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("id"),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("locationType"),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("mailAddress1"),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("mailAddress2"),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("mailCity"),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("mailCountry"),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("mailPostalCode"),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("mailStateProvince"),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("modified"),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("name"),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("nameOfBusiness"),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("notes"),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("postalCode"),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("stateProvince"),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("uniqueId"),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("version"),
            "type", v_str("`$INTEGER`"))),
        "name", v_str("location"),
        "op", cmap(4,
          "create", cmap(3,
            "input", v_str("data"),
            "name", v_str("create"),
            "points", clist(1,
              cmap(7,
                "args", v_map(),
                "kind", v_str("http"),
                "method", v_str("POST"),
                "orig", v_str("/locations"),
                "parts", clist(1,
                  v_str("locations")),
                "select", v_map(),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`"))))),
          "list", cmap(3,
            "input", v_str("data"),
            "name", v_str("list"),
            "points", clist(1,
              cmap(7,
                "args", cmap(1,
                  "query", clist(3,
                    cmap(5,
                      "kind", v_str("query"),
                      "name", v_str("client"),
                      "orig", v_str("client"),
                      "reqd", v_bool(true),
                      "type", v_str("`$STRING`")),
                    cmap(5,
                      "example", v_num(0),
                      "kind", v_str("query"),
                      "name", v_str("skip"),
                      "orig", v_str("skip"),
                      "type", v_str("`$INTEGER`")),
                    cmap(5,
                      "example", v_num(10),
                      "kind", v_str("query"),
                      "name", v_str("take"),
                      "orig", v_str("take"),
                      "type", v_str("`$INTEGER`")))),
                "kind", v_str("http"),
                "method", v_str("GET"),
                "orig", v_str("/locations"),
                "parts", clist(1,
                  v_str("locations")),
                "select", cmap(1,
                  "exist", clist(3,
                    v_str("client"),
                    v_str("skip"),
                    v_str("take"))),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`"))))),
          "load", cmap(3,
            "input", v_str("data"),
            "name", v_str("load"),
            "points", clist(1,
              cmap(7,
                "args", cmap(1,
                  "params", clist(1,
                    cmap(5,
                      "kind", v_str("param"),
                      "name", v_str("id"),
                      "orig", v_str("id"),
                      "reqd", v_bool(true),
                      "type", v_str("`$STRING`")))),
                "kind", v_str("http"),
                "method", v_str("GET"),
                "orig", v_str("/locations/{id}"),
                "parts", clist(2,
                  v_str("locations"),
                  v_str("{id}")),
                "select", cmap(1,
                  "exist", clist(1,
                    v_str("id"))),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`"))))),
          "remove", cmap(3,
            "input", v_str("data"),
            "name", v_str("remove"),
            "points", clist(1,
              cmap(7,
                "args", cmap(1,
                  "params", clist(1,
                    cmap(5,
                      "kind", v_str("param"),
                      "name", v_str("id"),
                      "orig", v_str("id"),
                      "reqd", v_bool(true),
                      "type", v_str("`$STRING`")))),
                "kind", v_str("http"),
                "method", v_str("DELETE"),
                "orig", v_str("/locations/{id}"),
                "parts", clist(2,
                  v_str("locations"),
                  v_str("{id}")),
                "select", cmap(1,
                  "exist", clist(1,
                    v_str("id"))),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")))))),
        "relations", cmap(1,
          "ancestors", v_list())),
      "partner", cmap(4,
        "fields", clist(14,
          cmap(2,
            "name", v_str("billingId"),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("clientCanOrderEquipment"),
            "type", v_str("`$BOOLEAN`")),
          cmap(3,
            "name", v_str("contact"),
            "op", cmap(1,
              "list", cmap(2,
                "req", v_bool(true),
                "type", v_str("`$OBJECT`"))),
            "type", v_str("`$OBJECT`")),
          cmap(2,
            "name", v_str("created"),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("id"),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("isActive"),
            "type", v_str("`$BOOLEAN`")),
          cmap(3,
            "name", v_str("location"),
            "req", v_bool(true),
            "type", v_str("`$OBJECT`")),
          cmap(2,
            "name", v_str("modified"),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("name"),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("parent"),
            "type", v_str("`$OBJECT`")),
          cmap(2,
            "name", v_str("partnerId"),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("reference"),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("verificationPhrase"),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("version"),
            "type", v_str("`$INTEGER`"))),
        "name", v_str("partner"),
        "op", cmap(3,
          "create", cmap(3,
            "input", v_str("data"),
            "name", v_str("create"),
            "points", clist(1,
              cmap(7,
                "args", v_map(),
                "kind", v_str("http"),
                "method", v_str("POST"),
                "orig", v_str("/partners"),
                "parts", clist(1,
                  v_str("partners")),
                "select", v_map(),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`"))))),
          "list", cmap(3,
            "input", v_str("data"),
            "name", v_str("list"),
            "points", clist(1,
              cmap(7,
                "args", cmap(1,
                  "query", clist(3,
                    cmap(4,
                      "kind", v_str("query"),
                      "name", v_str("partner"),
                      "orig", v_str("partner"),
                      "type", v_str("`$STRING`")),
                    cmap(5,
                      "example", v_num(0),
                      "kind", v_str("query"),
                      "name", v_str("skip"),
                      "orig", v_str("skip"),
                      "type", v_str("`$INTEGER`")),
                    cmap(5,
                      "example", v_num(10),
                      "kind", v_str("query"),
                      "name", v_str("take"),
                      "orig", v_str("take"),
                      "type", v_str("`$INTEGER`")))),
                "kind", v_str("http"),
                "method", v_str("GET"),
                "orig", v_str("/partners"),
                "parts", clist(1,
                  v_str("partners")),
                "select", cmap(1,
                  "exist", clist(3,
                    v_str("partner"),
                    v_str("skip"),
                    v_str("take"))),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`"))))),
          "load", cmap(3,
            "input", v_str("data"),
            "name", v_str("load"),
            "points", clist(1,
              cmap(7,
                "args", cmap(1,
                  "params", clist(1,
                    cmap(5,
                      "kind", v_str("param"),
                      "name", v_str("id"),
                      "orig", v_str("id"),
                      "reqd", v_bool(true),
                      "type", v_str("`$STRING`")))),
                "kind", v_str("http"),
                "method", v_str("GET"),
                "orig", v_str("/partners/{id}"),
                "parts", clist(2,
                  v_str("partners"),
                  v_str("{id}")),
                "select", cmap(1,
                  "exist", clist(1,
                    v_str("id"))),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")))))),
        "relations", cmap(1,
          "ancestors", v_list())),
      "shipment", cmap(4,
        "fields", clist(14,
          cmap(2,
            "name", v_str("carrier"),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("client"),
            "type", v_str("`$OBJECT`")),
          cmap(2,
            "name", v_str("created"),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("dateReceived"),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("dateShipped"),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("dcKif"),
            "type", v_str("`$OBJECT`")),
          cmap(2,
            "name", v_str("id"),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("items"),
            "type", v_str("`$ARRAY`")),
          cmap(2,
            "name", v_str("kif"),
            "type", v_str("`$OBJECT`")),
          cmap(2,
            "name", v_str("modified"),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("partner"),
            "type", v_str("`$OBJECT`")),
          cmap(2,
            "name", v_str("shipmentType"),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("tracking"),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("version"),
            "type", v_str("`$INTEGER`"))),
        "name", v_str("shipment"),
        "op", cmap(3,
          "create", cmap(3,
            "input", v_str("data"),
            "name", v_str("create"),
            "points", clist(1,
              cmap(7,
                "args", v_map(),
                "kind", v_str("http"),
                "method", v_str("POST"),
                "orig", v_str("/shipments"),
                "parts", clist(1,
                  v_str("shipments")),
                "select", v_map(),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`"))))),
          "list", cmap(3,
            "input", v_str("data"),
            "name", v_str("list"),
            "points", clist(1,
              cmap(7,
                "args", cmap(1,
                  "query", clist(4,
                    cmap(5,
                      "kind", v_str("query"),
                      "name", v_str("kif"),
                      "orig", v_str("kif"),
                      "reqd", v_bool(true),
                      "type", v_str("`$STRING`")),
                    cmap(4,
                      "kind", v_str("query"),
                      "name", v_str("mode"),
                      "orig", v_str("mode"),
                      "type", v_str("`$STRING`")),
                    cmap(5,
                      "example", v_num(0),
                      "kind", v_str("query"),
                      "name", v_str("skip"),
                      "orig", v_str("skip"),
                      "type", v_str("`$INTEGER`")),
                    cmap(5,
                      "example", v_num(10),
                      "kind", v_str("query"),
                      "name", v_str("take"),
                      "orig", v_str("take"),
                      "type", v_str("`$INTEGER`")))),
                "kind", v_str("http"),
                "method", v_str("GET"),
                "orig", v_str("/shipments"),
                "parts", clist(1,
                  v_str("shipments")),
                "select", cmap(1,
                  "exist", clist(4,
                    v_str("kif"),
                    v_str("mode"),
                    v_str("skip"),
                    v_str("take"))),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`"))))),
          "load", cmap(3,
            "input", v_str("data"),
            "name", v_str("load"),
            "points", clist(1,
              cmap(7,
                "args", cmap(1,
                  "params", clist(1,
                    cmap(5,
                      "kind", v_str("param"),
                      "name", v_str("id"),
                      "orig", v_str("id"),
                      "reqd", v_bool(true),
                      "type", v_str("`$STRING`")))),
                "kind", v_str("http"),
                "method", v_str("GET"),
                "orig", v_str("/shipments/{id}"),
                "parts", clist(2,
                  v_str("shipments"),
                  v_str("{id}")),
                "select", cmap(1,
                  "exist", clist(1,
                    v_str("id"))),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")))))),
        "relations", cmap(1,
          "ancestors", v_list())),
      "success", cmap(4,
        "fields", clist(1,
          cmap(2,
            "name", v_str("success"),
            "type", v_str("`$BOOLEAN`"))),
        "name", v_str("success"),
        "op", cmap(2,
          "create", cmap(3,
            "input", v_str("data"),
            "name", v_str("create"),
            "points", clist(1,
              cmap(8,
                "args", cmap(1,
                  "params", clist(1,
                    cmap(5,
                      "kind", v_str("param"),
                      "name", v_str("share_partner_to"),
                      "orig", v_str("share_partner_to"),
                      "reqd", v_bool(true),
                      "type", v_str("`$STRING`")))),
                "kind", v_str("http"),
                "method", v_str("POST"),
                "orig", v_str("/virtualDevices/{sharePartnerTo}"),
                "parts", clist(2,
                  v_str("virtualDevices"),
                  v_str("{share_partner_to}")),
                "rename", cmap(1,
                  "param", cmap(1,
                    "sharePartnerTo", v_str("share_partner_to"))),
                "select", cmap(1,
                  "exist", clist(1,
                    v_str("share_partner_to"))),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`"))))),
          "remove", cmap(3,
            "input", v_str("data"),
            "name", v_str("remove"),
            "points", clist(1,
              cmap(8,
                "args", cmap(1,
                  "params", clist(1,
                    cmap(5,
                      "kind", v_str("param"),
                      "name", v_str("share_partner_to"),
                      "orig", v_str("share_partner_to"),
                      "reqd", v_bool(true),
                      "type", v_str("`$STRING`")))),
                "kind", v_str("http"),
                "method", v_str("DELETE"),
                "orig", v_str("/virtualDevices/{sharePartnerTo}"),
                "parts", clist(2,
                  v_str("virtualDevices"),
                  v_str("{share_partner_to}")),
                "rename", cmap(1,
                  "param", cmap(1,
                    "sharePartnerTo", v_str("share_partner_to"))),
                "select", cmap(1,
                  "exist", clist(1,
                    v_str("share_partner_to"))),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")))))),
        "relations", cmap(1,
          "ancestors", clist(1,
            clist(1,
              v_str("virtual_device"))))),
      "transaction", cmap(4,
        "fields", clist(24,
          cmap(2,
            "name", v_str("alternateKey"),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("client"),
            "type", v_str("`$OBJECT`")),
          cmap(2,
            "name", v_str("clientRef"),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("created"),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("decrypted"),
            "type", v_str("`$INTEGER`")),
          cmap(2,
            "name", v_str("deviceName"),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("directPartner"),
            "type", v_str("`$OBJECT`")),
          cmap(2,
            "name", v_str("encrypted"),
            "type", v_str("`$INTEGER`")),
          cmap(2,
            "name", v_str("endDate"),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("errCode"),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("errMessage"),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("id"),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("ipAddress"),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("isVirtual"),
            "type", v_str("`$BOOLEAN`")),
          cmap(2,
            "name", v_str("keyType"),
            "type", v_str("`$STRING`")),
          cmap(3,
            "name", v_str("location"),
            "req", v_bool(true),
            "type", v_str("`$OBJECT`")),
          cmap(2,
            "name", v_str("messageId"),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("method"),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("partner"),
            "type", v_str("`$OBJECT`")),
          cmap(2,
            "name", v_str("reference"),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("serialNumber"),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("startDate"),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("success"),
            "type", v_str("`$BOOLEAN`")),
          cmap(2,
            "name", v_str("transactionSource"),
            "type", v_str("`$STRING`"))),
        "name", v_str("transaction"),
        "op", cmap(3,
          "create", cmap(3,
            "input", v_str("data"),
            "name", v_str("create"),
            "points", clist(1,
              cmap(7,
                "args", v_map(),
                "kind", v_str("http"),
                "method", v_str("POST"),
                "orig", v_str("/transactions"),
                "parts", clist(1,
                  v_str("transactions")),
                "select", v_map(),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`"))))),
          "list", cmap(3,
            "input", v_str("data"),
            "name", v_str("list"),
            "points", clist(1,
              cmap(7,
                "args", cmap(1,
                  "query", clist(13,
                    cmap(4,
                      "kind", v_str("query"),
                      "name", v_str("client"),
                      "orig", v_str("client"),
                      "type", v_str("`$STRING`")),
                    cmap(4,
                      "kind", v_str("query"),
                      "name", v_str("client_ref"),
                      "orig", v_str("client_ref"),
                      "type", v_str("`$STRING`")),
                    cmap(4,
                      "kind", v_str("query"),
                      "name", v_str("date_from"),
                      "orig", v_str("date_from"),
                      "type", v_str("`$STRING`")),
                    cmap(4,
                      "kind", v_str("query"),
                      "name", v_str("date_to"),
                      "orig", v_str("date_to"),
                      "type", v_str("`$STRING`")),
                    cmap(4,
                      "kind", v_str("query"),
                      "name", v_str("location"),
                      "orig", v_str("location"),
                      "type", v_str("`$STRING`")),
                    cmap(4,
                      "kind", v_str("query"),
                      "name", v_str("message_id"),
                      "orig", v_str("message_id"),
                      "type", v_str("`$STRING`")),
                    cmap(5,
                      "example", v_str("nocount"),
                      "kind", v_str("query"),
                      "name", v_str("paging_mode"),
                      "orig", v_str("paging_mode"),
                      "type", v_str("`$STRING`")),
                    cmap(4,
                      "kind", v_str("query"),
                      "name", v_str("partner"),
                      "orig", v_str("partner"),
                      "type", v_str("`$STRING`")),
                    cmap(4,
                      "kind", v_str("query"),
                      "name", v_str("reference"),
                      "orig", v_str("reference"),
                      "type", v_str("`$STRING`")),
                    cmap(4,
                      "kind", v_str("query"),
                      "name", v_str("serial_number"),
                      "orig", v_str("serial_number"),
                      "type", v_str("`$STRING`")),
                    cmap(5,
                      "example", v_num(0),
                      "kind", v_str("query"),
                      "name", v_str("skip"),
                      "orig", v_str("skip"),
                      "type", v_str("`$INTEGER`")),
                    cmap(4,
                      "kind", v_str("query"),
                      "name", v_str("success"),
                      "orig", v_str("success"),
                      "type", v_str("`$BOOLEAN`")),
                    cmap(5,
                      "example", v_num(10),
                      "kind", v_str("query"),
                      "name", v_str("take"),
                      "orig", v_str("take"),
                      "type", v_str("`$INTEGER`")))),
                "kind", v_str("http"),
                "method", v_str("GET"),
                "orig", v_str("/transactions"),
                "parts", clist(1,
                  v_str("transactions")),
                "select", cmap(1,
                  "exist", clist(13,
                    v_str("client"),
                    v_str("client_ref"),
                    v_str("date_from"),
                    v_str("date_to"),
                    v_str("location"),
                    v_str("message_id"),
                    v_str("paging_mode"),
                    v_str("partner"),
                    v_str("reference"),
                    v_str("serial_number"),
                    v_str("skip"),
                    v_str("success"),
                    v_str("take"))),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`"))))),
          "load", cmap(3,
            "input", v_str("data"),
            "name", v_str("load"),
            "points", clist(1,
              cmap(7,
                "args", cmap(1,
                  "params", clist(1,
                    cmap(5,
                      "kind", v_str("param"),
                      "name", v_str("id"),
                      "orig", v_str("id"),
                      "reqd", v_bool(true),
                      "type", v_str("`$STRING`")))),
                "kind", v_str("http"),
                "method", v_str("GET"),
                "orig", v_str("/transactions/{id}"),
                "parts", clist(2,
                  v_str("transactions"),
                  v_str("{id}")),
                "select", cmap(1,
                  "exist", clist(1,
                    v_str("id"))),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")))))),
        "relations", cmap(1,
          "ancestors", v_list())),
      "update_result", cmap(4,
        "fields", clist(12,
          cmap(2,
            "name", v_str("client"),
            "type", v_str("`$OBJECT`")),
          cmap(2,
            "name", v_str("email"),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("firstName"),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("id"),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("isActive"),
            "type", v_str("`$BOOLEAN`")),
          cmap(2,
            "name", v_str("kif"),
            "type", v_str("`$OBJECT`")),
          cmap(2,
            "name", v_str("lastName"),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("partner"),
            "type", v_str("`$OBJECT`")),
          cmap(2,
            "name", v_str("phone"),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("userName"),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("userRole"),
            "type", v_str("`$OBJECT`")),
          cmap(2,
            "name", v_str("version"),
            "type", v_str("`$INTEGER`"))),
        "name", v_str("update_result"),
        "op", cmap(3,
          "create", cmap(3,
            "input", v_str("data"),
            "name", v_str("create"),
            "points", clist(1,
              cmap(7,
                "args", v_map(),
                "kind", v_str("http"),
                "method", v_str("POST"),
                "orig", v_str("/users"),
                "parts", clist(1,
                  v_str("users")),
                "select", v_map(),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`"))))),
          "list", cmap(3,
            "input", v_str("data"),
            "name", v_str("list"),
            "points", clist(1,
              cmap(7,
                "args", cmap(1,
                  "query", clist(5,
                    cmap(4,
                      "kind", v_str("query"),
                      "name", v_str("client"),
                      "orig", v_str("client"),
                      "type", v_str("`$STRING`")),
                    cmap(4,
                      "kind", v_str("query"),
                      "name", v_str("kif"),
                      "orig", v_str("kif"),
                      "type", v_str("`$STRING`")),
                    cmap(4,
                      "kind", v_str("query"),
                      "name", v_str("partner"),
                      "orig", v_str("partner"),
                      "type", v_str("`$ANY`")),
                    cmap(5,
                      "example", v_num(0),
                      "kind", v_str("query"),
                      "name", v_str("skip"),
                      "orig", v_str("skip"),
                      "type", v_str("`$INTEGER`")),
                    cmap(5,
                      "example", v_num(10),
                      "kind", v_str("query"),
                      "name", v_str("take"),
                      "orig", v_str("take"),
                      "type", v_str("`$INTEGER`")))),
                "kind", v_str("http"),
                "method", v_str("GET"),
                "orig", v_str("/users"),
                "parts", clist(1,
                  v_str("users")),
                "select", cmap(1,
                  "exist", clist(5,
                    v_str("client"),
                    v_str("kif"),
                    v_str("partner"),
                    v_str("skip"),
                    v_str("take"))),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`"))))),
          "update", cmap(3,
            "input", v_str("data"),
            "name", v_str("update"),
            "points", clist(7,
              cmap(7,
                "args", cmap(1,
                  "params", clist(1,
                    cmap(5,
                      "kind", v_str("param"),
                      "name", v_str("id"),
                      "orig", v_str("id"),
                      "reqd", v_bool(true),
                      "type", v_str("`$STRING`")))),
                "kind", v_str("http"),
                "method", v_str("PATCH"),
                "orig", v_str("/clients/{id}"),
                "parts", clist(2,
                  v_str("clients"),
                  v_str("{id}")),
                "select", cmap(1,
                  "exist", clist(1,
                    v_str("id"))),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`"))),
              cmap(7,
                "args", cmap(1,
                  "params", clist(1,
                    cmap(5,
                      "kind", v_str("param"),
                      "name", v_str("id"),
                      "orig", v_str("id"),
                      "reqd", v_bool(true),
                      "type", v_str("`$STRING`")))),
                "kind", v_str("http"),
                "method", v_str("PATCH"),
                "orig", v_str("/devices/{id}"),
                "parts", clist(2,
                  v_str("devices"),
                  v_str("{id}")),
                "select", cmap(1,
                  "exist", clist(1,
                    v_str("id"))),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`"))),
              cmap(7,
                "args", cmap(1,
                  "params", clist(1,
                    cmap(5,
                      "kind", v_str("param"),
                      "name", v_str("id"),
                      "orig", v_str("id"),
                      "reqd", v_bool(true),
                      "type", v_str("`$STRING`")))),
                "kind", v_str("http"),
                "method", v_str("PATCH"),
                "orig", v_str("/locations/{id}"),
                "parts", clist(2,
                  v_str("locations"),
                  v_str("{id}")),
                "select", cmap(1,
                  "exist", clist(1,
                    v_str("id"))),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`"))),
              cmap(7,
                "args", cmap(1,
                  "params", clist(1,
                    cmap(5,
                      "kind", v_str("param"),
                      "name", v_str("id"),
                      "orig", v_str("id"),
                      "reqd", v_bool(true),
                      "type", v_str("`$STRING`")))),
                "kind", v_str("http"),
                "method", v_str("PATCH"),
                "orig", v_str("/partners/{id}"),
                "parts", clist(2,
                  v_str("partners"),
                  v_str("{id}")),
                "select", cmap(1,
                  "exist", clist(1,
                    v_str("id"))),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`"))),
              cmap(7,
                "args", cmap(1,
                  "params", clist(1,
                    cmap(5,
                      "kind", v_str("param"),
                      "name", v_str("id"),
                      "orig", v_str("id"),
                      "reqd", v_bool(true),
                      "type", v_str("`$STRING`")))),
                "kind", v_str("http"),
                "method", v_str("PATCH"),
                "orig", v_str("/shipments/{id}"),
                "parts", clist(2,
                  v_str("shipments"),
                  v_str("{id}")),
                "select", cmap(1,
                  "exist", clist(1,
                    v_str("id"))),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`"))),
              cmap(7,
                "args", cmap(1,
                  "params", clist(1,
                    cmap(5,
                      "kind", v_str("param"),
                      "name", v_str("id"),
                      "orig", v_str("id"),
                      "reqd", v_bool(true),
                      "type", v_str("`$STRING`")))),
                "kind", v_str("http"),
                "method", v_str("PATCH"),
                "orig", v_str("/transactions/{id}"),
                "parts", clist(2,
                  v_str("transactions"),
                  v_str("{id}")),
                "select", cmap(1,
                  "exist", clist(1,
                    v_str("id"))),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`"))),
              cmap(7,
                "args", cmap(1,
                  "params", clist(1,
                    cmap(5,
                      "kind", v_str("param"),
                      "name", v_str("id"),
                      "orig", v_str("id"),
                      "reqd", v_bool(true),
                      "type", v_str("`$STRING`")))),
                "kind", v_str("http"),
                "method", v_str("PATCH"),
                "orig", v_str("/users/{id}"),
                "parts", clist(2,
                  v_str("users"),
                  v_str("{id}")),
                "select", cmap(1,
                  "exist", clist(1,
                    v_str("id"))),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")))))),
        "relations", cmap(1,
          "ancestors", v_list())),
      "user", cmap(4,
        "fields", clist(14,
          cmap(2,
            "name", v_str("client"),
            "type", v_str("`$OBJECT`")),
          cmap(2,
            "name", v_str("created"),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("email"),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("firstName"),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("id"),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("isActive"),
            "type", v_str("`$BOOLEAN`")),
          cmap(2,
            "name", v_str("kif"),
            "type", v_str("`$OBJECT`")),
          cmap(2,
            "name", v_str("lastName"),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("modified"),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("partner"),
            "type", v_str("`$OBJECT`")),
          cmap(2,
            "name", v_str("phone"),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("userName"),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("userRole"),
            "type", v_str("`$OBJECT`")),
          cmap(2,
            "name", v_str("version"),
            "type", v_str("`$INTEGER`"))),
        "name", v_str("user"),
        "op", cmap(2,
          "load", cmap(3,
            "input", v_str("data"),
            "name", v_str("load"),
            "points", clist(1,
              cmap(7,
                "args", cmap(1,
                  "params", clist(1,
                    cmap(5,
                      "kind", v_str("param"),
                      "name", v_str("id"),
                      "orig", v_str("id"),
                      "reqd", v_bool(true),
                      "type", v_str("`$STRING`")))),
                "kind", v_str("http"),
                "method", v_str("GET"),
                "orig", v_str("/users/{id}"),
                "parts", clist(2,
                  v_str("users"),
                  v_str("{id}")),
                "select", cmap(1,
                  "exist", clist(1,
                    v_str("id"))),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`"))))),
          "remove", cmap(3,
            "input", v_str("data"),
            "name", v_str("remove"),
            "points", clist(1,
              cmap(7,
                "args", cmap(1,
                  "params", clist(1,
                    cmap(5,
                      "kind", v_str("param"),
                      "name", v_str("id"),
                      "orig", v_str("id"),
                      "reqd", v_bool(true),
                      "type", v_str("`$STRING`")))),
                "kind", v_str("http"),
                "method", v_str("DELETE"),
                "orig", v_str("/users/{id}"),
                "parts", clist(2,
                  v_str("users"),
                  v_str("{id}")),
                "select", cmap(1,
                  "exist", clist(1,
                    v_str("id"))),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")))))),
        "relations", cmap(1,
          "ancestors", v_list()))));
}

Feature* make_feature(const char* name) {
  if (strcmp(name, "test") == 0) return feature_test_new();
  return feature_base_new();
}
