// Generated by sdkgen go-mcp target.
package main

import (
	"context"
	"encoding/json"
	"fmt"
	"strings"

	"github.com/modelcontextprotocol/go-sdk/mcp"
	sdk "github.com/voxgig-sdk/bluefin-decryptx-p2pe-sdk/go"
)

// Args is the common argument shape for both tools. `entity` selects
// the SDK entity to operate on; `query` is the optional reqmatch /
// reqdata map passed through to the SDK. For load, `query` should be
// `{"id": <value>}`. For list, omit `query` or pass an empty map.
type Args struct {
	Entity string         `json:"entity" jsonschema:"attestation | client | create_result | decryption | device | device_build | device_custody_detail | device_custody_list | device_list | device_receive_result | device_rki_activate_result | device_state | device_type | inject_key | kif | location | partner | shipment | success | transaction | update_result | user"`
	Query  map[string]any `json:"query,omitempty" jsonschema:"optional match map e.g. {\"id\":1} for load, omit for list"`
}

func registerTools(server *mcp.Server, client *sdk.BluefinDecryptxP2peSDK) {
	mcp.AddTool(server, &mcp.Tool{
		Name: "bluefin-decryptx-p2pe_list",
		Description: "List records from BluefinDecryptxP2pe. " +
			"Args: entity (one of the supported SDK entities), query (optional filter map). " +
			"Returns the first page of records as JSON.",
	}, func(ctx context.Context, req *mcp.CallToolRequest, args Args) (*mcp.CallToolResult, any, error) {
		return runOp(client, "list", args)
	})

	mcp.AddTool(server, &mcp.Tool{
		Name: "bluefin-decryptx-p2pe_load",
		Description: "Load a single record from BluefinDecryptxP2pe. " +
			"Args: entity, query ({\"id\":N} required). Returns the record as JSON.",
	}, func(ctx context.Context, req *mcp.CallToolRequest, args Args) (*mcp.CallToolResult, any, error) {
		return runOp(client, "load", args)
	})
}

func runOp(client *sdk.BluefinDecryptxP2peSDK, op string, args Args) (*mcp.CallToolResult, any, error) {
	ent, err := entityFor(client, args.Entity)
	if err != nil {
		return toolError(err.Error())
	}

	var result any
	switch op {
	case "list":
		result, err = ent.List(args.Query, nil)
	case "load":
		result, err = ent.Load(args.Query, nil)
	default:
		return toolError(fmt.Sprintf("unknown op %q", op))
	}
	if err != nil {
		return toolError(err.Error())
	}

	// SDK returns *Entity wrappers; unwrap each via .Data() to get a
	// plain map[string]any (or []any of maps for list) suitable for
	// JSON marshalling.
	data := extractData(result)
	body, err := json.MarshalIndent(data, "", "  ")
	if err != nil {
		return toolError(fmt.Sprintf("marshal: %v", err))
	}
	return &mcp.CallToolResult{
		Content: []mcp.Content{
			&mcp.TextContent{Text: string(body)},
		},
	}, data, nil
}

// entityFor dispatches on the lowercase entity name. The generator
// emits one `case "<name>":` per entity defined in the SDK model.
func entityFor(client *sdk.BluefinDecryptxP2peSDK, name string) (sdk.BluefinDecryptxP2peEntity, error) {
	switch strings.ToLower(name) {
	case "attestation":
		return client.Attestation(nil), nil
	case "client":
		return client.Client(nil), nil
	case "create_result":
		return client.CreateResult(nil), nil
	case "decryption":
		return client.Decryption(nil), nil
	case "device":
		return client.Device(nil), nil
	case "device_build":
		return client.DeviceBuild(nil), nil
	case "device_custody_detail":
		return client.DeviceCustodyDetail(nil), nil
	case "device_custody_list":
		return client.DeviceCustodyList(nil), nil
	case "device_list":
		return client.DeviceList(nil), nil
	case "device_receive_result":
		return client.DeviceReceiveResult(nil), nil
	case "device_rki_activate_result":
		return client.DeviceRkiActivateResult(nil), nil
	case "device_state":
		return client.DeviceState(nil), nil
	case "device_type":
		return client.DeviceType(nil), nil
	case "inject_key":
		return client.InjectKey(nil), nil
	case "kif":
		return client.Kif(nil), nil
	case "location":
		return client.Location(nil), nil
	case "partner":
		return client.Partner(nil), nil
	case "shipment":
		return client.Shipment(nil), nil
	case "success":
		return client.Success(nil), nil
	case "transaction":
		return client.Transaction(nil), nil
	case "update_result":
		return client.UpdateResult(nil), nil
	case "user":
		return client.User(nil), nil

	}
	return nil, fmt.Errorf("unknown entity %q", name)
}

// extractData walks an SDK result and replaces any sdk.Entity wrapper
// with its underlying record (via .Data()).
func extractData(x any) any {
	switch v := x.(type) {
	case sdk.Entity:
		return extractData(v.Data())
	case []any:
		out := make([]any, len(v))
		for i, e := range v {
			out[i] = extractData(e)
		}
		return out
	case map[string]any:
		out := make(map[string]any, len(v))
		for k, vv := range v {
			out[k] = extractData(vv)
		}
		return out
	}
	return x
}

func toolError(msg string) (*mcp.CallToolResult, any, error) {
	return &mcp.CallToolResult{
		IsError: true,
		Content: []mcp.Content{
			&mcp.TextContent{Text: msg},
		},
	}, nil, nil
}
