(* BluefinDecryptxP2pe SDK client (generated by @voxgig/sdkgen).
 *
 * The SDK "object" is the runtime sdk_client record (see Sdk_types). These
 * constructors wire the embedded config + feature factory (Sdk_config) into
 * the API-agnostic client builders (Sdk_features.make_client_base / sdk_test).
 * Entity accessors return an entity_obj whose CRUD closures run the pipeline. *)

open Voxgig_struct
open Sdk_types
open Sdk_features

(* Construct a live client from options (Noval for defaults). *)
let make (options : value) : sdk_client =
  make_client_base
    ~config:(Sdk_config.make_config ())
    ~make_feature:Sdk_config.make_feature
    options

(* No-argument convenience constructor. *)
let make0 () : sdk_client = make Noval

(* Construct a client in test mode (in-memory mock transport). *)
let test () : sdk_client =
  sdk_test
    ~config:(Sdk_config.make_config ())
    ~make_feature:Sdk_config.make_feature
    Noval Noval

(* Test-mode client with explicit test / sdk options. *)
let test_with (testopts : value) (sdkopts : value) : sdk_client =
  sdk_test
    ~config:(Sdk_config.make_config ())
    ~make_feature:Sdk_config.make_feature
    testopts sdkopts

(* Low-level escape hatches (raw transport call / request preparation). *)
let direct (client : sdk_client) (fetchargs : value) : value =
  Sdk_features.direct client fetchargs

let graphql (client : sdk_client) (query : string) (variables : value)
    (ctrl : value) : value =
  Sdk_features.graphql client query variables ctrl

let prepare (client : sdk_client) (fetchargs : value) : value =
  Sdk_features.prepare client fetchargs

(* Attestation entity bound to a client:  attestation client entopts *)
let attestation (client : sdk_client) (entopts : value) : entity_obj =
  Sdk_entity_attestation.make client entopts

(* Client entity bound to a client:  client client entopts *)
let client (client : sdk_client) (entopts : value) : entity_obj =
  Sdk_entity_client.make client entopts

(* CreateResult entity bound to a client:  create_result client entopts *)
let create_result (client : sdk_client) (entopts : value) : entity_obj =
  Sdk_entity_create_result.make client entopts

(* Decryption entity bound to a client:  decryption client entopts *)
let decryption (client : sdk_client) (entopts : value) : entity_obj =
  Sdk_entity_decryption.make client entopts

(* Device entity bound to a client:  device client entopts *)
let device (client : sdk_client) (entopts : value) : entity_obj =
  Sdk_entity_device.make client entopts

(* DeviceBuild entity bound to a client:  device_build client entopts *)
let device_build (client : sdk_client) (entopts : value) : entity_obj =
  Sdk_entity_device_build.make client entopts

(* DeviceCustodyDetail entity bound to a client:  device_custody_detail client entopts *)
let device_custody_detail (client : sdk_client) (entopts : value) : entity_obj =
  Sdk_entity_device_custody_detail.make client entopts

(* DeviceCustodyList entity bound to a client:  device_custody_list client entopts *)
let device_custody_list (client : sdk_client) (entopts : value) : entity_obj =
  Sdk_entity_device_custody_list.make client entopts

(* DeviceList entity bound to a client:  device_list client entopts *)
let device_list (client : sdk_client) (entopts : value) : entity_obj =
  Sdk_entity_device_list.make client entopts

(* DeviceReceiveResult entity bound to a client:  device_receive_result client entopts *)
let device_receive_result (client : sdk_client) (entopts : value) : entity_obj =
  Sdk_entity_device_receive_result.make client entopts

(* DeviceRkiActivateResult entity bound to a client:  device_rki_activate_result client entopts *)
let device_rki_activate_result (client : sdk_client) (entopts : value) : entity_obj =
  Sdk_entity_device_rki_activate_result.make client entopts

(* DeviceState entity bound to a client:  device_state client entopts *)
let device_state (client : sdk_client) (entopts : value) : entity_obj =
  Sdk_entity_device_state.make client entopts

(* DeviceType entity bound to a client:  device_type client entopts *)
let device_type (client : sdk_client) (entopts : value) : entity_obj =
  Sdk_entity_device_type.make client entopts

(* InjectKey entity bound to a client:  inject_key client entopts *)
let inject_key (client : sdk_client) (entopts : value) : entity_obj =
  Sdk_entity_inject_key.make client entopts

(* Kif entity bound to a client:  kif client entopts *)
let kif (client : sdk_client) (entopts : value) : entity_obj =
  Sdk_entity_kif.make client entopts

(* Location entity bound to a client:  location client entopts *)
let location (client : sdk_client) (entopts : value) : entity_obj =
  Sdk_entity_location.make client entopts

(* Partner entity bound to a client:  partner client entopts *)
let partner (client : sdk_client) (entopts : value) : entity_obj =
  Sdk_entity_partner.make client entopts

(* Shipment entity bound to a client:  shipment client entopts *)
let shipment (client : sdk_client) (entopts : value) : entity_obj =
  Sdk_entity_shipment.make client entopts

(* Success entity bound to a client:  success client entopts *)
let success (client : sdk_client) (entopts : value) : entity_obj =
  Sdk_entity_success.make client entopts

(* Transaction entity bound to a client:  transaction client entopts *)
let transaction (client : sdk_client) (entopts : value) : entity_obj =
  Sdk_entity_transaction.make client entopts

(* UpdateResult entity bound to a client:  update_result client entopts *)
let update_result (client : sdk_client) (entopts : value) : entity_obj =
  Sdk_entity_update_result.make client entopts

(* User entity bound to a client:  user client entopts *)
let user (client : sdk_client) (entopts : value) : entity_obj =
  Sdk_entity_user.make client entopts
