-- BluefinDecryptxP2pe SDK public client (generated by @voxgig/sdkgen).
--
-- SDK constructors (newSdk / testSdk) and one accessor per entity. Entities
-- are generic — every accessor calls the config-driven F.makeEntity, so the
-- operation pipeline is identical for every entity and every API.

module SdkClient
  ( module SdkTypes
  , newSdk
  , newSdk0
  , testSdk
  , testSdk0
  , attestation
  , client
  , create_result
  , decryption
  , device
  , device_build
  , device_custody_detail
  , device_custody_list
  , device_list
  , device_receive_result
  , device_rki_activate_result
  , device_state
  , device_type
  , inject_key
  , kif
  , location
  , partner
  , shipment
  , success
  , transaction
  , update_result
  , user
  ) where

import Data.IORef (readIORef)

import VoxgigStruct (Value (..))
import SdkTypes
import SdkConfig (makeConfig, makeFeature)
import qualified SdkFeatures as F

-- | Construct a live SDK client from an options map (Noval for defaults).
newSdk :: Value -> IO Client
newSdk options = do
  cfg <- makeConfig
  F.makeClientBase cfg makeFeature options

-- | No-argument convenience constructor.
newSdk0 :: IO Client
newSdk0 = newSdk VNoval

-- | Construct a test-mode SDK: testSdk testopts sdkopts.
testSdk :: Value -> Value -> IO Client
testSdk testopts sdkopts = do
  cfg <- makeConfig
  F.sdkTest cfg makeFeature testopts sdkopts

-- | No-argument convenience test constructor.
testSdk0 :: IO Client
testSdk0 = testSdk VNoval VNoval

-- | The active client mode ("live" or "test").
clientMode :: Client -> IO String
clientMode = readIORef . clMode

-- | The Attestation entity bound to this client.
attestation :: Client -> Value -> IO Entity
attestation client entopts = F.makeEntity client "attestation" entopts

-- | The Client entity bound to this client.
client :: Client -> Value -> IO Entity
client client entopts = F.makeEntity client "client" entopts

-- | The CreateResult entity bound to this client.
create_result :: Client -> Value -> IO Entity
create_result client entopts = F.makeEntity client "create_result" entopts

-- | The Decryption entity bound to this client.
decryption :: Client -> Value -> IO Entity
decryption client entopts = F.makeEntity client "decryption" entopts

-- | The Device entity bound to this client.
device :: Client -> Value -> IO Entity
device client entopts = F.makeEntity client "device" entopts

-- | The DeviceBuild entity bound to this client.
device_build :: Client -> Value -> IO Entity
device_build client entopts = F.makeEntity client "device_build" entopts

-- | The DeviceCustodyDetail entity bound to this client.
device_custody_detail :: Client -> Value -> IO Entity
device_custody_detail client entopts = F.makeEntity client "device_custody_detail" entopts

-- | The DeviceCustodyList entity bound to this client.
device_custody_list :: Client -> Value -> IO Entity
device_custody_list client entopts = F.makeEntity client "device_custody_list" entopts

-- | The DeviceList entity bound to this client.
device_list :: Client -> Value -> IO Entity
device_list client entopts = F.makeEntity client "device_list" entopts

-- | The DeviceReceiveResult entity bound to this client.
device_receive_result :: Client -> Value -> IO Entity
device_receive_result client entopts = F.makeEntity client "device_receive_result" entopts

-- | The DeviceRkiActivateResult entity bound to this client.
device_rki_activate_result :: Client -> Value -> IO Entity
device_rki_activate_result client entopts = F.makeEntity client "device_rki_activate_result" entopts

-- | The DeviceState entity bound to this client.
device_state :: Client -> Value -> IO Entity
device_state client entopts = F.makeEntity client "device_state" entopts

-- | The DeviceType entity bound to this client.
device_type :: Client -> Value -> IO Entity
device_type client entopts = F.makeEntity client "device_type" entopts

-- | The InjectKey entity bound to this client.
inject_key :: Client -> Value -> IO Entity
inject_key client entopts = F.makeEntity client "inject_key" entopts

-- | The Kif entity bound to this client.
kif :: Client -> Value -> IO Entity
kif client entopts = F.makeEntity client "kif" entopts

-- | The Location entity bound to this client.
location :: Client -> Value -> IO Entity
location client entopts = F.makeEntity client "location" entopts

-- | The Partner entity bound to this client.
partner :: Client -> Value -> IO Entity
partner client entopts = F.makeEntity client "partner" entopts

-- | The Shipment entity bound to this client.
shipment :: Client -> Value -> IO Entity
shipment client entopts = F.makeEntity client "shipment" entopts

-- | The Success entity bound to this client.
success :: Client -> Value -> IO Entity
success client entopts = F.makeEntity client "success" entopts

-- | The Transaction entity bound to this client.
transaction :: Client -> Value -> IO Entity
transaction client entopts = F.makeEntity client "transaction" entopts

-- | The UpdateResult entity bound to this client.
update_result :: Client -> Value -> IO Entity
update_result client entopts = F.makeEntity client "update_result" entopts

-- | The User entity bound to this client.
user :: Client -> Value -> IO Entity
user client entopts = F.makeEntity client "user" entopts

