-- BluefinDecryptxP2pe SDK test runner (generated by @voxgig/sdkgen).
--
-- OFFLINE lane (always): a test-mode client seeded from the generated entity
-- test data answers operations from an in-memory store — no server needed.
-- LIVE lane (only when SDK_TEST_BASE is set): the same flow over real HTTP.

import VoxgigStruct
import SdkJson
import SdkRuntime
import SdkClient

open VoxgigStruct

initialize npass : IO.Ref Nat ← IO.mkRef 0
initialize nfail : IO.Ref Nat ← IO.mkRef 0

def pass (msg : String) : SIO Unit := do
  npass.modify (· + 1)
  IO.println s!"ok   - {msg}"

def fail (msg : String) : SIO Unit := do
  nfail.modify (· + 1)
  IO.println s!"FAIL - {msg}"

def defaultBase : String := "http://localhost:8901"

def main : IO UInt32 := do
  let liveBase ← IO.getEnv "SDK_TEST_BASE"
  let ctx ← mkCtx
  let offline : SIO Unit := do
    -- attestation: offline (test-mode) entity behaviour
    (do
      let seedPath := "../.sdk/test/entity/attestation/AttestationTestData.json"
      if !(← System.FilePath.pathExists seedPath) then
        IO.println s!"skip - attestation: no seed at {seedPath}"
      else do
        let seed ← SdkJson.jsonRead (← IO.FS.readFile seedPath)
        let tclient ← Sdk.testSdk0 seed
        let existing ← SdkRuntime.gp (← SdkRuntime.gp seed "existing") "attestation"
        let ids ← keysof existing
        -- list returns every seeded entity
        let items ← Attestation.list tclient (← emptyMap) (← emptyMap)
        let n ← (match items with | Value.list lid => do pure (← listItems lid).size | _ => pure 0)
        if n == ids.size then pass s!"attestation.list offline -> {n} seeded"
        else fail s!"attestation.list offline: got {n}, want {ids.size}"
        -- load the first seeded entity by id
        if ids.size > 0 then do
          let wid := ids[0]!
          let m ← newMap #[("id", Value.str wid)]
          let got ← Attestation.load tclient m (← emptyMap)
          let gid ← SdkRuntime.gpS got "id"
          if gid == wid then pass s!"attestation.load offline (id={wid})"
          else fail s!"attestation.load offline: got {gid}, want {wid}"
)
    -- client: offline (test-mode) entity behaviour
    (do
      let seedPath := "../.sdk/test/entity/client/ClientTestData.json"
      if !(← System.FilePath.pathExists seedPath) then
        IO.println s!"skip - client: no seed at {seedPath}"
      else do
        let seed ← SdkJson.jsonRead (← IO.FS.readFile seedPath)
        let tclient ← Sdk.testSdk0 seed
        let existing ← SdkRuntime.gp (← SdkRuntime.gp seed "existing") "client"
        let ids ← keysof existing
        -- list returns every seeded entity
        let items ← Client.list tclient (← emptyMap) (← emptyMap)
        let n ← (match items with | Value.list lid => do pure (← listItems lid).size | _ => pure 0)
        if n == ids.size then pass s!"client.list offline -> {n} seeded"
        else fail s!"client.list offline: got {n}, want {ids.size}"
        -- load the first seeded entity by id
        if ids.size > 0 then do
          let wid := ids[0]!
          let m ← newMap #[("id", Value.str wid)]
          let got ← Client.load tclient m (← emptyMap)
          let gid ← SdkRuntime.gpS got "id"
          if gid == wid then pass s!"client.load offline (id={wid})"
          else fail s!"client.load offline: got {gid}, want {wid}"
        -- create -> load back -> remove, all in the store
        let newmap ← SdkRuntime.gp (← SdkRuntime.gp seed "new") "client"
        let nks ← keysof newmap
        if nks.size > 0 then do
          let payload ← SdkRuntime.gp newmap nks[0]!
          let created ← Client.create tclient payload (← emptyMap)
          let cid ← SdkRuntime.gpS created "id"
          if cid == "" then fail "client.create offline returned no id" else do
            let m2 ← newMap #[("id", Value.str cid)]
            let back ← Client.load tclient m2 (← emptyMap)
            if (← SdkRuntime.gpS back "id") == cid then
              pass s!"client.create/load offline (id={cid})"
            else fail s!"client.create/load offline mismatch"
            let _ ← Client.remove tclient m2 (← emptyMap)
            let gone ← Client.load tclient m2 (← emptyMap)
            match gone with
            | Value.map _ => fail s!"client.remove offline: still present"
            | _ => pass s!"client.remove offline (id={cid})"
)
    -- device: offline (test-mode) entity behaviour
    (do
      let seedPath := "../.sdk/test/entity/device/DeviceTestData.json"
      if !(← System.FilePath.pathExists seedPath) then
        IO.println s!"skip - device: no seed at {seedPath}"
      else do
        let seed ← SdkJson.jsonRead (← IO.FS.readFile seedPath)
        let tclient ← Sdk.testSdk0 seed
        let existing ← SdkRuntime.gp (← SdkRuntime.gp seed "existing") "device"
        let ids ← keysof existing
        -- list returns every seeded entity
        let items ← Device.list tclient (← emptyMap) (← emptyMap)
        let n ← (match items with | Value.list lid => do pure (← listItems lid).size | _ => pure 0)
        if n == ids.size then pass s!"device.list offline -> {n} seeded"
        else fail s!"device.list offline: got {n}, want {ids.size}"
        -- load the first seeded entity by id
        if ids.size > 0 then do
          let wid := ids[0]!
          let m ← newMap #[("id", Value.str wid)]
          let got ← Device.load tclient m (← emptyMap)
          let gid ← SdkRuntime.gpS got "id"
          if gid == wid then pass s!"device.load offline (id={wid})"
          else fail s!"device.load offline: got {gid}, want {wid}"
)
    -- device_build: offline (test-mode) entity behaviour
    (do
      let seedPath := "../.sdk/test/entity/device_build/DeviceBuildTestData.json"
      if !(← System.FilePath.pathExists seedPath) then
        IO.println s!"skip - device_build: no seed at {seedPath}"
      else do
        let seed ← SdkJson.jsonRead (← IO.FS.readFile seedPath)
        let tclient ← Sdk.testSdk0 seed
        let existing ← SdkRuntime.gp (← SdkRuntime.gp seed "existing") "device_build"
        let ids ← keysof existing
        -- list returns every seeded entity
        let items ← Device_build.list tclient (← emptyMap) (← emptyMap)
        let n ← (match items with | Value.list lid => do pure (← listItems lid).size | _ => pure 0)
        if n == ids.size then pass s!"device_build.list offline -> {n} seeded"
        else fail s!"device_build.list offline: got {n}, want {ids.size}"
        -- load the first seeded entity by id
        if ids.size > 0 then do
          let wid := ids[0]!
          let m ← newMap #[("id", Value.str wid)]
          let got ← Device_build.load tclient m (← emptyMap)
          let gid ← SdkRuntime.gpS got "id"
          if gid == wid then pass s!"device_build.load offline (id={wid})"
          else fail s!"device_build.load offline: got {gid}, want {wid}"
)
    -- device_custody_detail: offline (test-mode) entity behaviour
    (do
      let seedPath := "../.sdk/test/entity/device_custody_detail/DeviceCustodyDetailTestData.json"
      if !(← System.FilePath.pathExists seedPath) then
        IO.println s!"skip - device_custody_detail: no seed at {seedPath}"
      else do
        let seed ← SdkJson.jsonRead (← IO.FS.readFile seedPath)
        let tclient ← Sdk.testSdk0 seed
        let existing ← SdkRuntime.gp (← SdkRuntime.gp seed "existing") "device_custody_detail"
        let ids ← keysof existing
        -- load the first seeded entity by id
        if ids.size > 0 then do
          let wid := ids[0]!
          let m ← newMap #[("id", Value.str wid)]
          let got ← Device_custody_detail.load tclient m (← emptyMap)
          let gid ← SdkRuntime.gpS got "id"
          if gid == wid then pass s!"device_custody_detail.load offline (id={wid})"
          else fail s!"device_custody_detail.load offline: got {gid}, want {wid}"
)
    -- device_custody_list: offline (test-mode) entity behaviour
    (do
      let seedPath := "../.sdk/test/entity/device_custody_list/DeviceCustodyListTestData.json"
      if !(← System.FilePath.pathExists seedPath) then
        IO.println s!"skip - device_custody_list: no seed at {seedPath}"
      else do
        let seed ← SdkJson.jsonRead (← IO.FS.readFile seedPath)
        let tclient ← Sdk.testSdk0 seed
        let existing ← SdkRuntime.gp (← SdkRuntime.gp seed "existing") "device_custody_list"
        let ids ← keysof existing
        -- list returns every seeded entity
        let items ← Device_custody_list.list tclient (← emptyMap) (← emptyMap)
        let n ← (match items with | Value.list lid => do pure (← listItems lid).size | _ => pure 0)
        if n == ids.size then pass s!"device_custody_list.list offline -> {n} seeded"
        else fail s!"device_custody_list.list offline: got {n}, want {ids.size}"
)
    -- device_list: offline (test-mode) entity behaviour
    (do
      let seedPath := "../.sdk/test/entity/device_list/DeviceListTestData.json"
      if !(← System.FilePath.pathExists seedPath) then
        IO.println s!"skip - device_list: no seed at {seedPath}"
      else do
        let seed ← SdkJson.jsonRead (← IO.FS.readFile seedPath)
        let tclient ← Sdk.testSdk0 seed
        let existing ← SdkRuntime.gp (← SdkRuntime.gp seed "existing") "device_list"
        let ids ← keysof existing
        -- load the first seeded entity by id
        if ids.size > 0 then do
          let wid := ids[0]!
          let m ← newMap #[("id", Value.str wid)]
          let got ← Device_list.load tclient m (← emptyMap)
          let gid ← SdkRuntime.gpS got "id"
          if gid == wid then pass s!"device_list.load offline (id={wid})"
          else fail s!"device_list.load offline: got {gid}, want {wid}"
)
    -- device_state: offline (test-mode) entity behaviour
    (do
      let seedPath := "../.sdk/test/entity/device_state/DeviceStateTestData.json"
      if !(← System.FilePath.pathExists seedPath) then
        IO.println s!"skip - device_state: no seed at {seedPath}"
      else do
        let seed ← SdkJson.jsonRead (← IO.FS.readFile seedPath)
        let tclient ← Sdk.testSdk0 seed
        let existing ← SdkRuntime.gp (← SdkRuntime.gp seed "existing") "device_state"
        let ids ← keysof existing
        -- list returns every seeded entity
        let items ← Device_state.list tclient (← emptyMap) (← emptyMap)
        let n ← (match items with | Value.list lid => do pure (← listItems lid).size | _ => pure 0)
        if n == ids.size then pass s!"device_state.list offline -> {n} seeded"
        else fail s!"device_state.list offline: got {n}, want {ids.size}"
)
    -- device_type: offline (test-mode) entity behaviour
    (do
      let seedPath := "../.sdk/test/entity/device_type/DeviceTypeTestData.json"
      if !(← System.FilePath.pathExists seedPath) then
        IO.println s!"skip - device_type: no seed at {seedPath}"
      else do
        let seed ← SdkJson.jsonRead (← IO.FS.readFile seedPath)
        let tclient ← Sdk.testSdk0 seed
        let existing ← SdkRuntime.gp (← SdkRuntime.gp seed "existing") "device_type"
        let ids ← keysof existing
        -- list returns every seeded entity
        let items ← Device_type.list tclient (← emptyMap) (← emptyMap)
        let n ← (match items with | Value.list lid => do pure (← listItems lid).size | _ => pure 0)
        if n == ids.size then pass s!"device_type.list offline -> {n} seeded"
        else fail s!"device_type.list offline: got {n}, want {ids.size}"
        -- load the first seeded entity by id
        if ids.size > 0 then do
          let wid := ids[0]!
          let m ← newMap #[("id", Value.str wid)]
          let got ← Device_type.load tclient m (← emptyMap)
          let gid ← SdkRuntime.gpS got "id"
          if gid == wid then pass s!"device_type.load offline (id={wid})"
          else fail s!"device_type.load offline: got {gid}, want {wid}"
)
    -- inject_key: offline (test-mode) entity behaviour
    (do
      let seedPath := "../.sdk/test/entity/inject_key/InjectKeyTestData.json"
      if !(← System.FilePath.pathExists seedPath) then
        IO.println s!"skip - inject_key: no seed at {seedPath}"
      else do
        let seed ← SdkJson.jsonRead (← IO.FS.readFile seedPath)
        let tclient ← Sdk.testSdk0 seed
        let existing ← SdkRuntime.gp (← SdkRuntime.gp seed "existing") "inject_key"
        let ids ← keysof existing
        -- list returns every seeded entity
        let items ← Inject_key.list tclient (← emptyMap) (← emptyMap)
        let n ← (match items with | Value.list lid => do pure (← listItems lid).size | _ => pure 0)
        if n == ids.size then pass s!"inject_key.list offline -> {n} seeded"
        else fail s!"inject_key.list offline: got {n}, want {ids.size}"
        -- load the first seeded entity by id
        if ids.size > 0 then do
          let wid := ids[0]!
          let m ← newMap #[("id", Value.str wid)]
          let got ← Inject_key.load tclient m (← emptyMap)
          let gid ← SdkRuntime.gpS got "id"
          if gid == wid then pass s!"inject_key.load offline (id={wid})"
          else fail s!"inject_key.load offline: got {gid}, want {wid}"
)
    -- kif: offline (test-mode) entity behaviour
    (do
      let seedPath := "../.sdk/test/entity/kif/KifTestData.json"
      if !(← System.FilePath.pathExists seedPath) then
        IO.println s!"skip - kif: no seed at {seedPath}"
      else do
        let seed ← SdkJson.jsonRead (← IO.FS.readFile seedPath)
        let tclient ← Sdk.testSdk0 seed
        let existing ← SdkRuntime.gp (← SdkRuntime.gp seed "existing") "kif"
        let ids ← keysof existing
        -- list returns every seeded entity
        let items ← Kif.list tclient (← emptyMap) (← emptyMap)
        let n ← (match items with | Value.list lid => do pure (← listItems lid).size | _ => pure 0)
        if n == ids.size then pass s!"kif.list offline -> {n} seeded"
        else fail s!"kif.list offline: got {n}, want {ids.size}"
)
    -- location: offline (test-mode) entity behaviour
    (do
      let seedPath := "../.sdk/test/entity/location/LocationTestData.json"
      if !(← System.FilePath.pathExists seedPath) then
        IO.println s!"skip - location: no seed at {seedPath}"
      else do
        let seed ← SdkJson.jsonRead (← IO.FS.readFile seedPath)
        let tclient ← Sdk.testSdk0 seed
        let existing ← SdkRuntime.gp (← SdkRuntime.gp seed "existing") "location"
        let ids ← keysof existing
        -- list returns every seeded entity
        let items ← Location.list tclient (← emptyMap) (← emptyMap)
        let n ← (match items with | Value.list lid => do pure (← listItems lid).size | _ => pure 0)
        if n == ids.size then pass s!"location.list offline -> {n} seeded"
        else fail s!"location.list offline: got {n}, want {ids.size}"
        -- load the first seeded entity by id
        if ids.size > 0 then do
          let wid := ids[0]!
          let m ← newMap #[("id", Value.str wid)]
          let got ← Location.load tclient m (← emptyMap)
          let gid ← SdkRuntime.gpS got "id"
          if gid == wid then pass s!"location.load offline (id={wid})"
          else fail s!"location.load offline: got {gid}, want {wid}"
        -- create -> load back -> remove, all in the store
        let newmap ← SdkRuntime.gp (← SdkRuntime.gp seed "new") "location"
        let nks ← keysof newmap
        if nks.size > 0 then do
          let payload ← SdkRuntime.gp newmap nks[0]!
          let created ← Location.create tclient payload (← emptyMap)
          let cid ← SdkRuntime.gpS created "id"
          if cid == "" then fail "location.create offline returned no id" else do
            let m2 ← newMap #[("id", Value.str cid)]
            let back ← Location.load tclient m2 (← emptyMap)
            if (← SdkRuntime.gpS back "id") == cid then
              pass s!"location.create/load offline (id={cid})"
            else fail s!"location.create/load offline mismatch"
            let _ ← Location.remove tclient m2 (← emptyMap)
            let gone ← Location.load tclient m2 (← emptyMap)
            match gone with
            | Value.map _ => fail s!"location.remove offline: still present"
            | _ => pass s!"location.remove offline (id={cid})"
)
    -- partner: offline (test-mode) entity behaviour
    (do
      let seedPath := "../.sdk/test/entity/partner/PartnerTestData.json"
      if !(← System.FilePath.pathExists seedPath) then
        IO.println s!"skip - partner: no seed at {seedPath}"
      else do
        let seed ← SdkJson.jsonRead (← IO.FS.readFile seedPath)
        let tclient ← Sdk.testSdk0 seed
        let existing ← SdkRuntime.gp (← SdkRuntime.gp seed "existing") "partner"
        let ids ← keysof existing
        -- list returns every seeded entity
        let items ← Partner.list tclient (← emptyMap) (← emptyMap)
        let n ← (match items with | Value.list lid => do pure (← listItems lid).size | _ => pure 0)
        if n == ids.size then pass s!"partner.list offline -> {n} seeded"
        else fail s!"partner.list offline: got {n}, want {ids.size}"
        -- load the first seeded entity by id
        if ids.size > 0 then do
          let wid := ids[0]!
          let m ← newMap #[("id", Value.str wid)]
          let got ← Partner.load tclient m (← emptyMap)
          let gid ← SdkRuntime.gpS got "id"
          if gid == wid then pass s!"partner.load offline (id={wid})"
          else fail s!"partner.load offline: got {gid}, want {wid}"
)
    -- shipment: offline (test-mode) entity behaviour
    (do
      let seedPath := "../.sdk/test/entity/shipment/ShipmentTestData.json"
      if !(← System.FilePath.pathExists seedPath) then
        IO.println s!"skip - shipment: no seed at {seedPath}"
      else do
        let seed ← SdkJson.jsonRead (← IO.FS.readFile seedPath)
        let tclient ← Sdk.testSdk0 seed
        let existing ← SdkRuntime.gp (← SdkRuntime.gp seed "existing") "shipment"
        let ids ← keysof existing
        -- list returns every seeded entity
        let items ← Shipment.list tclient (← emptyMap) (← emptyMap)
        let n ← (match items with | Value.list lid => do pure (← listItems lid).size | _ => pure 0)
        if n == ids.size then pass s!"shipment.list offline -> {n} seeded"
        else fail s!"shipment.list offline: got {n}, want {ids.size}"
        -- load the first seeded entity by id
        if ids.size > 0 then do
          let wid := ids[0]!
          let m ← newMap #[("id", Value.str wid)]
          let got ← Shipment.load tclient m (← emptyMap)
          let gid ← SdkRuntime.gpS got "id"
          if gid == wid then pass s!"shipment.load offline (id={wid})"
          else fail s!"shipment.load offline: got {gid}, want {wid}"
)
    -- transaction: offline (test-mode) entity behaviour
    (do
      let seedPath := "../.sdk/test/entity/transaction/TransactionTestData.json"
      if !(← System.FilePath.pathExists seedPath) then
        IO.println s!"skip - transaction: no seed at {seedPath}"
      else do
        let seed ← SdkJson.jsonRead (← IO.FS.readFile seedPath)
        let tclient ← Sdk.testSdk0 seed
        let existing ← SdkRuntime.gp (← SdkRuntime.gp seed "existing") "transaction"
        let ids ← keysof existing
        -- list returns every seeded entity
        let items ← Transaction.list tclient (← emptyMap) (← emptyMap)
        let n ← (match items with | Value.list lid => do pure (← listItems lid).size | _ => pure 0)
        if n == ids.size then pass s!"transaction.list offline -> {n} seeded"
        else fail s!"transaction.list offline: got {n}, want {ids.size}"
        -- load the first seeded entity by id
        if ids.size > 0 then do
          let wid := ids[0]!
          let m ← newMap #[("id", Value.str wid)]
          let got ← Transaction.load tclient m (← emptyMap)
          let gid ← SdkRuntime.gpS got "id"
          if gid == wid then pass s!"transaction.load offline (id={wid})"
          else fail s!"transaction.load offline: got {gid}, want {wid}"
)
    -- update_result: offline (test-mode) entity behaviour
    (do
      let seedPath := "../.sdk/test/entity/update_result/UpdateResultTestData.json"
      if !(← System.FilePath.pathExists seedPath) then
        IO.println s!"skip - update_result: no seed at {seedPath}"
      else do
        let seed ← SdkJson.jsonRead (← IO.FS.readFile seedPath)
        let tclient ← Sdk.testSdk0 seed
        let existing ← SdkRuntime.gp (← SdkRuntime.gp seed "existing") "update_result"
        let ids ← keysof existing
        -- list returns every seeded entity
        let items ← Update_result.list tclient (← emptyMap) (← emptyMap)
        let n ← (match items with | Value.list lid => do pure (← listItems lid).size | _ => pure 0)
        if n == ids.size then pass s!"update_result.list offline -> {n} seeded"
        else fail s!"update_result.list offline: got {n}, want {ids.size}"
)
    -- user: offline (test-mode) entity behaviour
    (do
      let seedPath := "../.sdk/test/entity/user/UserTestData.json"
      if !(← System.FilePath.pathExists seedPath) then
        IO.println s!"skip - user: no seed at {seedPath}"
      else do
        let seed ← SdkJson.jsonRead (← IO.FS.readFile seedPath)
        let tclient ← Sdk.testSdk0 seed
        let existing ← SdkRuntime.gp (← SdkRuntime.gp seed "existing") "user"
        let ids ← keysof existing
        -- load the first seeded entity by id
        if ids.size > 0 then do
          let wid := ids[0]!
          let m ← newMap #[("id", Value.str wid)]
          let got ← User.load tclient m (← emptyMap)
          let gid ← SdkRuntime.gpS got "id"
          if gid == wid then pass s!"user.load offline (id={wid})"
          else fail s!"user.load offline: got {gid}, want {wid}"
)
  offline.run ctx
  match liveBase with
  | none => IO.println "skip - live lane (set SDK_TEST_BASE to enable)"
  | some base => do
    let live : SIO Unit := do
      let opts ← newMap #[("base", .str base)]
      let client ← Sdk.newSdk opts
      -- attestation: list smoke
      (do
        let items ← Attestation.list client (← emptyMap) (← emptyMap)
        match items with
        | Value.list lid => pass s!"attestation.list -> {(← listItems lid).size} items"
        | _ => fail "attestation.list did not return a list")
      -- client: list smoke
      (do
        let items ← Client.list client (← emptyMap) (← emptyMap)
        match items with
        | Value.list lid => pass s!"client.list -> {(← listItems lid).size} items"
        | _ => fail "client.list did not return a list")
      -- client: create / load / remove round-trip
      (do
        let d ← SdkJson.jsonRead "{\"location\":\"leantest\"}"
        let created ← Client.create client d (← emptyMap)
        let nid ← SdkRuntime.gpS created "id"
        if nid == "" then fail "client.create returned no id" else do
          let m ← newMap #[("id", .str nid)]
          let back ← Client.load client m (← emptyMap)
          let bid ← SdkRuntime.gpS back "id"
          if bid == nid then pass s!"client.create/load round-trip (id={nid})"
          else fail s!"client.load mismatch: {bid} != {nid}"
          let _ ← Client.remove client m (← emptyMap)
          pass s!"client.remove (id={nid})")
      -- device: list smoke
      (do
        let items ← Device.list client (← emptyMap) (← emptyMap)
        match items with
        | Value.list lid => pass s!"device.list -> {(← listItems lid).size} items"
        | _ => fail "device.list did not return a list")
      -- device_build: list smoke
      (do
        let items ← Device_build.list client (← emptyMap) (← emptyMap)
        match items with
        | Value.list lid => pass s!"device_build.list -> {(← listItems lid).size} items"
        | _ => fail "device_build.list did not return a list")
      -- device_state: list smoke
      (do
        let items ← Device_state.list client (← emptyMap) (← emptyMap)
        match items with
        | Value.list lid => pass s!"device_state.list -> {(← listItems lid).size} items"
        | _ => fail "device_state.list did not return a list")
      -- device_type: list smoke
      (do
        let items ← Device_type.list client (← emptyMap) (← emptyMap)
        match items with
        | Value.list lid => pass s!"device_type.list -> {(← listItems lid).size} items"
        | _ => fail "device_type.list did not return a list")
      -- inject_key: list smoke
      (do
        let items ← Inject_key.list client (← emptyMap) (← emptyMap)
        match items with
        | Value.list lid => pass s!"inject_key.list -> {(← listItems lid).size} items"
        | _ => fail "inject_key.list did not return a list")
      -- kif: list smoke
      (do
        let items ← Kif.list client (← emptyMap) (← emptyMap)
        match items with
        | Value.list lid => pass s!"kif.list -> {(← listItems lid).size} items"
        | _ => fail "kif.list did not return a list")
      -- location: list smoke
      (do
        let items ← Location.list client (← emptyMap) (← emptyMap)
        match items with
        | Value.list lid => pass s!"location.list -> {(← listItems lid).size} items"
        | _ => fail "location.list did not return a list")
      -- location: create / load / remove round-trip
      (do
        let d ← SdkJson.jsonRead "{}"
        let created ← Location.create client d (← emptyMap)
        let nid ← SdkRuntime.gpS created "id"
        if nid == "" then fail "location.create returned no id" else do
          let m ← newMap #[("id", .str nid)]
          let back ← Location.load client m (← emptyMap)
          let bid ← SdkRuntime.gpS back "id"
          if bid == nid then pass s!"location.create/load round-trip (id={nid})"
          else fail s!"location.load mismatch: {bid} != {nid}"
          let _ ← Location.remove client m (← emptyMap)
          pass s!"location.remove (id={nid})")
      -- partner: list smoke
      (do
        let items ← Partner.list client (← emptyMap) (← emptyMap)
        match items with
        | Value.list lid => pass s!"partner.list -> {(← listItems lid).size} items"
        | _ => fail "partner.list did not return a list")
      -- shipment: list smoke
      (do
        let items ← Shipment.list client (← emptyMap) (← emptyMap)
        match items with
        | Value.list lid => pass s!"shipment.list -> {(← listItems lid).size} items"
        | _ => fail "shipment.list did not return a list")
      -- transaction: list smoke
      (do
        let items ← Transaction.list client (← emptyMap) (← emptyMap)
        match items with
        | Value.list lid => pass s!"transaction.list -> {(← listItems lid).size} items"
        | _ => fail "transaction.list did not return a list")
      -- update_result: list smoke
      (do
        let items ← Update_result.list client (← emptyMap) (← emptyMap)
        match items with
        | Value.list lid => pass s!"update_result.list -> {(← listItems lid).size} items"
        | _ => fail "update_result.list did not return a list")
    live.run ctx
  let p ← npass.get
  let f ← nfail.get
  IO.println ""
  IO.println s!"PASS {p}  FAIL {f}"
  if f > 0 then return 1 else return 0
