;; BluefinDecryptxP2pe SDK public API (generated by @voxgig/sdkgen).
(ns sdk.api
  (:require [sdk.client :as client]
            [sdk.entity.attestation :as e-attestation]
            [sdk.entity.client :as e-client]
            [sdk.entity.create_result :as e-create_result]
            [sdk.entity.decryption :as e-decryption]
            [sdk.entity.device :as e-device]
            [sdk.entity.device_build :as e-device_build]
            [sdk.entity.device_custody_detail :as e-device_custody_detail]
            [sdk.entity.device_custody_list :as e-device_custody_list]
            [sdk.entity.device_list :as e-device_list]
            [sdk.entity.device_receive_result :as e-device_receive_result]
            [sdk.entity.device_rki_activate_result :as e-device_rki_activate_result]
            [sdk.entity.device_state :as e-device_state]
            [sdk.entity.device_type :as e-device_type]
            [sdk.entity.inject_key :as e-inject_key]
            [sdk.entity.kif :as e-kif]
            [sdk.entity.location :as e-location]
            [sdk.entity.partner :as e-partner]
            [sdk.entity.shipment :as e-shipment]
            [sdk.entity.success :as e-success]
            [sdk.entity.transaction :as e-transaction]
            [sdk.entity.update_result :as e-update_result]
            [sdk.entity.user :as e-user]))

(def make-sdk client/make-sdk)
(def test-sdk client/test-sdk)
(def direct client/direct)
(def graphql client/graphql)
(def prepare client/prepare)
(def options-map client/options-map)

;; Attestation accessor: (attestation client data)
(defn attestation [client data] (e-attestation/make client data))

;; Client accessor: (client client data)
(defn client [client data] (e-client/make client data))

;; CreateResult accessor: (create_result client data)
(defn create_result [client data] (e-create_result/make client data))

;; Decryption accessor: (decryption client data)
(defn decryption [client data] (e-decryption/make client data))

;; Device accessor: (device client data)
(defn device [client data] (e-device/make client data))

;; DeviceBuild accessor: (device_build client data)
(defn device_build [client data] (e-device_build/make client data))

;; DeviceCustodyDetail accessor: (device_custody_detail client data)
(defn device_custody_detail [client data] (e-device_custody_detail/make client data))

;; DeviceCustodyList accessor: (device_custody_list client data)
(defn device_custody_list [client data] (e-device_custody_list/make client data))

;; DeviceList accessor: (device_list client data)
(defn device_list [client data] (e-device_list/make client data))

;; DeviceReceiveResult accessor: (device_receive_result client data)
(defn device_receive_result [client data] (e-device_receive_result/make client data))

;; DeviceRkiActivateResult accessor: (device_rki_activate_result client data)
(defn device_rki_activate_result [client data] (e-device_rki_activate_result/make client data))

;; DeviceState accessor: (device_state client data)
(defn device_state [client data] (e-device_state/make client data))

;; DeviceType accessor: (device_type client data)
(defn device_type [client data] (e-device_type/make client data))

;; InjectKey accessor: (inject_key client data)
(defn inject_key [client data] (e-inject_key/make client data))

;; Kif accessor: (kif client data)
(defn kif [client data] (e-kif/make client data))

;; Location accessor: (location client data)
(defn location [client data] (e-location/make client data))

;; Partner accessor: (partner client data)
(defn partner [client data] (e-partner/make client data))

;; Shipment accessor: (shipment client data)
(defn shipment [client data] (e-shipment/make client data))

;; Success accessor: (success client data)
(defn success [client data] (e-success/make client data))

;; Transaction accessor: (transaction client data)
(defn transaction [client data] (e-transaction/make client data))

;; UpdateResult accessor: (update_result client data)
(defn update_result [client data] (e-update_result/make client data))

;; User accessor: (user client data)
(defn user [client data] (e-user/make client data))
