;; BluefinDecryptxP2pe SDK configuration (generated by @voxgig/sdkgen).
(ns sdk.config
  (:require [voxgig.struct :as vs]))

(defn make-config []
  (vs/jm
    "entity" (vs/jm
      "attestation" (vs/jm
        "fields" (vs/jt
          (vs/jm
            "name" "client"
            "type" "`$OBJECT`")
          (vs/jm
            "name" "completeDate"
            "type" "`$STRING`")
          (vs/jm
            "name" "created"
            "type" "`$STRING`")
          (vs/jm
            "name" "device"
            "type" "`$OBJECT`")
          (vs/jm
            "name" "id"
            "type" "`$STRING`")
          (vs/jm
            "name" "name"
            "type" "`$STRING`")
          (vs/jm
            "name" "notes"
            "type" "`$STRING`"))
        "name" "attestation"
        "op" (vs/jm
          "create" (vs/jm
            "input" "data"
            "name" "create"
            "points" (vs/jt
              (vs/jm
                "args" (vs/jm)
                "kind" "http"
                "method" "POST"
                "orig" "/attestations"
                "parts" (vs/jt
                  "attestations")
                "select" (vs/jm)
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`"))))
          "list" (vs/jm
            "input" "data"
            "name" "list"
            "points" (vs/jt
              (vs/jm
                "args" (vs/jm
                  "query" (vs/jt
                    (vs/jm
                      "kind" "query"
                      "name" "client"
                      "orig" "client"
                      "reqd" true
                      "type" "`$STRING`")
                    (vs/jm
                      "example" 0
                      "kind" "query"
                      "name" "skip"
                      "orig" "skip"
                      "type" "`$INTEGER`")
                    (vs/jm
                      "example" 10
                      "kind" "query"
                      "name" "take"
                      "orig" "take"
                      "type" "`$INTEGER`")))
                "kind" "http"
                "method" "GET"
                "orig" "/attestations"
                "parts" (vs/jt
                  "attestations")
                "select" (vs/jm
                  "exist" (vs/jt
                    "client"
                    "skip"
                    "take"))
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`"))))
          "load" (vs/jm
            "input" "data"
            "name" "load"
            "points" (vs/jt
              (vs/jm
                "args" (vs/jm
                  "params" (vs/jt
                    (vs/jm
                      "kind" "param"
                      "name" "id"
                      "orig" "id"
                      "reqd" true
                      "type" "`$STRING`")))
                "kind" "http"
                "method" "GET"
                "orig" "/attestations/{id}"
                "parts" (vs/jt
                  "attestations"
                  "{id}")
                "select" (vs/jm
                  "exist" (vs/jt
                    "id"))
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`")))))
        "relations" (vs/jm
          "ancestors" (vs/jt)))
      "client" (vs/jm
        "fields" (vs/jt
          (vs/jm
            "name" "contact"
            "op" (vs/jm
              "list" (vs/jm
                "req" true
                "type" "`$OBJECT`"))
            "type" "`$OBJECT`")
          (vs/jm
            "name" "created"
            "type" "`$STRING`")
          (vs/jm
            "name" "directPartner"
            "type" "`$OBJECT`")
          (vs/jm
            "name" "id"
            "type" "`$STRING`")
          (vs/jm
            "name" "isActive"
            "type" "`$BOOLEAN`")
          (vs/jm
            "name" "location"
            "req" true
            "type" "`$OBJECT`")
          (vs/jm
            "name" "mid"
            "type" "`$STRING`")
          (vs/jm
            "name" "modified"
            "type" "`$STRING`")
          (vs/jm
            "name" "name"
            "type" "`$STRING`")
          (vs/jm
            "name" "partner"
            "type" "`$OBJECT`")
          (vs/jm
            "name" "version"
            "type" "`$INTEGER`"))
        "name" "client"
        "op" (vs/jm
          "create" (vs/jm
            "input" "data"
            "name" "create"
            "points" (vs/jt
              (vs/jm
                "args" (vs/jm)
                "kind" "http"
                "method" "POST"
                "orig" "/clients"
                "parts" (vs/jt
                  "clients")
                "select" (vs/jm)
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`"))))
          "list" (vs/jm
            "input" "data"
            "name" "list"
            "points" (vs/jt
              (vs/jm
                "args" (vs/jm
                  "query" (vs/jt
                    (vs/jm
                      "kind" "query"
                      "name" "partner"
                      "orig" "partner"
                      "reqd" true
                      "type" "`$STRING`")
                    (vs/jm
                      "example" 0
                      "kind" "query"
                      "name" "skip"
                      "orig" "skip"
                      "type" "`$INTEGER`")
                    (vs/jm
                      "example" 10
                      "kind" "query"
                      "name" "take"
                      "orig" "take"
                      "type" "`$INTEGER`")))
                "kind" "http"
                "method" "GET"
                "orig" "/clients"
                "parts" (vs/jt
                  "clients")
                "select" (vs/jm
                  "exist" (vs/jt
                    "partner"
                    "skip"
                    "take"))
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`"))))
          "load" (vs/jm
            "input" "data"
            "name" "load"
            "points" (vs/jt
              (vs/jm
                "args" (vs/jm
                  "params" (vs/jt
                    (vs/jm
                      "kind" "param"
                      "name" "id"
                      "orig" "id"
                      "reqd" true
                      "type" "`$STRING`")))
                "kind" "http"
                "method" "GET"
                "orig" "/clients/{id}"
                "parts" (vs/jt
                  "clients"
                  "{id}")
                "select" (vs/jm
                  "exist" (vs/jt
                    "id"))
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`"))))
          "remove" (vs/jm
            "input" "data"
            "name" "remove"
            "points" (vs/jt
              (vs/jm
                "args" (vs/jm
                  "params" (vs/jt
                    (vs/jm
                      "kind" "param"
                      "name" "id"
                      "orig" "id"
                      "reqd" true
                      "type" "`$STRING`")))
                "kind" "http"
                "method" "DELETE"
                "orig" "/clients/{id}"
                "parts" (vs/jt
                  "clients"
                  "{id}")
                "select" (vs/jm
                  "exist" (vs/jt
                    "id"))
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`")))))
        "relations" (vs/jm
          "ancestors" (vs/jt)))
      "create_result" (vs/jm
        "fields" (vs/jt)
        "name" "create_result"
        "op" (vs/jm
          "create" (vs/jm
            "input" "data"
            "name" "create"
            "points" (vs/jt
              (vs/jm
                "args" (vs/jm
                  "params" (vs/jt
                    (vs/jm
                      "kind" "param"
                      "name" "device_type"
                      "orig" "device_type"
                      "reqd" true
                      "type" "`$STRING`")
                    (vs/jm
                      "kind" "param"
                      "name" "serial_number"
                      "orig" "serial_number"
                      "reqd" true
                      "type" "`$STRING`")))
                "kind" "http"
                "method" "POST"
                "orig" "/devices/{serialNumber}/{deviceType}/custody"
                "parts" (vs/jt
                  "devices"
                  "{serial_number}"
                  "{device_type}"
                  "custody")
                "rename" (vs/jm
                  "param" (vs/jm
                    "deviceType" "device_type"
                    "serialNumber" "serial_number"))
                "select" (vs/jm
                  "exist" (vs/jt
                    "device_type"
                    "serial_number"))
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`")))))
        "relations" (vs/jm
          "ancestors" (vs/jt
            (vs/jt
              "device"))))
      "decryption" (vs/jm
        "fields" (vs/jt
          (vs/jm
            "name" "success"
            "type" "`$BOOLEAN`"))
        "name" "decryption"
        "op" (vs/jm
          "create" (vs/jm
            "input" "data"
            "name" "create"
            "points" (vs/jt
              (vs/jm
                "args" (vs/jm)
                "kind" "http"
                "method" "POST"
                "orig" "/decryption"
                "parts" (vs/jt
                  "decryption")
                "select" (vs/jm)
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`")))))
        "relations" (vs/jm
          "ancestors" (vs/jt)))
      "device" (vs/jm
        "fields" (vs/jt
          (vs/jm
            "name" "activatedBy"
            "req" true
            "type" "`$OBJECT`")
          (vs/jm
            "name" "activationDate"
            "type" "`$STRING`")
          (vs/jm
            "name" "alternateKey"
            "type" "`$STRING`")
          (vs/jm
            "name" "auditNextDate"
            "type" "`$STRING`")
          (vs/jm
            "name" "auditNotificationDate"
            "type" "`$STRING`")
          (vs/jm
            "name" "client"
            "type" "`$OBJECT`")
          (vs/jm
            "name" "created"
            "type" "`$STRING`")
          (vs/jm
            "name" "createdBy"
            "req" true
            "type" "`$OBJECT`")
          (vs/jm
            "name" "deviceBuild"
            "type" "`$OBJECT`")
          (vs/jm
            "name" "deviceState"
            "type" "`$OBJECT`")
          (vs/jm
            "name" "deviceType"
            "type" "`$OBJECT`")
          (vs/jm
            "name" "errorCounter"
            "type" "`$INTEGER`")
          (vs/jm
            "name" "errorLastDate"
            "type" "`$STRING`")
          (vs/jm
            "name" "id"
            "type" "`$STRING`")
          (vs/jm
            "name" "initializedBy"
            "req" true
            "type" "`$OBJECT`")
          (vs/jm
            "name" "initializedDate"
            "type" "`$STRING`")
          (vs/jm
            "name" "injectKey"
            "type" "`$OBJECT`")
          (vs/jm
            "name" "isVirtual"
            "type" "`$BOOLEAN`")
          (vs/jm
            "name" "kif"
            "type" "`$OBJECT`")
          (vs/jm
            "name" "lastActivityDate"
            "type" "`$STRING`")
          (vs/jm
            "name" "location"
            "req" true
            "type" "`$OBJECT`")
          (vs/jm
            "name" "modified"
            "type" "`$STRING`")
          (vs/jm
            "name" "modifiedBy"
            "req" true
            "type" "`$OBJECT`")
          (vs/jm
            "name" "name"
            "type" "`$STRING`")
          (vs/jm
            "name" "notes"
            "type" "`$STRING`")
          (vs/jm
            "name" "partner"
            "type" "`$OBJECT`")
          (vs/jm
            "name" "serialNumber"
            "type" "`$STRING`")
          (vs/jm
            "name" "version"
            "type" "`$INTEGER`"))
        "name" "device"
        "op" (vs/jm
          "create" (vs/jm
            "input" "data"
            "name" "create"
            "points" (vs/jt
              (vs/jm
                "args" (vs/jm)
                "kind" "http"
                "method" "POST"
                "orig" "/devices"
                "parts" (vs/jt
                  "devices")
                "select" (vs/jm)
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`"))))
          "list" (vs/jm
            "input" "data"
            "name" "list"
            "points" (vs/jt
              (vs/jm
                "args" (vs/jm
                  "query" (vs/jt
                    (vs/jm
                      "kind" "query"
                      "name" "client"
                      "orig" "client"
                      "type" "`$STRING`")
                    (vs/jm
                      "kind" "query"
                      "name" "device_state"
                      "orig" "device_state"
                      "type" "`$STRING`")
                    (vs/jm
                      "kind" "query"
                      "name" "kif"
                      "orig" "kif"
                      "type" "`$STRING`")
                    (vs/jm
                      "kind" "query"
                      "name" "partner"
                      "orig" "partner"
                      "type" "`$STRING`")
                    (vs/jm
                      "kind" "query"
                      "name" "serial_number"
                      "orig" "serial_number"
                      "type" "`$STRING`")
                    (vs/jm
                      "example" 0
                      "kind" "query"
                      "name" "skip"
                      "orig" "skip"
                      "type" "`$INTEGER`")
                    (vs/jm
                      "example" "asc"
                      "kind" "query"
                      "name" "sorting_direction"
                      "orig" "sorting_direction"
                      "type" "`$STRING`")
                    (vs/jm
                      "example" "serialnumber"
                      "kind" "query"
                      "name" "sorting_field"
                      "orig" "sorting_field"
                      "type" "`$STRING`")
                    (vs/jm
                      "example" 10
                      "kind" "query"
                      "name" "take"
                      "orig" "take"
                      "type" "`$INTEGER`")))
                "kind" "http"
                "method" "GET"
                "orig" "/devices"
                "parts" (vs/jt
                  "devices")
                "select" (vs/jm
                  "exist" (vs/jt
                    "client"
                    "device_state"
                    "kif"
                    "partner"
                    "serial_number"
                    "skip"
                    "sorting_direction"
                    "sorting_field"
                    "take"))
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`"))))
          "load" (vs/jm
            "input" "data"
            "name" "load"
            "points" (vs/jt
              (vs/jm
                "args" (vs/jm
                  "params" (vs/jt
                    (vs/jm
                      "kind" "param"
                      "name" "device_type"
                      "orig" "device_type"
                      "reqd" true
                      "type" "`$STRING`")
                    (vs/jm
                      "kind" "param"
                      "name" "serial_number"
                      "orig" "serial_number"
                      "reqd" true
                      "type" "`$STRING`")))
                "kind" "http"
                "method" "GET"
                "orig" "/devices/{serialNumber}/{deviceType}"
                "parts" (vs/jt
                  "devices"
                  "{serial_number}"
                  "{device_type}")
                "rename" (vs/jm
                  "param" (vs/jm
                    "deviceType" "device_type"
                    "serialNumber" "serial_number"))
                "select" (vs/jm
                  "exist" (vs/jt
                    "device_type"
                    "serial_number"))
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`"))
              (vs/jm
                "args" (vs/jm
                  "params" (vs/jt
                    (vs/jm
                      "kind" "param"
                      "name" "id"
                      "orig" "id"
                      "reqd" true
                      "type" "`$STRING`")))
                "kind" "http"
                "method" "GET"
                "orig" "/devices/{id}"
                "parts" (vs/jt
                  "devices"
                  "{id}")
                "select" (vs/jm
                  "exist" (vs/jt
                    "id"))
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`")))))
        "relations" (vs/jm
          "ancestors" (vs/jt
            (vs/jt
              "device"))))
      "device_build" (vs/jm
        "fields" (vs/jt
          (vs/jm
            "name" "appVersion"
            "type" "`$STRING`")
          (vs/jm
            "name" "buildNumber"
            "type" "`$STRING`")
          (vs/jm
            "name" "configFileName"
            "type" "`$STRING`")
          (vs/jm
            "name" "created"
            "type" "`$STRING`")
          (vs/jm
            "name" "deviceType"
            "type" "`$STRING`")
          (vs/jm
            "name" "firmwareVersion"
            "type" "`$STRING`")
          (vs/jm
            "name" "hardwareVersion"
            "type" "`$STRING`")
          (vs/jm
            "name" "id"
            "type" "`$INTEGER`")
          (vs/jm
            "name" "isActive"
            "type" "`$BOOLEAN`")
          (vs/jm
            "name" "modified"
            "type" "`$STRING`")
          (vs/jm
            "name" "name"
            "type" "`$STRING`")
          (vs/jm
            "name" "notes"
            "type" "`$STRING`")
          (vs/jm
            "name" "version"
            "type" "`$INTEGER`")
          (vs/jm
            "name" "whiteListingBinRanges"
            "type" "`$STRING`")
          (vs/jm
            "name" "whiteListingUsed"
            "type" "`$BOOLEAN`"))
        "name" "device_build"
        "op" (vs/jm
          "list" (vs/jm
            "input" "data"
            "name" "list"
            "points" (vs/jt
              (vs/jm
                "args" (vs/jm
                  "query" (vs/jt
                    (vs/jm
                      "kind" "query"
                      "name" "device_type"
                      "orig" "device_type"
                      "type" "`$STRING`")
                    (vs/jm
                      "example" 0
                      "kind" "query"
                      "name" "skip"
                      "orig" "skip"
                      "type" "`$INTEGER`")
                    (vs/jm
                      "example" 10
                      "kind" "query"
                      "name" "take"
                      "orig" "take"
                      "type" "`$INTEGER`")))
                "kind" "http"
                "method" "GET"
                "orig" "/deviceBuilds"
                "parts" (vs/jt
                  "deviceBuilds")
                "select" (vs/jm
                  "exist" (vs/jt
                    "device_type"
                    "skip"
                    "take"))
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`"))))
          "load" (vs/jm
            "input" "data"
            "name" "load"
            "points" (vs/jt
              (vs/jm
                "args" (vs/jm
                  "params" (vs/jt
                    (vs/jm
                      "kind" "param"
                      "name" "id"
                      "orig" "id"
                      "reqd" true
                      "type" "`$STRING`")))
                "kind" "http"
                "method" "GET"
                "orig" "/deviceBuilds/{id}"
                "parts" (vs/jt
                  "deviceBuilds"
                  "{id}")
                "select" (vs/jm
                  "exist" (vs/jt
                    "id"))
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`")))))
        "relations" (vs/jm
          "ancestors" (vs/jt)))
      "device_custody_detail" (vs/jm
        "fields" (vs/jt
          (vs/jm
            "name" "completeDate"
            "type" "`$STRING`")
          (vs/jm
            "name" "created"
            "type" "`$STRING`")
          (vs/jm
            "name" "createdBy"
            "req" true
            "type" "`$OBJECT`")
          (vs/jm
            "name" "custodian"
            "req" true
            "type" "`$OBJECT`")
          (vs/jm
            "name" "device"
            "type" "`$OBJECT`")
          (vs/jm
            "name" "id"
            "type" "`$INTEGER`")
          (vs/jm
            "name" "location"
            "req" true
            "type" "`$OBJECT`")
          (vs/jm
            "name" "modified"
            "type" "`$STRING`")
          (vs/jm
            "name" "modifiedBy"
            "req" true
            "type" "`$OBJECT`")
          (vs/jm
            "name" "notes"
            "type" "`$STRING`")
          (vs/jm
            "name" "status"
            "type" "`$OBJECT`")
          (vs/jm
            "name" "transferMethod"
            "type" "`$OBJECT`")
          (vs/jm
            "name" "version"
            "type" "`$INTEGER`"))
        "name" "device_custody_detail"
        "op" (vs/jm
          "load" (vs/jm
            "input" "data"
            "name" "load"
            "points" (vs/jt
              (vs/jm
                "args" (vs/jm
                  "params" (vs/jt
                    (vs/jm
                      "kind" "param"
                      "name" "device_type"
                      "orig" "device_type"
                      "reqd" true
                      "type" "`$STRING`")
                    (vs/jm
                      "kind" "param"
                      "name" "id"
                      "orig" "id"
                      "reqd" true
                      "type" "`$STRING`")
                    (vs/jm
                      "kind" "param"
                      "name" "serial_number"
                      "orig" "serial_number"
                      "reqd" true
                      "type" "`$STRING`")))
                "kind" "http"
                "method" "GET"
                "orig" "/devices/{serialNumber}/{deviceType}/custody/{id}"
                "parts" (vs/jt
                  "devices"
                  "{serial_number}"
                  "{device_type}"
                  "custody"
                  "{id}")
                "rename" (vs/jm
                  "param" (vs/jm
                    "deviceType" "device_type"
                    "serialNumber" "serial_number"))
                "select" (vs/jm
                  "exist" (vs/jt
                    "device_type"
                    "id"
                    "serial_number"))
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`")))))
        "relations" (vs/jm
          "ancestors" (vs/jt
            (vs/jt
              "device"))))
      "device_custody_list" (vs/jm
        "fields" (vs/jt
          (vs/jm
            "name" "completeDate"
            "type" "`$STRING`")
          (vs/jm
            "name" "created"
            "type" "`$STRING`")
          (vs/jm
            "name" "createdBy"
            "req" true
            "type" "`$OBJECT`")
          (vs/jm
            "name" "custodian"
            "req" true
            "type" "`$OBJECT`")
          (vs/jm
            "name" "device"
            "type" "`$OBJECT`")
          (vs/jm
            "name" "id"
            "type" "`$INTEGER`")
          (vs/jm
            "name" "location"
            "req" true
            "type" "`$OBJECT`")
          (vs/jm
            "name" "modified"
            "type" "`$STRING`")
          (vs/jm
            "name" "modifiedBy"
            "req" true
            "type" "`$OBJECT`")
          (vs/jm
            "name" "notes"
            "type" "`$STRING`")
          (vs/jm
            "name" "status"
            "type" "`$OBJECT`")
          (vs/jm
            "name" "transferMethod"
            "type" "`$OBJECT`")
          (vs/jm
            "name" "version"
            "type" "`$INTEGER`"))
        "name" "device_custody_list"
        "op" (vs/jm
          "list" (vs/jm
            "input" "data"
            "name" "list"
            "points" (vs/jt
              (vs/jm
                "args" (vs/jm
                  "params" (vs/jt
                    (vs/jm
                      "kind" "param"
                      "name" "device_type"
                      "orig" "device_type"
                      "reqd" true
                      "type" "`$STRING`")
                    (vs/jm
                      "kind" "param"
                      "name" "serial_number"
                      "orig" "serial_number"
                      "reqd" true
                      "type" "`$STRING`"))
                  "query" (vs/jt
                    (vs/jm
                      "example" 0
                      "kind" "query"
                      "name" "skip"
                      "orig" "skip"
                      "type" "`$INTEGER`")
                    (vs/jm
                      "example" 10
                      "kind" "query"
                      "name" "take"
                      "orig" "take"
                      "type" "`$INTEGER`")))
                "kind" "http"
                "method" "GET"
                "orig" "/devices/{serialNumber}/{deviceType}/custody"
                "parts" (vs/jt
                  "devices"
                  "{serial_number}"
                  "{device_type}"
                  "custody")
                "rename" (vs/jm
                  "param" (vs/jm
                    "deviceType" "device_type"
                    "serialNumber" "serial_number"))
                "select" (vs/jm
                  "exist" (vs/jt
                    "device_type"
                    "serial_number"
                    "skip"
                    "take"))
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`")))))
        "relations" (vs/jm
          "ancestors" (vs/jt
            (vs/jt
              "device"))))
      "device_list" (vs/jm
        "fields" (vs/jt
          (vs/jm
            "name" "data"
            "type" "`$ARRAY`")
          (vs/jm
            "name" "total"
            "type" "`$INTEGER`"))
        "name" "device_list"
        "op" (vs/jm
          "load" (vs/jm
            "input" "data"
            "name" "load"
            "points" (vs/jt
              (vs/jm
                "args" (vs/jm
                  "params" (vs/jt
                    (vs/jm
                      "kind" "param"
                      "name" "share_partner_to"
                      "orig" "share_partner_to"
                      "reqd" true
                      "type" "`$STRING`"))
                  "query" (vs/jt
                    (vs/jm
                      "example" 0
                      "kind" "query"
                      "name" "skip"
                      "orig" "skip"
                      "type" "`$INTEGER`")
                    (vs/jm
                      "example" "asc"
                      "kind" "query"
                      "name" "sorting_direction"
                      "orig" "sorting_direction"
                      "type" "`$STRING`")
                    (vs/jm
                      "example" "serialnumber"
                      "kind" "query"
                      "name" "sorting_field"
                      "orig" "sorting_field"
                      "type" "`$STRING`")
                    (vs/jm
                      "example" 10
                      "kind" "query"
                      "name" "take"
                      "orig" "take"
                      "type" "`$INTEGER`")))
                "kind" "http"
                "method" "GET"
                "orig" "/virtualDevices/{sharePartnerTo}"
                "parts" (vs/jt
                  "virtualDevices"
                  "{share_partner_to}")
                "rename" (vs/jm
                  "param" (vs/jm
                    "sharePartnerTo" "share_partner_to"))
                "select" (vs/jm
                  "exist" (vs/jt
                    "share_partner_to"
                    "skip"
                    "sorting_direction"
                    "sorting_field"
                    "take"))
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`")))))
        "relations" (vs/jm
          "ancestors" (vs/jt
            (vs/jt
              "virtual_device"))))
      "device_receive_result" (vs/jm
        "fields" (vs/jt
          (vs/jm
            "name" "success"
            "req" true
            "type" "`$BOOLEAN`"))
        "name" "device_receive_result"
        "op" (vs/jm
          "create" (vs/jm
            "input" "data"
            "name" "create"
            "points" (vs/jt
              (vs/jm
                "args" (vs/jm)
                "kind" "http"
                "method" "POST"
                "orig" "/devices/receive"
                "parts" (vs/jt
                  "devices"
                  "receive")
                "select" (vs/jm)
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`")))))
        "relations" (vs/jm
          "ancestors" (vs/jt)))
      "device_rki_activate_result" (vs/jm
        "fields" (vs/jt
          (vs/jm
            "name" "success"
            "req" true
            "type" "`$BOOLEAN`"))
        "name" "device_rki_activate_result"
        "op" (vs/jm
          "create" (vs/jm
            "input" "data"
            "name" "create"
            "points" (vs/jt
              (vs/jm
                "args" (vs/jm)
                "kind" "http"
                "method" "POST"
                "orig" "/devices/rki/activate"
                "parts" (vs/jt
                  "devices"
                  "rki"
                  "activate")
                "select" (vs/jm)
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`")))))
        "relations" (vs/jm
          "ancestors" (vs/jt)))
      "device_state" (vs/jm
        "fields" (vs/jt
          (vs/jm
            "name" "id"
            "type" "`$INTEGER`")
          (vs/jm
            "name" "name"
            "type" "`$STRING`"))
        "name" "device_state"
        "op" (vs/jm
          "list" (vs/jm
            "input" "data"
            "name" "list"
            "points" (vs/jt
              (vs/jm
                "args" (vs/jm)
                "kind" "http"
                "method" "GET"
                "orig" "/deviceStates"
                "parts" (vs/jt
                  "deviceStates")
                "select" (vs/jm)
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`")))))
        "relations" (vs/jm
          "ancestors" (vs/jt)))
      "device_type" (vs/jm
        "fields" (vs/jt
          (vs/jm
            "name" "created"
            "type" "`$STRING`")
          (vs/jm
            "name" "deviceTypeMode"
            "type" "`$STRING`")
          (vs/jm
            "name" "hardwareVersion"
            "type" "`$STRING`")
          (vs/jm
            "name" "id"
            "type" "`$STRING`")
          (vs/jm
            "name" "isActive"
            "type" "`$BOOLEAN`")
          (vs/jm
            "name" "manufacturer"
            "type" "`$STRING`")
          (vs/jm
            "name" "model"
            "type" "`$STRING`")
          (vs/jm
            "name" "modified"
            "type" "`$STRING`")
          (vs/jm
            "name" "name"
            "type" "`$STRING`")
          (vs/jm
            "name" "photoUrl"
            "type" "`$STRING`")
          (vs/jm
            "name" "productName"
            "type" "`$STRING`")
          (vs/jm
            "name" "version"
            "type" "`$INTEGER`"))
        "name" "device_type"
        "op" (vs/jm
          "list" (vs/jm
            "input" "data"
            "name" "list"
            "points" (vs/jt
              (vs/jm
                "args" (vs/jm)
                "kind" "http"
                "method" "GET"
                "orig" "/deviceTypes"
                "parts" (vs/jt
                  "deviceTypes")
                "select" (vs/jm)
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`"))))
          "load" (vs/jm
            "input" "data"
            "name" "load"
            "points" (vs/jt
              (vs/jm
                "args" (vs/jm
                  "params" (vs/jt
                    (vs/jm
                      "kind" "param"
                      "name" "id"
                      "orig" "id"
                      "reqd" true
                      "type" "`$STRING`")))
                "kind" "http"
                "method" "GET"
                "orig" "/deviceTypes/{id}"
                "parts" (vs/jt
                  "deviceTypes"
                  "{id}")
                "select" (vs/jm
                  "exist" (vs/jt
                    "id"))
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`")))))
        "relations" (vs/jm
          "ancestors" (vs/jt)))
      "inject_key" (vs/jm
        "fields" (vs/jt
          (vs/jm
            "name" "created"
            "type" "`$STRING`")
          (vs/jm
            "name" "id"
            "type" "`$STRING`")
          (vs/jm
            "name" "isActive"
            "type" "`$BOOLEAN`")
          (vs/jm
            "name" "isP2PE"
            "type" "`$BOOLEAN`")
          (vs/jm
            "name" "keyType"
            "type" "`$STRING`")
          (vs/jm
            "name" "modified"
            "type" "`$STRING`")
          (vs/jm
            "name" "name"
            "type" "`$STRING`")
          (vs/jm
            "name" "version"
            "type" "`$INTEGER`"))
        "name" "inject_key"
        "op" (vs/jm
          "list" (vs/jm
            "input" "data"
            "name" "list"
            "points" (vs/jt
              (vs/jm
                "args" (vs/jm)
                "kind" "http"
                "method" "GET"
                "orig" "/injectKeys"
                "parts" (vs/jt
                  "injectKeys")
                "select" (vs/jm)
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`"))))
          "load" (vs/jm
            "input" "data"
            "name" "load"
            "points" (vs/jt
              (vs/jm
                "args" (vs/jm
                  "params" (vs/jt
                    (vs/jm
                      "kind" "param"
                      "name" "id"
                      "orig" "id"
                      "reqd" true
                      "type" "`$STRING`")))
                "kind" "http"
                "method" "GET"
                "orig" "/injectKeys/{id}"
                "parts" (vs/jt
                  "injectKeys"
                  "{id}")
                "select" (vs/jm
                  "exist" (vs/jt
                    "id"))
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`")))))
        "relations" (vs/jm
          "ancestors" (vs/jt)))
      "kif" (vs/jm
        "fields" (vs/jt
          (vs/jm
            "name" "id"
            "type" "`$INTEGER`")
          (vs/jm
            "name" "name"
            "type" "`$STRING`"))
        "name" "kif"
        "op" (vs/jm
          "list" (vs/jm
            "input" "data"
            "name" "list"
            "points" (vs/jt
              (vs/jm
                "args" (vs/jm)
                "kind" "http"
                "method" "GET"
                "orig" "/kifs"
                "parts" (vs/jt
                  "kifs")
                "select" (vs/jm)
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`")))))
        "relations" (vs/jm
          "ancestors" (vs/jt)))
      "location" (vs/jm
        "fields" (vs/jt
          (vs/jm
            "name" "address1"
            "type" "`$STRING`")
          (vs/jm
            "name" "address2"
            "type" "`$STRING`")
          (vs/jm
            "name" "billingId"
            "type" "`$STRING`")
          (vs/jm
            "name" "city"
            "type" "`$STRING`")
          (vs/jm
            "name" "country"
            "type" "`$STRING`")
          (vs/jm
            "name" "created"
            "type" "`$STRING`")
          (vs/jm
            "name" "customReference"
            "type" "`$STRING`")
          (vs/jm
            "name" "id"
            "type" "`$STRING`")
          (vs/jm
            "name" "locationType"
            "type" "`$STRING`")
          (vs/jm
            "name" "mailAddress1"
            "type" "`$STRING`")
          (vs/jm
            "name" "mailAddress2"
            "type" "`$STRING`")
          (vs/jm
            "name" "mailCity"
            "type" "`$STRING`")
          (vs/jm
            "name" "mailCountry"
            "type" "`$STRING`")
          (vs/jm
            "name" "mailPostalCode"
            "type" "`$STRING`")
          (vs/jm
            "name" "mailStateProvince"
            "type" "`$STRING`")
          (vs/jm
            "name" "modified"
            "type" "`$STRING`")
          (vs/jm
            "name" "name"
            "type" "`$STRING`")
          (vs/jm
            "name" "nameOfBusiness"
            "type" "`$STRING`")
          (vs/jm
            "name" "notes"
            "type" "`$STRING`")
          (vs/jm
            "name" "postalCode"
            "type" "`$STRING`")
          (vs/jm
            "name" "stateProvince"
            "type" "`$STRING`")
          (vs/jm
            "name" "uniqueId"
            "type" "`$STRING`")
          (vs/jm
            "name" "version"
            "type" "`$INTEGER`"))
        "name" "location"
        "op" (vs/jm
          "create" (vs/jm
            "input" "data"
            "name" "create"
            "points" (vs/jt
              (vs/jm
                "args" (vs/jm)
                "kind" "http"
                "method" "POST"
                "orig" "/locations"
                "parts" (vs/jt
                  "locations")
                "select" (vs/jm)
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`"))))
          "list" (vs/jm
            "input" "data"
            "name" "list"
            "points" (vs/jt
              (vs/jm
                "args" (vs/jm
                  "query" (vs/jt
                    (vs/jm
                      "kind" "query"
                      "name" "client"
                      "orig" "client"
                      "reqd" true
                      "type" "`$STRING`")
                    (vs/jm
                      "example" 0
                      "kind" "query"
                      "name" "skip"
                      "orig" "skip"
                      "type" "`$INTEGER`")
                    (vs/jm
                      "example" 10
                      "kind" "query"
                      "name" "take"
                      "orig" "take"
                      "type" "`$INTEGER`")))
                "kind" "http"
                "method" "GET"
                "orig" "/locations"
                "parts" (vs/jt
                  "locations")
                "select" (vs/jm
                  "exist" (vs/jt
                    "client"
                    "skip"
                    "take"))
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`"))))
          "load" (vs/jm
            "input" "data"
            "name" "load"
            "points" (vs/jt
              (vs/jm
                "args" (vs/jm
                  "params" (vs/jt
                    (vs/jm
                      "kind" "param"
                      "name" "id"
                      "orig" "id"
                      "reqd" true
                      "type" "`$STRING`")))
                "kind" "http"
                "method" "GET"
                "orig" "/locations/{id}"
                "parts" (vs/jt
                  "locations"
                  "{id}")
                "select" (vs/jm
                  "exist" (vs/jt
                    "id"))
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`"))))
          "remove" (vs/jm
            "input" "data"
            "name" "remove"
            "points" (vs/jt
              (vs/jm
                "args" (vs/jm
                  "params" (vs/jt
                    (vs/jm
                      "kind" "param"
                      "name" "id"
                      "orig" "id"
                      "reqd" true
                      "type" "`$STRING`")))
                "kind" "http"
                "method" "DELETE"
                "orig" "/locations/{id}"
                "parts" (vs/jt
                  "locations"
                  "{id}")
                "select" (vs/jm
                  "exist" (vs/jt
                    "id"))
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`")))))
        "relations" (vs/jm
          "ancestors" (vs/jt)))
      "partner" (vs/jm
        "fields" (vs/jt
          (vs/jm
            "name" "billingId"
            "type" "`$STRING`")
          (vs/jm
            "name" "clientCanOrderEquipment"
            "type" "`$BOOLEAN`")
          (vs/jm
            "name" "contact"
            "op" (vs/jm
              "list" (vs/jm
                "req" true
                "type" "`$OBJECT`"))
            "type" "`$OBJECT`")
          (vs/jm
            "name" "created"
            "type" "`$STRING`")
          (vs/jm
            "name" "id"
            "type" "`$STRING`")
          (vs/jm
            "name" "isActive"
            "type" "`$BOOLEAN`")
          (vs/jm
            "name" "location"
            "req" true
            "type" "`$OBJECT`")
          (vs/jm
            "name" "modified"
            "type" "`$STRING`")
          (vs/jm
            "name" "name"
            "type" "`$STRING`")
          (vs/jm
            "name" "parent"
            "type" "`$OBJECT`")
          (vs/jm
            "name" "partnerId"
            "type" "`$STRING`")
          (vs/jm
            "name" "reference"
            "type" "`$STRING`")
          (vs/jm
            "name" "verificationPhrase"
            "type" "`$STRING`")
          (vs/jm
            "name" "version"
            "type" "`$INTEGER`"))
        "name" "partner"
        "op" (vs/jm
          "create" (vs/jm
            "input" "data"
            "name" "create"
            "points" (vs/jt
              (vs/jm
                "args" (vs/jm)
                "kind" "http"
                "method" "POST"
                "orig" "/partners"
                "parts" (vs/jt
                  "partners")
                "select" (vs/jm)
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`"))))
          "list" (vs/jm
            "input" "data"
            "name" "list"
            "points" (vs/jt
              (vs/jm
                "args" (vs/jm
                  "query" (vs/jt
                    (vs/jm
                      "kind" "query"
                      "name" "partner"
                      "orig" "partner"
                      "type" "`$STRING`")
                    (vs/jm
                      "example" 0
                      "kind" "query"
                      "name" "skip"
                      "orig" "skip"
                      "type" "`$INTEGER`")
                    (vs/jm
                      "example" 10
                      "kind" "query"
                      "name" "take"
                      "orig" "take"
                      "type" "`$INTEGER`")))
                "kind" "http"
                "method" "GET"
                "orig" "/partners"
                "parts" (vs/jt
                  "partners")
                "select" (vs/jm
                  "exist" (vs/jt
                    "partner"
                    "skip"
                    "take"))
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`"))))
          "load" (vs/jm
            "input" "data"
            "name" "load"
            "points" (vs/jt
              (vs/jm
                "args" (vs/jm
                  "params" (vs/jt
                    (vs/jm
                      "kind" "param"
                      "name" "id"
                      "orig" "id"
                      "reqd" true
                      "type" "`$STRING`")))
                "kind" "http"
                "method" "GET"
                "orig" "/partners/{id}"
                "parts" (vs/jt
                  "partners"
                  "{id}")
                "select" (vs/jm
                  "exist" (vs/jt
                    "id"))
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`")))))
        "relations" (vs/jm
          "ancestors" (vs/jt)))
      "shipment" (vs/jm
        "fields" (vs/jt
          (vs/jm
            "name" "carrier"
            "type" "`$STRING`")
          (vs/jm
            "name" "client"
            "type" "`$OBJECT`")
          (vs/jm
            "name" "created"
            "type" "`$STRING`")
          (vs/jm
            "name" "dateReceived"
            "type" "`$STRING`")
          (vs/jm
            "name" "dateShipped"
            "type" "`$STRING`")
          (vs/jm
            "name" "dcKif"
            "type" "`$OBJECT`")
          (vs/jm
            "name" "id"
            "type" "`$STRING`")
          (vs/jm
            "name" "items"
            "type" "`$ARRAY`")
          (vs/jm
            "name" "kif"
            "type" "`$OBJECT`")
          (vs/jm
            "name" "modified"
            "type" "`$STRING`")
          (vs/jm
            "name" "partner"
            "type" "`$OBJECT`")
          (vs/jm
            "name" "shipmentType"
            "type" "`$STRING`")
          (vs/jm
            "name" "tracking"
            "type" "`$STRING`")
          (vs/jm
            "name" "version"
            "type" "`$INTEGER`"))
        "name" "shipment"
        "op" (vs/jm
          "create" (vs/jm
            "input" "data"
            "name" "create"
            "points" (vs/jt
              (vs/jm
                "args" (vs/jm)
                "kind" "http"
                "method" "POST"
                "orig" "/shipments"
                "parts" (vs/jt
                  "shipments")
                "select" (vs/jm)
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`"))))
          "list" (vs/jm
            "input" "data"
            "name" "list"
            "points" (vs/jt
              (vs/jm
                "args" (vs/jm
                  "query" (vs/jt
                    (vs/jm
                      "kind" "query"
                      "name" "kif"
                      "orig" "kif"
                      "reqd" true
                      "type" "`$STRING`")
                    (vs/jm
                      "kind" "query"
                      "name" "mode"
                      "orig" "mode"
                      "type" "`$STRING`")
                    (vs/jm
                      "example" 0
                      "kind" "query"
                      "name" "skip"
                      "orig" "skip"
                      "type" "`$INTEGER`")
                    (vs/jm
                      "example" 10
                      "kind" "query"
                      "name" "take"
                      "orig" "take"
                      "type" "`$INTEGER`")))
                "kind" "http"
                "method" "GET"
                "orig" "/shipments"
                "parts" (vs/jt
                  "shipments")
                "select" (vs/jm
                  "exist" (vs/jt
                    "kif"
                    "mode"
                    "skip"
                    "take"))
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`"))))
          "load" (vs/jm
            "input" "data"
            "name" "load"
            "points" (vs/jt
              (vs/jm
                "args" (vs/jm
                  "params" (vs/jt
                    (vs/jm
                      "kind" "param"
                      "name" "id"
                      "orig" "id"
                      "reqd" true
                      "type" "`$STRING`")))
                "kind" "http"
                "method" "GET"
                "orig" "/shipments/{id}"
                "parts" (vs/jt
                  "shipments"
                  "{id}")
                "select" (vs/jm
                  "exist" (vs/jt
                    "id"))
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`")))))
        "relations" (vs/jm
          "ancestors" (vs/jt)))
      "success" (vs/jm
        "fields" (vs/jt
          (vs/jm
            "name" "success"
            "type" "`$BOOLEAN`"))
        "name" "success"
        "op" (vs/jm
          "create" (vs/jm
            "input" "data"
            "name" "create"
            "points" (vs/jt
              (vs/jm
                "args" (vs/jm
                  "params" (vs/jt
                    (vs/jm
                      "kind" "param"
                      "name" "share_partner_to"
                      "orig" "share_partner_to"
                      "reqd" true
                      "type" "`$STRING`")))
                "kind" "http"
                "method" "POST"
                "orig" "/virtualDevices/{sharePartnerTo}"
                "parts" (vs/jt
                  "virtualDevices"
                  "{share_partner_to}")
                "rename" (vs/jm
                  "param" (vs/jm
                    "sharePartnerTo" "share_partner_to"))
                "select" (vs/jm
                  "exist" (vs/jt
                    "share_partner_to"))
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`"))))
          "remove" (vs/jm
            "input" "data"
            "name" "remove"
            "points" (vs/jt
              (vs/jm
                "args" (vs/jm
                  "params" (vs/jt
                    (vs/jm
                      "kind" "param"
                      "name" "share_partner_to"
                      "orig" "share_partner_to"
                      "reqd" true
                      "type" "`$STRING`")))
                "kind" "http"
                "method" "DELETE"
                "orig" "/virtualDevices/{sharePartnerTo}"
                "parts" (vs/jt
                  "virtualDevices"
                  "{share_partner_to}")
                "rename" (vs/jm
                  "param" (vs/jm
                    "sharePartnerTo" "share_partner_to"))
                "select" (vs/jm
                  "exist" (vs/jt
                    "share_partner_to"))
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`")))))
        "relations" (vs/jm
          "ancestors" (vs/jt
            (vs/jt
              "virtual_device"))))
      "transaction" (vs/jm
        "fields" (vs/jt
          (vs/jm
            "name" "alternateKey"
            "type" "`$STRING`")
          (vs/jm
            "name" "client"
            "type" "`$OBJECT`")
          (vs/jm
            "name" "clientRef"
            "type" "`$STRING`")
          (vs/jm
            "name" "created"
            "type" "`$STRING`")
          (vs/jm
            "name" "decrypted"
            "type" "`$INTEGER`")
          (vs/jm
            "name" "deviceName"
            "type" "`$STRING`")
          (vs/jm
            "name" "directPartner"
            "type" "`$OBJECT`")
          (vs/jm
            "name" "encrypted"
            "type" "`$INTEGER`")
          (vs/jm
            "name" "endDate"
            "type" "`$STRING`")
          (vs/jm
            "name" "errCode"
            "type" "`$STRING`")
          (vs/jm
            "name" "errMessage"
            "type" "`$STRING`")
          (vs/jm
            "name" "id"
            "type" "`$STRING`")
          (vs/jm
            "name" "ipAddress"
            "type" "`$STRING`")
          (vs/jm
            "name" "isVirtual"
            "type" "`$BOOLEAN`")
          (vs/jm
            "name" "keyType"
            "type" "`$STRING`")
          (vs/jm
            "name" "location"
            "req" true
            "type" "`$OBJECT`")
          (vs/jm
            "name" "messageId"
            "type" "`$STRING`")
          (vs/jm
            "name" "method"
            "type" "`$STRING`")
          (vs/jm
            "name" "partner"
            "type" "`$OBJECT`")
          (vs/jm
            "name" "reference"
            "type" "`$STRING`")
          (vs/jm
            "name" "serialNumber"
            "type" "`$STRING`")
          (vs/jm
            "name" "startDate"
            "type" "`$STRING`")
          (vs/jm
            "name" "success"
            "type" "`$BOOLEAN`")
          (vs/jm
            "name" "transactionSource"
            "type" "`$STRING`"))
        "name" "transaction"
        "op" (vs/jm
          "create" (vs/jm
            "input" "data"
            "name" "create"
            "points" (vs/jt
              (vs/jm
                "args" (vs/jm)
                "kind" "http"
                "method" "POST"
                "orig" "/transactions"
                "parts" (vs/jt
                  "transactions")
                "select" (vs/jm)
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`"))))
          "list" (vs/jm
            "input" "data"
            "name" "list"
            "points" (vs/jt
              (vs/jm
                "args" (vs/jm
                  "query" (vs/jt
                    (vs/jm
                      "kind" "query"
                      "name" "client"
                      "orig" "client"
                      "type" "`$STRING`")
                    (vs/jm
                      "kind" "query"
                      "name" "client_ref"
                      "orig" "client_ref"
                      "type" "`$STRING`")
                    (vs/jm
                      "kind" "query"
                      "name" "date_from"
                      "orig" "date_from"
                      "type" "`$STRING`")
                    (vs/jm
                      "kind" "query"
                      "name" "date_to"
                      "orig" "date_to"
                      "type" "`$STRING`")
                    (vs/jm
                      "kind" "query"
                      "name" "location"
                      "orig" "location"
                      "type" "`$STRING`")
                    (vs/jm
                      "kind" "query"
                      "name" "message_id"
                      "orig" "message_id"
                      "type" "`$STRING`")
                    (vs/jm
                      "example" "nocount"
                      "kind" "query"
                      "name" "paging_mode"
                      "orig" "paging_mode"
                      "type" "`$STRING`")
                    (vs/jm
                      "kind" "query"
                      "name" "partner"
                      "orig" "partner"
                      "type" "`$STRING`")
                    (vs/jm
                      "kind" "query"
                      "name" "reference"
                      "orig" "reference"
                      "type" "`$STRING`")
                    (vs/jm
                      "kind" "query"
                      "name" "serial_number"
                      "orig" "serial_number"
                      "type" "`$STRING`")
                    (vs/jm
                      "example" 0
                      "kind" "query"
                      "name" "skip"
                      "orig" "skip"
                      "type" "`$INTEGER`")
                    (vs/jm
                      "kind" "query"
                      "name" "success"
                      "orig" "success"
                      "type" "`$BOOLEAN`")
                    (vs/jm
                      "example" 10
                      "kind" "query"
                      "name" "take"
                      "orig" "take"
                      "type" "`$INTEGER`")))
                "kind" "http"
                "method" "GET"
                "orig" "/transactions"
                "parts" (vs/jt
                  "transactions")
                "select" (vs/jm
                  "exist" (vs/jt
                    "client"
                    "client_ref"
                    "date_from"
                    "date_to"
                    "location"
                    "message_id"
                    "paging_mode"
                    "partner"
                    "reference"
                    "serial_number"
                    "skip"
                    "success"
                    "take"))
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`"))))
          "load" (vs/jm
            "input" "data"
            "name" "load"
            "points" (vs/jt
              (vs/jm
                "args" (vs/jm
                  "params" (vs/jt
                    (vs/jm
                      "kind" "param"
                      "name" "id"
                      "orig" "id"
                      "reqd" true
                      "type" "`$STRING`")))
                "kind" "http"
                "method" "GET"
                "orig" "/transactions/{id}"
                "parts" (vs/jt
                  "transactions"
                  "{id}")
                "select" (vs/jm
                  "exist" (vs/jt
                    "id"))
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`")))))
        "relations" (vs/jm
          "ancestors" (vs/jt)))
      "update_result" (vs/jm
        "fields" (vs/jt
          (vs/jm
            "name" "client"
            "type" "`$OBJECT`")
          (vs/jm
            "name" "email"
            "type" "`$STRING`")
          (vs/jm
            "name" "firstName"
            "type" "`$STRING`")
          (vs/jm
            "name" "id"
            "type" "`$STRING`")
          (vs/jm
            "name" "isActive"
            "type" "`$BOOLEAN`")
          (vs/jm
            "name" "kif"
            "type" "`$OBJECT`")
          (vs/jm
            "name" "lastName"
            "type" "`$STRING`")
          (vs/jm
            "name" "partner"
            "type" "`$OBJECT`")
          (vs/jm
            "name" "phone"
            "type" "`$STRING`")
          (vs/jm
            "name" "userName"
            "type" "`$STRING`")
          (vs/jm
            "name" "userRole"
            "type" "`$OBJECT`")
          (vs/jm
            "name" "version"
            "type" "`$INTEGER`"))
        "name" "update_result"
        "op" (vs/jm
          "create" (vs/jm
            "input" "data"
            "name" "create"
            "points" (vs/jt
              (vs/jm
                "args" (vs/jm)
                "kind" "http"
                "method" "POST"
                "orig" "/users"
                "parts" (vs/jt
                  "users")
                "select" (vs/jm)
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`"))))
          "list" (vs/jm
            "input" "data"
            "name" "list"
            "points" (vs/jt
              (vs/jm
                "args" (vs/jm
                  "query" (vs/jt
                    (vs/jm
                      "kind" "query"
                      "name" "client"
                      "orig" "client"
                      "type" "`$STRING`")
                    (vs/jm
                      "kind" "query"
                      "name" "kif"
                      "orig" "kif"
                      "type" "`$STRING`")
                    (vs/jm
                      "kind" "query"
                      "name" "partner"
                      "orig" "partner"
                      "type" "`$ANY`")
                    (vs/jm
                      "example" 0
                      "kind" "query"
                      "name" "skip"
                      "orig" "skip"
                      "type" "`$INTEGER`")
                    (vs/jm
                      "example" 10
                      "kind" "query"
                      "name" "take"
                      "orig" "take"
                      "type" "`$INTEGER`")))
                "kind" "http"
                "method" "GET"
                "orig" "/users"
                "parts" (vs/jt
                  "users")
                "select" (vs/jm
                  "exist" (vs/jt
                    "client"
                    "kif"
                    "partner"
                    "skip"
                    "take"))
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`"))))
          "update" (vs/jm
            "input" "data"
            "name" "update"
            "points" (vs/jt
              (vs/jm
                "args" (vs/jm
                  "params" (vs/jt
                    (vs/jm
                      "kind" "param"
                      "name" "id"
                      "orig" "id"
                      "reqd" true
                      "type" "`$STRING`")))
                "kind" "http"
                "method" "PATCH"
                "orig" "/clients/{id}"
                "parts" (vs/jt
                  "clients"
                  "{id}")
                "select" (vs/jm
                  "exist" (vs/jt
                    "id"))
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`"))
              (vs/jm
                "args" (vs/jm
                  "params" (vs/jt
                    (vs/jm
                      "kind" "param"
                      "name" "id"
                      "orig" "id"
                      "reqd" true
                      "type" "`$STRING`")))
                "kind" "http"
                "method" "PATCH"
                "orig" "/devices/{id}"
                "parts" (vs/jt
                  "devices"
                  "{id}")
                "select" (vs/jm
                  "exist" (vs/jt
                    "id"))
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`"))
              (vs/jm
                "args" (vs/jm
                  "params" (vs/jt
                    (vs/jm
                      "kind" "param"
                      "name" "id"
                      "orig" "id"
                      "reqd" true
                      "type" "`$STRING`")))
                "kind" "http"
                "method" "PATCH"
                "orig" "/locations/{id}"
                "parts" (vs/jt
                  "locations"
                  "{id}")
                "select" (vs/jm
                  "exist" (vs/jt
                    "id"))
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`"))
              (vs/jm
                "args" (vs/jm
                  "params" (vs/jt
                    (vs/jm
                      "kind" "param"
                      "name" "id"
                      "orig" "id"
                      "reqd" true
                      "type" "`$STRING`")))
                "kind" "http"
                "method" "PATCH"
                "orig" "/partners/{id}"
                "parts" (vs/jt
                  "partners"
                  "{id}")
                "select" (vs/jm
                  "exist" (vs/jt
                    "id"))
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`"))
              (vs/jm
                "args" (vs/jm
                  "params" (vs/jt
                    (vs/jm
                      "kind" "param"
                      "name" "id"
                      "orig" "id"
                      "reqd" true
                      "type" "`$STRING`")))
                "kind" "http"
                "method" "PATCH"
                "orig" "/shipments/{id}"
                "parts" (vs/jt
                  "shipments"
                  "{id}")
                "select" (vs/jm
                  "exist" (vs/jt
                    "id"))
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`"))
              (vs/jm
                "args" (vs/jm
                  "params" (vs/jt
                    (vs/jm
                      "kind" "param"
                      "name" "id"
                      "orig" "id"
                      "reqd" true
                      "type" "`$STRING`")))
                "kind" "http"
                "method" "PATCH"
                "orig" "/transactions/{id}"
                "parts" (vs/jt
                  "transactions"
                  "{id}")
                "select" (vs/jm
                  "exist" (vs/jt
                    "id"))
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`"))
              (vs/jm
                "args" (vs/jm
                  "params" (vs/jt
                    (vs/jm
                      "kind" "param"
                      "name" "id"
                      "orig" "id"
                      "reqd" true
                      "type" "`$STRING`")))
                "kind" "http"
                "method" "PATCH"
                "orig" "/users/{id}"
                "parts" (vs/jt
                  "users"
                  "{id}")
                "select" (vs/jm
                  "exist" (vs/jt
                    "id"))
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`")))))
        "relations" (vs/jm
          "ancestors" (vs/jt)))
      "user" (vs/jm
        "fields" (vs/jt
          (vs/jm
            "name" "client"
            "type" "`$OBJECT`")
          (vs/jm
            "name" "created"
            "type" "`$STRING`")
          (vs/jm
            "name" "email"
            "type" "`$STRING`")
          (vs/jm
            "name" "firstName"
            "type" "`$STRING`")
          (vs/jm
            "name" "id"
            "type" "`$STRING`")
          (vs/jm
            "name" "isActive"
            "type" "`$BOOLEAN`")
          (vs/jm
            "name" "kif"
            "type" "`$OBJECT`")
          (vs/jm
            "name" "lastName"
            "type" "`$STRING`")
          (vs/jm
            "name" "modified"
            "type" "`$STRING`")
          (vs/jm
            "name" "partner"
            "type" "`$OBJECT`")
          (vs/jm
            "name" "phone"
            "type" "`$STRING`")
          (vs/jm
            "name" "userName"
            "type" "`$STRING`")
          (vs/jm
            "name" "userRole"
            "type" "`$OBJECT`")
          (vs/jm
            "name" "version"
            "type" "`$INTEGER`"))
        "name" "user"
        "op" (vs/jm
          "load" (vs/jm
            "input" "data"
            "name" "load"
            "points" (vs/jt
              (vs/jm
                "args" (vs/jm
                  "params" (vs/jt
                    (vs/jm
                      "kind" "param"
                      "name" "id"
                      "orig" "id"
                      "reqd" true
                      "type" "`$STRING`")))
                "kind" "http"
                "method" "GET"
                "orig" "/users/{id}"
                "parts" (vs/jt
                  "users"
                  "{id}")
                "select" (vs/jm
                  "exist" (vs/jt
                    "id"))
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`"))))
          "remove" (vs/jm
            "input" "data"
            "name" "remove"
            "points" (vs/jt
              (vs/jm
                "args" (vs/jm
                  "params" (vs/jt
                    (vs/jm
                      "kind" "param"
                      "name" "id"
                      "orig" "id"
                      "reqd" true
                      "type" "`$STRING`")))
                "kind" "http"
                "method" "DELETE"
                "orig" "/users/{id}"
                "parts" (vs/jt
                  "users"
                  "{id}")
                "select" (vs/jm
                  "exist" (vs/jt
                    "id"))
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`")))))
        "relations" (vs/jm
          "ancestors" (vs/jt))))
    "feature" (vs/jm
      "test" (vs/jm
        "options" (vs/jm
          "active" false)))
    "main" (vs/jm
      "name" "BluefinDecryptxP2pe")
    "options" (vs/jm
      "auth" (vs/jm
        "prefix" "Basic")
      "base" "https://apis.p2pemanager.com/api/v1"
      "entity" (vs/jm
        "attestation" (vs/jm)
        "client" (vs/jm)
        "create_result" (vs/jm)
        "decryption" (vs/jm)
        "device" (vs/jm)
        "device_build" (vs/jm)
        "device_custody_detail" (vs/jm)
        "device_custody_list" (vs/jm)
        "device_list" (vs/jm)
        "device_receive_result" (vs/jm)
        "device_rki_activate_result" (vs/jm)
        "device_state" (vs/jm)
        "device_type" (vs/jm)
        "inject_key" (vs/jm)
        "kif" (vs/jm)
        "location" (vs/jm)
        "partner" (vs/jm)
        "shipment" (vs/jm)
        "success" (vs/jm)
        "transaction" (vs/jm)
        "update_result" (vs/jm)
        "user" (vs/jm))
      "headers" (vs/jm
        "content-type" "application/json"))))
