;; BluefinDecryptxP2pe SDK configuration (generated by @voxgig/sdkgen).
(ns sdk.config
  (:require [voxgig.struct :as vs]))

(defn make-config []
  (vs/jm
    "entity" (vs/jm
      "attestation" (vs/jm
        "fields" (vs/jt
          (vs/jm
            "name" "client"
            "short" "Reference to the associated Client resource."
            "type" "`$OBJECT`")
          (vs/jm
            "name" "completeDate"
            "short" "The date and time that the Attestation took place."
            "type" "`$STRING`")
          (vs/jm
            "name" "created"
            "short" "Creation timestamp in ISO 8601 format."
            "type" "`$STRING`")
          (vs/jm
            "name" "device"
            "short" "Reference to the associated Device resource."
            "type" "`$OBJECT`")
          (vs/jm
            "name" "id"
            "short" "This resource's unique identifier."
            "type" "`$STRING`")
          (vs/jm
            "name" "name"
            "short" "Text describing the attestation."
            "type" "`$STRING`")
          (vs/jm
            "name" "notes"
            "short" "Free form field that allows the Client associate notes with the Attestation."
            "type" "`$STRING`"))
        "name" "attestation"
        "op" (vs/jm
          "create" (vs/jm
            "input" "data"
            "name" "create"
            "points" (vs/jt
              (vs/jm
                "args" (vs/jm)
                "kind" "http"
                "method" "POST"
                "orig" "/attestations"
                "parts" (vs/jt
                  "attestations")
                "select" (vs/jm)
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`"))))
          "list" (vs/jm
            "input" "data"
            "name" "list"
            "points" (vs/jt
              (vs/jm
                "args" (vs/jm
                  "query" (vs/jt
                    (vs/jm
                      "kind" "query"
                      "name" "client"
                      "orig" "client"
                      "reqd" true
                      "type" "`$STRING`")
                    (vs/jm
                      "example" 0
                      "kind" "query"
                      "name" "skip"
                      "orig" "skip"
                      "type" "`$INTEGER`")
                    (vs/jm
                      "example" 10
                      "kind" "query"
                      "name" "take"
                      "orig" "take"
                      "type" "`$INTEGER`")))
                "kind" "http"
                "method" "GET"
                "orig" "/attestations"
                "parts" (vs/jt
                  "attestations")
                "select" (vs/jm
                  "exist" (vs/jt
                    "client"
                    "skip"
                    "take"))
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body.data`"))))
          "load" (vs/jm
            "input" "data"
            "name" "load"
            "points" (vs/jt
              (vs/jm
                "args" (vs/jm
                  "params" (vs/jt
                    (vs/jm
                      "kind" "param"
                      "name" "id"
                      "orig" "id"
                      "reqd" true
                      "type" "`$STRING`")))
                "kind" "http"
                "method" "GET"
                "orig" "/attestations/{id}"
                "parts" (vs/jt
                  "attestations"
                  "{id}")
                "select" (vs/jm
                  "exist" (vs/jt
                    "id"))
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`")))))
        "relations" (vs/jm
          "ancestors" (vs/jt)))
      "client" (vs/jm
        "fields" (vs/jt
          (vs/jm
            "name" "contact"
            "op" (vs/jm
              "list" (vs/jm
                "req" true
                "type" "`$OBJECT`"))
            "short" "Reference to the associated User resource."
            "type" "`$OBJECT`")
          (vs/jm
            "name" "created"
            "short" "Creation timestamp in ISO 8601 format."
            "type" "`$STRING`")
          (vs/jm
            "name" "directPartner"
            "short" "Reference to the associated Partner."
            "type" "`$OBJECT`")
          (vs/jm
            "name" "id"
            "short" "This resource's unique identifier."
            "type" "`$STRING`")
          (vs/jm
            "name" "isActive"
            "short" "This property indicates if the Client account is active or disabled."
            "type" "`$BOOLEAN`")
          (vs/jm
            "name" "location"
            "req" true
            "short" "Reference to the associated Location resource."
            "type" "`$OBJECT`")
          (vs/jm
            "name" "mid"
            "short" "Some Partners will have an merchant ids on their own software offerings."
            "type" "`$STRING`")
          (vs/jm
            "name" "modified"
            "short" "Last modified timestamp."
            "type" "`$STRING`")
          (vs/jm
            "name" "name"
            "short" "The Client's name."
            "type" "`$STRING`")
          (vs/jm
            "name" "partner"
            "short" "Reference to the Client's root Partner."
            "type" "`$OBJECT`")
          (vs/jm
            "name" "version"
            "short" "The number of times that this resource has been updated."
            "type" "`$INTEGER`"))
        "name" "client"
        "op" (vs/jm
          "create" (vs/jm
            "input" "data"
            "name" "create"
            "points" (vs/jt
              (vs/jm
                "args" (vs/jm)
                "kind" "http"
                "method" "POST"
                "orig" "/clients"
                "parts" (vs/jt
                  "clients")
                "select" (vs/jm)
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`"))))
          "list" (vs/jm
            "input" "data"
            "name" "list"
            "points" (vs/jt
              (vs/jm
                "args" (vs/jm
                  "query" (vs/jt
                    (vs/jm
                      "kind" "query"
                      "name" "partner"
                      "orig" "partner"
                      "reqd" true
                      "type" "`$STRING`")
                    (vs/jm
                      "example" 0
                      "kind" "query"
                      "name" "skip"
                      "orig" "skip"
                      "type" "`$INTEGER`")
                    (vs/jm
                      "example" 10
                      "kind" "query"
                      "name" "take"
                      "orig" "take"
                      "type" "`$INTEGER`")))
                "kind" "http"
                "method" "GET"
                "orig" "/clients"
                "parts" (vs/jt
                  "clients")
                "select" (vs/jm
                  "exist" (vs/jt
                    "partner"
                    "skip"
                    "take"))
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body.data`"))))
          "load" (vs/jm
            "input" "data"
            "name" "load"
            "points" (vs/jt
              (vs/jm
                "args" (vs/jm
                  "params" (vs/jt
                    (vs/jm
                      "kind" "param"
                      "name" "id"
                      "orig" "id"
                      "reqd" true
                      "type" "`$STRING`")))
                "kind" "http"
                "method" "GET"
                "orig" "/clients/{id}"
                "parts" (vs/jt
                  "clients"
                  "{id}")
                "select" (vs/jm
                  "exist" (vs/jt
                    "id"))
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`"))))
          "remove" (vs/jm
            "input" "data"
            "name" "remove"
            "points" (vs/jt
              (vs/jm
                "args" (vs/jm
                  "params" (vs/jt
                    (vs/jm
                      "kind" "param"
                      "name" "id"
                      "orig" "id"
                      "reqd" true
                      "type" "`$STRING`")))
                "kind" "http"
                "method" "DELETE"
                "orig" "/clients/{id}"
                "parts" (vs/jt
                  "clients"
                  "{id}")
                "select" (vs/jm
                  "exist" (vs/jt
                    "id"))
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`")))))
        "relations" (vs/jm
          "ancestors" (vs/jt)))
      "create_result" (vs/jm
        "fields" (vs/jt)
        "name" "create_result"
        "op" (vs/jm
          "create" (vs/jm
            "input" "data"
            "name" "create"
            "points" (vs/jt
              (vs/jm
                "args" (vs/jm
                  "params" (vs/jt
                    (vs/jm
                      "kind" "param"
                      "name" "device_type"
                      "orig" "device_type"
                      "reqd" true
                      "type" "`$STRING`")
                    (vs/jm
                      "kind" "param"
                      "name" "serial_number"
                      "orig" "serial_number"
                      "reqd" true
                      "type" "`$STRING`")))
                "kind" "http"
                "method" "POST"
                "orig" "/devices/{serialNumber}/{deviceType}/custody"
                "parts" (vs/jt
                  "devices"
                  "{serial_number}"
                  "{device_type}"
                  "custody")
                "rename" (vs/jm
                  "param" (vs/jm
                    "deviceType" "device_type"
                    "serialNumber" "serial_number"))
                "select" (vs/jm
                  "exist" (vs/jt
                    "device_type"
                    "serial_number"))
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`")))))
        "relations" (vs/jm
          "ancestors" (vs/jt
            (vs/jt
              "device"))))
      "decryption" (vs/jm
        "fields" (vs/jt
          (vs/jm
            "name" "success"
            "short" "true if the payload decryption was successful."
            "type" "`$BOOLEAN`"))
        "name" "decryption"
        "op" (vs/jm
          "create" (vs/jm
            "input" "data"
            "name" "create"
            "points" (vs/jt
              (vs/jm
                "args" (vs/jm)
                "kind" "http"
                "method" "POST"
                "orig" "/decryption"
                "parts" (vs/jt
                  "decryption")
                "select" (vs/jm)
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`")))))
        "relations" (vs/jm
          "ancestors" (vs/jt)))
      "device" (vs/jm
        "fields" (vs/jt
          (vs/jm
            "name" "activatedBy"
            "req" true
            "short" "Reference to the associated User resource."
            "type" "`$OBJECT`")
          (vs/jm
            "name" "activationDate"
            "short" "Timestamp from when the Device was activated."
            "type" "`$STRING`")
          (vs/jm
            "name" "alternateKey"
            "short" "The alternative key is used when a Device outputs a different serial number from its firmware/software when compared to the serial number that is printed on the Device's casing or its packaging."
            "type" "`$STRING`")
          (vs/jm
            "name" "auditNextDate"
            "short" "Date and time that the Device is due its next PCI Audit."
            "type" "`$STRING`")
          (vs/jm
            "name" "auditNotificationDate"
            "short" "Date and time that a notification should be sent that a PCI audit is due."
            "type" "`$STRING`")
          (vs/jm
            "name" "client"
            "short" "Reference to the associated Client resource."
            "type" "`$OBJECT`")
          (vs/jm
            "name" "created"
            "short" "Creation timestamp in ISO 8601 format."
            "type" "`$STRING`")
          (vs/jm
            "name" "createdBy"
            "req" true
            "short" "Reference to the associated User resource."
            "type" "`$OBJECT`")
          (vs/jm
            "name" "deviceBuild"
            "short" "Reference to the associated Device Build resource."
            "type" "`$OBJECT`")
          (vs/jm
            "name" "deviceState"
            "short" "Reference to the associated Device State resource."
            "type" "`$OBJECT`")
          (vs/jm
            "name" "deviceType"
            "short" "Reference to the associated Device Type resource."
            "type" "`$OBJECT`")
          (vs/jm
            "name" "errorCounter"
            "short" "The number times the Device has been in error."
            "type" "`$INTEGER`")
          (vs/jm
            "name" "errorLastDate"
            "short" "Timestamp from the last time that the Device had an error."
            "type" "`$STRING`")
          (vs/jm
            "name" "id"
            "short" "The Device's unique identifier."
            "type" "`$STRING`")
          (vs/jm
            "name" "initializedBy"
            "req" true
            "short" "Reference to the associated User resource."
            "type" "`$OBJECT`")
          (vs/jm
            "name" "initializedDate"
            "short" "Timestamp from when the Device was initialized."
            "type" "`$STRING`")
          (vs/jm
            "name" "injectKey"
            "short" "Reference to the associated Device resource."
            "type" "`$OBJECT`")
          (vs/jm
            "name" "isVirtual"
            "short" "Indicates if a Device is Virtual (represents a Device shared with a partner)."
            "type" "`$BOOLEAN`")
          (vs/jm
            "name" "kif"
            "short" "Reference to the associated KIF resource."
            "type" "`$OBJECT`")
          (vs/jm
            "name" "lastActivityDate"
            "short" "Timestamp from the last time that the Device was used."
            "type" "`$STRING`")
          (vs/jm
            "name" "location"
            "req" true
            "short" "Reference to the associated Location resource."
            "type" "`$OBJECT`")
          (vs/jm
            "name" "modified"
            "short" "Last modified timestamp."
            "type" "`$STRING`")
          (vs/jm
            "name" "modifiedBy"
            "req" true
            "short" "Reference to the associated User resource."
            "type" "`$OBJECT`")
          (vs/jm
            "name" "name"
            "short" "The Device's name."
            "type" "`$STRING`")
          (vs/jm
            "name" "notes"
            "short" "Arbitary note that can be attached to a Device entry."
            "type" "`$STRING`")
          (vs/jm
            "name" "partner"
            "short" "Reference to the associated Partner."
            "type" "`$OBJECT`")
          (vs/jm
            "name" "serialNumber"
            "short" "The Device's serial number."
            "type" "`$STRING`")
          (vs/jm
            "name" "version"
            "short" "The number of times that this resource has been updated."
            "type" "`$INTEGER`"))
        "name" "device"
        "op" (vs/jm
          "create" (vs/jm
            "input" "data"
            "name" "create"
            "points" (vs/jt
              (vs/jm
                "args" (vs/jm)
                "kind" "http"
                "method" "POST"
                "orig" "/devices"
                "parts" (vs/jt
                  "devices")
                "select" (vs/jm)
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`"))))
          "list" (vs/jm
            "input" "data"
            "name" "list"
            "points" (vs/jt
              (vs/jm
                "args" (vs/jm
                  "query" (vs/jt
                    (vs/jm
                      "kind" "query"
                      "name" "client"
                      "orig" "client"
                      "type" "`$STRING`")
                    (vs/jm
                      "kind" "query"
                      "name" "device_state"
                      "orig" "device_state"
                      "type" "`$STRING`")
                    (vs/jm
                      "kind" "query"
                      "name" "kif"
                      "orig" "kif"
                      "type" "`$STRING`")
                    (vs/jm
                      "kind" "query"
                      "name" "partner"
                      "orig" "partner"
                      "type" "`$STRING`")
                    (vs/jm
                      "kind" "query"
                      "name" "serial_number"
                      "orig" "serial_number"
                      "type" "`$STRING`")
                    (vs/jm
                      "example" 0
                      "kind" "query"
                      "name" "skip"
                      "orig" "skip"
                      "type" "`$INTEGER`")
                    (vs/jm
                      "example" "asc"
                      "kind" "query"
                      "name" "sorting_direction"
                      "orig" "sorting_direction"
                      "type" "`$STRING`")
                    (vs/jm
                      "example" "serialnumber"
                      "kind" "query"
                      "name" "sorting_field"
                      "orig" "sorting_field"
                      "type" "`$STRING`")
                    (vs/jm
                      "example" 10
                      "kind" "query"
                      "name" "take"
                      "orig" "take"
                      "type" "`$INTEGER`")))
                "kind" "http"
                "method" "GET"
                "orig" "/devices"
                "parts" (vs/jt
                  "devices")
                "select" (vs/jm
                  "exist" (vs/jt
                    "client"
                    "device_state"
                    "kif"
                    "partner"
                    "serial_number"
                    "skip"
                    "sorting_direction"
                    "sorting_field"
                    "take"))
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body.data`"))))
          "load" (vs/jm
            "input" "data"
            "name" "load"
            "points" (vs/jt
              (vs/jm
                "args" (vs/jm
                  "params" (vs/jt
                    (vs/jm
                      "kind" "param"
                      "name" "device_type"
                      "orig" "device_type"
                      "reqd" true
                      "type" "`$STRING`")
                    (vs/jm
                      "kind" "param"
                      "name" "serial_number"
                      "orig" "serial_number"
                      "reqd" true
                      "type" "`$STRING`")))
                "kind" "http"
                "method" "GET"
                "orig" "/devices/{serialNumber}/{deviceType}"
                "parts" (vs/jt
                  "devices"
                  "{serial_number}"
                  "{device_type}")
                "rename" (vs/jm
                  "param" (vs/jm
                    "deviceType" "device_type"
                    "serialNumber" "serial_number"))
                "select" (vs/jm
                  "exist" (vs/jt
                    "device_type"
                    "serial_number"))
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`"))
              (vs/jm
                "args" (vs/jm
                  "params" (vs/jt
                    (vs/jm
                      "kind" "param"
                      "name" "id"
                      "orig" "id"
                      "reqd" true
                      "type" "`$STRING`")))
                "kind" "http"
                "method" "GET"
                "orig" "/devices/{id}"
                "parts" (vs/jt
                  "devices"
                  "{id}")
                "select" (vs/jm
                  "exist" (vs/jt
                    "id"))
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`")))))
        "relations" (vs/jm
          "ancestors" (vs/jt
            (vs/jt
              "device"))))
      "device_build" (vs/jm
        "fields" (vs/jt
          (vs/jm
            "name" "appVersion"
            "short" "If a Device Type has more than one Application Code version the supported version is specified here."
            "type" "`$STRING`")
          (vs/jm
            "name" "buildNumber"
            "short" "The Build Number."
            "type" "`$STRING`")
          (vs/jm
            "name" "configFileName"
            "short" "The name of the configuration file that is uploaded to the device."
            "type" "`$STRING`")
          (vs/jm
            "name" "created"
            "short" "Creation timestamp in ISO 8601 format."
            "type" "`$STRING`")
          (vs/jm
            "name" "deviceType"
            "short" "The Device Type Name."
            "type" "`$STRING`")
          (vs/jm
            "name" "firmwareVersion"
            "short" "A list of firmware versions that this Device Build covers."
            "type" "`$STRING`")
          (vs/jm
            "name" "hardwareVersion"
            "short" "A list of hardware versions that this Device Build covers."
            "type" "`$STRING`")
          (vs/jm
            "name" "id"
            "short" "This resource's unique identifier."
            "type" "`$INTEGER`")
          (vs/jm
            "name" "isActive"
            "short" "This property indicates if the device build is still active and not succeeded by subsequent build."
            "type" "`$BOOLEAN`")
          (vs/jm
            "name" "modified"
            "short" "Last modified timestamp."
            "type" "`$STRING`")
          (vs/jm
            "name" "name"
            "short" "The Device Builds's name."
            "type" "`$STRING`")
          (vs/jm
            "name" "notes"
            "short" "Notes attached to the device build by Bluefin CISO."
            "type" "`$STRING`")
          (vs/jm
            "name" "version"
            "short" "The number of times that this resource has been updated."
            "type" "`$INTEGER`")
          (vs/jm
            "name" "whiteListingBinRanges"
            "short" "A comma separated list of BIN ranges that aren't encrypted by the terminal."
            "type" "`$STRING`")
          (vs/jm
            "name" "whiteListingUsed"
            "short" "This value is used in conjunction with whiteListingBinRanges to indicate the range card numbers that aren't encrypted by the terminal."
            "type" "`$BOOLEAN`"))
        "name" "device_build"
        "op" (vs/jm
          "list" (vs/jm
            "input" "data"
            "name" "list"
            "points" (vs/jt
              (vs/jm
                "args" (vs/jm
                  "query" (vs/jt
                    (vs/jm
                      "kind" "query"
                      "name" "device_type"
                      "orig" "device_type"
                      "type" "`$STRING`")
                    (vs/jm
                      "example" 0
                      "kind" "query"
                      "name" "skip"
                      "orig" "skip"
                      "type" "`$INTEGER`")
                    (vs/jm
                      "example" 10
                      "kind" "query"
                      "name" "take"
                      "orig" "take"
                      "type" "`$INTEGER`")))
                "kind" "http"
                "method" "GET"
                "orig" "/deviceBuilds"
                "parts" (vs/jt
                  "deviceBuilds")
                "select" (vs/jm
                  "exist" (vs/jt
                    "device_type"
                    "skip"
                    "take"))
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body.data`"))))
          "load" (vs/jm
            "input" "data"
            "name" "load"
            "points" (vs/jt
              (vs/jm
                "args" (vs/jm
                  "params" (vs/jt
                    (vs/jm
                      "kind" "param"
                      "name" "id"
                      "orig" "id"
                      "reqd" true
                      "type" "`$STRING`")))
                "kind" "http"
                "method" "GET"
                "orig" "/deviceBuilds/{id}"
                "parts" (vs/jt
                  "deviceBuilds"
                  "{id}")
                "select" (vs/jm
                  "exist" (vs/jt
                    "id"))
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`")))))
        "relations" (vs/jm
          "ancestors" (vs/jt)))
      "device_custody_detail" (vs/jm
        "fields" (vs/jt
          (vs/jm
            "name" "completeDate"
            "short" "The date and time that the Custody change took place."
            "type" "`$STRING`")
          (vs/jm
            "name" "created"
            "short" "Creation timestamp in ISO 8601 format."
            "type" "`$STRING`")
          (vs/jm
            "name" "createdBy"
            "req" true
            "short" "Reference to the associated User resource."
            "type" "`$OBJECT`")
          (vs/jm
            "name" "custodian"
            "req" true
            "short" "Reference to the associated User resource."
            "type" "`$OBJECT`")
          (vs/jm
            "name" "device"
            "short" "Reference to the associated Device resource."
            "type" "`$OBJECT`")
          (vs/jm
            "name" "id"
            "short" "This resource's unique identifier."
            "type" "`$INTEGER`")
          (vs/jm
            "name" "location"
            "req" true
            "short" "Reference to the associated Location resource."
            "type" "`$OBJECT`")
          (vs/jm
            "name" "modified"
            "short" "Last modified timestamp."
            "type" "`$STRING`")
          (vs/jm
            "name" "modifiedBy"
            "req" true
            "short" "Reference to the associated User resource."
            "type" "`$OBJECT`")
          (vs/jm
            "name" "notes"
            "short" "Free form field that allows the Client associate notes with the Custody Change."
            "type" "`$STRING`")
          (vs/jm
            "name" "status"
            "short" "Reference to the associated Custody Status."
            "type" "`$OBJECT`")
          (vs/jm
            "name" "transferMethod"
            "short" "Reference to the associated Transfer Method."
            "type" "`$OBJECT`")
          (vs/jm
            "name" "version"
            "short" "The number of times that this resource has been updated."
            "type" "`$INTEGER`"))
        "name" "device_custody_detail"
        "op" (vs/jm
          "load" (vs/jm
            "input" "data"
            "name" "load"
            "points" (vs/jt
              (vs/jm
                "args" (vs/jm
                  "params" (vs/jt
                    (vs/jm
                      "kind" "param"
                      "name" "device_type"
                      "orig" "device_type"
                      "reqd" true
                      "type" "`$STRING`")
                    (vs/jm
                      "kind" "param"
                      "name" "id"
                      "orig" "id"
                      "reqd" true
                      "type" "`$STRING`")
                    (vs/jm
                      "kind" "param"
                      "name" "serial_number"
                      "orig" "serial_number"
                      "reqd" true
                      "type" "`$STRING`")))
                "kind" "http"
                "method" "GET"
                "orig" "/devices/{serialNumber}/{deviceType}/custody/{id}"
                "parts" (vs/jt
                  "devices"
                  "{serial_number}"
                  "{device_type}"
                  "custody"
                  "{id}")
                "rename" (vs/jm
                  "param" (vs/jm
                    "deviceType" "device_type"
                    "serialNumber" "serial_number"))
                "select" (vs/jm
                  "exist" (vs/jt
                    "device_type"
                    "id"
                    "serial_number"))
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`")))))
        "relations" (vs/jm
          "ancestors" (vs/jt
            (vs/jt
              "device"))))
      "device_custody_list" (vs/jm
        "fields" (vs/jt
          (vs/jm
            "name" "completeDate"
            "short" "The date and time that the Custody change took place."
            "type" "`$STRING`")
          (vs/jm
            "name" "created"
            "short" "Creation timestamp in ISO 8601 format."
            "type" "`$STRING`")
          (vs/jm
            "name" "createdBy"
            "req" true
            "short" "Reference to the associated User resource."
            "type" "`$OBJECT`")
          (vs/jm
            "name" "custodian"
            "req" true
            "short" "Reference to the associated User resource."
            "type" "`$OBJECT`")
          (vs/jm
            "name" "device"
            "short" "Reference to the associated Device resource."
            "type" "`$OBJECT`")
          (vs/jm
            "name" "id"
            "short" "This resource's unique identifier."
            "type" "`$INTEGER`")
          (vs/jm
            "name" "location"
            "req" true
            "short" "Reference to the associated Location resource."
            "type" "`$OBJECT`")
          (vs/jm
            "name" "modified"
            "short" "Last modified timestamp."
            "type" "`$STRING`")
          (vs/jm
            "name" "modifiedBy"
            "req" true
            "short" "Reference to the associated User resource."
            "type" "`$OBJECT`")
          (vs/jm
            "name" "notes"
            "short" "Free form field that allows the Client associate notes with the Custody Change."
            "type" "`$STRING`")
          (vs/jm
            "name" "status"
            "short" "Reference to the associated Custody Status."
            "type" "`$OBJECT`")
          (vs/jm
            "name" "transferMethod"
            "short" "Reference to the associated Transfer Method."
            "type" "`$OBJECT`")
          (vs/jm
            "name" "version"
            "short" "The number of times that this resource has been updated."
            "type" "`$INTEGER`"))
        "name" "device_custody_list"
        "op" (vs/jm
          "list" (vs/jm
            "input" "data"
            "name" "list"
            "points" (vs/jt
              (vs/jm
                "args" (vs/jm
                  "params" (vs/jt
                    (vs/jm
                      "kind" "param"
                      "name" "device_type"
                      "orig" "device_type"
                      "reqd" true
                      "type" "`$STRING`")
                    (vs/jm
                      "kind" "param"
                      "name" "serial_number"
                      "orig" "serial_number"
                      "reqd" true
                      "type" "`$STRING`"))
                  "query" (vs/jt
                    (vs/jm
                      "example" 0
                      "kind" "query"
                      "name" "skip"
                      "orig" "skip"
                      "type" "`$INTEGER`")
                    (vs/jm
                      "example" 10
                      "kind" "query"
                      "name" "take"
                      "orig" "take"
                      "type" "`$INTEGER`")))
                "kind" "http"
                "method" "GET"
                "orig" "/devices/{serialNumber}/{deviceType}/custody"
                "parts" (vs/jt
                  "devices"
                  "{serial_number}"
                  "{device_type}"
                  "custody")
                "rename" (vs/jm
                  "param" (vs/jm
                    "deviceType" "device_type"
                    "serialNumber" "serial_number"))
                "select" (vs/jm
                  "exist" (vs/jt
                    "device_type"
                    "serial_number"
                    "skip"
                    "take"))
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body.data`")))))
        "relations" (vs/jm
          "ancestors" (vs/jt
            (vs/jt
              "device"))))
      "device_list" (vs/jm
        "fields" (vs/jt
          (vs/jm
            "name" "data"
            "short" "List of Devices."
            "type" "`$ARRAY`")
          (vs/jm
            "name" "total"
            "short" "Total number of Devices available (not the number of Users in the response)."
            "type" "`$INTEGER`"))
        "name" "device_list"
        "op" (vs/jm
          "load" (vs/jm
            "input" "data"
            "name" "load"
            "points" (vs/jt
              (vs/jm
                "args" (vs/jm
                  "params" (vs/jt
                    (vs/jm
                      "kind" "param"
                      "name" "share_partner_to"
                      "orig" "share_partner_to"
                      "reqd" true
                      "type" "`$STRING`"))
                  "query" (vs/jt
                    (vs/jm
                      "example" 0
                      "kind" "query"
                      "name" "skip"
                      "orig" "skip"
                      "type" "`$INTEGER`")
                    (vs/jm
                      "example" "asc"
                      "kind" "query"
                      "name" "sorting_direction"
                      "orig" "sorting_direction"
                      "type" "`$STRING`")
                    (vs/jm
                      "example" "serialnumber"
                      "kind" "query"
                      "name" "sorting_field"
                      "orig" "sorting_field"
                      "type" "`$STRING`")
                    (vs/jm
                      "example" 10
                      "kind" "query"
                      "name" "take"
                      "orig" "take"
                      "type" "`$INTEGER`")))
                "kind" "http"
                "method" "GET"
                "orig" "/virtualDevices/{sharePartnerTo}"
                "parts" (vs/jt
                  "virtualDevices"
                  "{share_partner_to}")
                "rename" (vs/jm
                  "param" (vs/jm
                    "sharePartnerTo" "share_partner_to"))
                "select" (vs/jm
                  "exist" (vs/jt
                    "share_partner_to"
                    "skip"
                    "sorting_direction"
                    "sorting_field"
                    "take"))
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`")))))
        "relations" (vs/jm
          "ancestors" (vs/jt
            (vs/jt
              "virtual_device"))))
      "device_receive_result" (vs/jm
        "fields" (vs/jt
          (vs/jm
            "name" "success"
            "req" true
            "short" "Indicates if the action succeeded."
            "type" "`$BOOLEAN`"))
        "name" "device_receive_result"
        "op" (vs/jm
          "create" (vs/jm
            "input" "data"
            "name" "create"
            "points" (vs/jt
              (vs/jm
                "args" (vs/jm)
                "kind" "http"
                "method" "POST"
                "orig" "/devices/receive"
                "parts" (vs/jt
                  "devices"
                  "receive")
                "select" (vs/jm)
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`")))))
        "relations" (vs/jm
          "ancestors" (vs/jt)))
      "device_rki_activate_result" (vs/jm
        "fields" (vs/jt
          (vs/jm
            "name" "success"
            "req" true
            "short" "Indicates if the RKI activation succeeded."
            "type" "`$BOOLEAN`"))
        "name" "device_rki_activate_result"
        "op" (vs/jm
          "create" (vs/jm
            "input" "data"
            "name" "create"
            "points" (vs/jt
              (vs/jm
                "args" (vs/jm)
                "kind" "http"
                "method" "POST"
                "orig" "/devices/rki/activate"
                "parts" (vs/jt
                  "devices"
                  "rki"
                  "activate")
                "select" (vs/jm)
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`")))))
        "relations" (vs/jm
          "ancestors" (vs/jt)))
      "device_state" (vs/jm
        "fields" (vs/jt
          (vs/jm
            "name" "id"
            "short" "Unique identifier for this Device state."
            "type" "`$INTEGER`")
          (vs/jm
            "name" "name"
            "short" "Descriptive name for this Device state."
            "type" "`$STRING`"))
        "name" "device_state"
        "op" (vs/jm
          "list" (vs/jm
            "input" "data"
            "name" "list"
            "points" (vs/jt
              (vs/jm
                "args" (vs/jm)
                "kind" "http"
                "method" "GET"
                "orig" "/deviceStates"
                "parts" (vs/jt
                  "deviceStates")
                "select" (vs/jm)
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body.data`")))))
        "relations" (vs/jm
          "ancestors" (vs/jt)))
      "device_type" (vs/jm
        "fields" (vs/jt
          (vs/jm
            "name" "created"
            "short" "Creation timestamp in ISO 8601 format."
            "type" "`$STRING`")
          (vs/jm
            "name" "deviceTypeMode"
            "short" "The Device type."
            "type" "`$STRING`")
          (vs/jm
            "name" "hardwareVersion"
            "short" "The Device hardware version."
            "type" "`$STRING`")
          (vs/jm
            "name" "id"
            "short" "Unique idenifier."
            "type" "`$STRING`")
          (vs/jm
            "name" "isActive"
            "short" "This property indicates if the DeviceType is active."
            "type" "`$BOOLEAN`")
          (vs/jm
            "name" "manufacturer"
            "short" "The Device manufacturer."
            "type" "`$STRING`")
          (vs/jm
            "name" "model"
            "short" "The Device model."
            "type" "`$STRING`")
          (vs/jm
            "name" "modified"
            "short" "Last modified timestamp."
            "type" "`$STRING`")
          (vs/jm
            "name" "name"
            "short" "The DeviceType name."
            "type" "`$STRING`")
          (vs/jm
            "name" "photoUrl"
            "type" "`$STRING`")
          (vs/jm
            "name" "productName"
            "short" "The Device name."
            "type" "`$STRING`")
          (vs/jm
            "name" "version"
            "short" "The number of times that this resource has been updated."
            "type" "`$INTEGER`"))
        "name" "device_type"
        "op" (vs/jm
          "list" (vs/jm
            "input" "data"
            "name" "list"
            "points" (vs/jt
              (vs/jm
                "args" (vs/jm)
                "kind" "http"
                "method" "GET"
                "orig" "/deviceTypes"
                "parts" (vs/jt
                  "deviceTypes")
                "select" (vs/jm)
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body.data`"))))
          "load" (vs/jm
            "input" "data"
            "name" "load"
            "points" (vs/jt
              (vs/jm
                "args" (vs/jm
                  "params" (vs/jt
                    (vs/jm
                      "kind" "param"
                      "name" "id"
                      "orig" "id"
                      "reqd" true
                      "type" "`$STRING`")))
                "kind" "http"
                "method" "GET"
                "orig" "/deviceTypes/{id}"
                "parts" (vs/jt
                  "deviceTypes"
                  "{id}")
                "select" (vs/jm
                  "exist" (vs/jt
                    "id"))
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`")))))
        "relations" (vs/jm
          "ancestors" (vs/jt)))
      "inject_key" (vs/jm
        "fields" (vs/jt
          (vs/jm
            "name" "created"
            "short" "Creation timestamp in ISO 8601 format."
            "type" "`$STRING`")
          (vs/jm
            "name" "id"
            "short" "unique idenifier"
            "type" "`$STRING`")
          (vs/jm
            "name" "isActive"
            "short" "Active flag, inactive keys cannot be assigned to devices."
            "type" "`$BOOLEAN`")
          (vs/jm
            "name" "isP2PE"
            "short" "Flags if a key is for a P2PE compliant cypher."
            "type" "`$BOOLEAN`")
          (vs/jm
            "name" "keyType"
            "short" "The cipher type that the key works with."
            "type" "`$STRING`")
          (vs/jm
            "name" "modified"
            "short" "Last modified timestamp in ISO 8601 format."
            "type" "`$STRING`")
          (vs/jm
            "name" "name"
            "short" "Key name."
            "type" "`$STRING`")
          (vs/jm
            "name" "version"
            "short" "The number of times that this resource has been updated."
            "type" "`$INTEGER`"))
        "name" "inject_key"
        "op" (vs/jm
          "list" (vs/jm
            "input" "data"
            "name" "list"
            "points" (vs/jt
              (vs/jm
                "args" (vs/jm)
                "kind" "http"
                "method" "GET"
                "orig" "/injectKeys"
                "parts" (vs/jt
                  "injectKeys")
                "select" (vs/jm)
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body.data`"))))
          "load" (vs/jm
            "input" "data"
            "name" "load"
            "points" (vs/jt
              (vs/jm
                "args" (vs/jm
                  "params" (vs/jt
                    (vs/jm
                      "kind" "param"
                      "name" "id"
                      "orig" "id"
                      "reqd" true
                      "type" "`$STRING`")))
                "kind" "http"
                "method" "GET"
                "orig" "/injectKeys/{id}"
                "parts" (vs/jt
                  "injectKeys"
                  "{id}")
                "select" (vs/jm
                  "exist" (vs/jt
                    "id"))
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`")))))
        "relations" (vs/jm
          "ancestors" (vs/jt)))
      "kif" (vs/jm
        "fields" (vs/jt
          (vs/jm
            "name" "id"
            "short" "This resource's unique identifier."
            "type" "`$INTEGER`")
          (vs/jm
            "name" "name"
            "short" "The KIF's name."
            "type" "`$STRING`"))
        "name" "kif"
        "op" (vs/jm
          "list" (vs/jm
            "input" "data"
            "name" "list"
            "points" (vs/jt
              (vs/jm
                "args" (vs/jm)
                "kind" "http"
                "method" "GET"
                "orig" "/kifs"
                "parts" (vs/jt
                  "kifs")
                "select" (vs/jm)
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body.data`")))))
        "relations" (vs/jm
          "ancestors" (vs/jt)))
      "location" (vs/jm
        "fields" (vs/jt
          (vs/jm
            "name" "address1"
            "short" "The Location's street address."
            "type" "`$STRING`")
          (vs/jm
            "name" "address2"
            "short" "The Location's street address."
            "type" "`$STRING`")
          (vs/jm
            "name" "billingId"
            "short" "\\?"
            "type" "`$STRING`")
          (vs/jm
            "name" "city"
            "short" "The Location's city."
            "type" "`$STRING`")
          (vs/jm
            "name" "country"
            "short" "The Location's country."
            "type" "`$STRING`")
          (vs/jm
            "name" "created"
            "short" "Creation timestamp in ISO 8601 format."
            "type" "`$STRING`")
          (vs/jm
            "name" "customReference"
            "short" "A Partner specified reference for a location."
            "type" "`$STRING`")
          (vs/jm
            "name" "id"
            "short" "This resource's unique identifier."
            "type" "`$STRING`")
          (vs/jm
            "name" "locationType"
            "short" "The Location's clasification."
            "type" "`$STRING`")
          (vs/jm
            "name" "mailAddress1"
            "short" "The Location's street address."
            "type" "`$STRING`")
          (vs/jm
            "name" "mailAddress2"
            "short" "The Location's street address."
            "type" "`$STRING`")
          (vs/jm
            "name" "mailCity"
            "short" "The Location's city."
            "type" "`$STRING`")
          (vs/jm
            "name" "mailCountry"
            "short" "The Location's street address."
            "type" "`$STRING`")
          (vs/jm
            "name" "mailPostalCode"
            "short" "The Location's postal code."
            "type" "`$STRING`")
          (vs/jm
            "name" "mailStateProvince"
            "short" "The Location's street state or province."
            "type" "`$STRING`")
          (vs/jm
            "name" "modified"
            "short" "Last modified timestamp."
            "type" "`$STRING`")
          (vs/jm
            "name" "name"
            "short" "The Location's name."
            "type" "`$STRING`")
          (vs/jm
            "name" "nameOfBusiness"
            "short" "The name of the business at this location."
            "type" "`$STRING`")
          (vs/jm
            "name" "notes"
            "short" "Note for delivery driver."
            "type" "`$STRING`")
          (vs/jm
            "name" "postalCode"
            "short" "The Location's postal code."
            "type" "`$STRING`")
          (vs/jm
            "name" "stateProvince"
            "short" "The Location's street state or province."
            "type" "`$STRING`")
          (vs/jm
            "name" "uniqueId"
            "short" "Unique Identifier for the Location."
            "type" "`$STRING`")
          (vs/jm
            "name" "version"
            "short" "The number of times that this resource has been updated."
            "type" "`$INTEGER`"))
        "name" "location"
        "op" (vs/jm
          "create" (vs/jm
            "input" "data"
            "name" "create"
            "points" (vs/jt
              (vs/jm
                "args" (vs/jm)
                "kind" "http"
                "method" "POST"
                "orig" "/locations"
                "parts" (vs/jt
                  "locations")
                "select" (vs/jm)
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`"))))
          "list" (vs/jm
            "input" "data"
            "name" "list"
            "points" (vs/jt
              (vs/jm
                "args" (vs/jm
                  "query" (vs/jt
                    (vs/jm
                      "kind" "query"
                      "name" "client"
                      "orig" "client"
                      "reqd" true
                      "type" "`$STRING`")
                    (vs/jm
                      "example" 0
                      "kind" "query"
                      "name" "skip"
                      "orig" "skip"
                      "type" "`$INTEGER`")
                    (vs/jm
                      "example" 10
                      "kind" "query"
                      "name" "take"
                      "orig" "take"
                      "type" "`$INTEGER`")))
                "kind" "http"
                "method" "GET"
                "orig" "/locations"
                "parts" (vs/jt
                  "locations")
                "select" (vs/jm
                  "exist" (vs/jt
                    "client"
                    "skip"
                    "take"))
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body.data`"))))
          "load" (vs/jm
            "input" "data"
            "name" "load"
            "points" (vs/jt
              (vs/jm
                "args" (vs/jm
                  "params" (vs/jt
                    (vs/jm
                      "kind" "param"
                      "name" "id"
                      "orig" "id"
                      "reqd" true
                      "type" "`$STRING`")))
                "kind" "http"
                "method" "GET"
                "orig" "/locations/{id}"
                "parts" (vs/jt
                  "locations"
                  "{id}")
                "select" (vs/jm
                  "exist" (vs/jt
                    "id"))
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`"))))
          "remove" (vs/jm
            "input" "data"
            "name" "remove"
            "points" (vs/jt
              (vs/jm
                "args" (vs/jm
                  "params" (vs/jt
                    (vs/jm
                      "kind" "param"
                      "name" "id"
                      "orig" "id"
                      "reqd" true
                      "type" "`$STRING`")))
                "kind" "http"
                "method" "DELETE"
                "orig" "/locations/{id}"
                "parts" (vs/jt
                  "locations"
                  "{id}")
                "select" (vs/jm
                  "exist" (vs/jt
                    "id"))
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`")))))
        "relations" (vs/jm
          "ancestors" (vs/jt)))
      "partner" (vs/jm
        "fields" (vs/jt
          (vs/jm
            "name" "billingId"
            "short" "The Partner's billing identifier."
            "type" "`$STRING`")
          (vs/jm
            "name" "clientCanOrderEquipment"
            "short" "This property indicates if the Partner is allowed to order Equipment."
            "type" "`$BOOLEAN`")
          (vs/jm
            "name" "contact"
            "op" (vs/jm
              "list" (vs/jm
                "req" true
                "type" "`$OBJECT`"))
            "short" "Reference to the associated User resource."
            "type" "`$OBJECT`")
          (vs/jm
            "name" "created"
            "short" "Creation timestamp in ISO 8601 format."
            "type" "`$STRING`")
          (vs/jm
            "name" "id"
            "short" "This resource's unique identifier."
            "type" "`$STRING`")
          (vs/jm
            "name" "isActive"
            "short" "This property indicates if the Parter account is active or disabled."
            "type" "`$BOOLEAN`")
          (vs/jm
            "name" "location"
            "req" true
            "short" "Reference to the associated Location resource."
            "type" "`$OBJECT`")
          (vs/jm
            "name" "modified"
            "short" "Last modified timestamp."
            "type" "`$STRING`")
          (vs/jm
            "name" "name"
            "short" "The Partner's name."
            "type" "`$STRING`")
          (vs/jm
            "name" "parent"
            "short" "Reference to the associated Partner."
            "type" "`$OBJECT`")
          (vs/jm
            "name" "partnerId"
            "short" "The Partner's id."
            "type" "`$STRING`")
          (vs/jm
            "name" "reference"
            "short" "The Partner's reference string."
            "type" "`$STRING`")
          (vs/jm
            "name" "verificationPhrase"
            "short" "The verification phrase is a message that the Partner creates."
            "type" "`$STRING`")
          (vs/jm
            "name" "version"
            "short" "The number of times that this resource has been updated."
            "type" "`$INTEGER`"))
        "name" "partner"
        "op" (vs/jm
          "create" (vs/jm
            "input" "data"
            "name" "create"
            "points" (vs/jt
              (vs/jm
                "args" (vs/jm)
                "kind" "http"
                "method" "POST"
                "orig" "/partners"
                "parts" (vs/jt
                  "partners")
                "select" (vs/jm)
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`"))))
          "list" (vs/jm
            "input" "data"
            "name" "list"
            "points" (vs/jt
              (vs/jm
                "args" (vs/jm
                  "query" (vs/jt
                    (vs/jm
                      "kind" "query"
                      "name" "partner"
                      "orig" "partner"
                      "type" "`$STRING`")
                    (vs/jm
                      "example" 0
                      "kind" "query"
                      "name" "skip"
                      "orig" "skip"
                      "type" "`$INTEGER`")
                    (vs/jm
                      "example" 10
                      "kind" "query"
                      "name" "take"
                      "orig" "take"
                      "type" "`$INTEGER`")))
                "kind" "http"
                "method" "GET"
                "orig" "/partners"
                "parts" (vs/jt
                  "partners")
                "select" (vs/jm
                  "exist" (vs/jt
                    "partner"
                    "skip"
                    "take"))
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body.data`"))))
          "load" (vs/jm
            "input" "data"
            "name" "load"
            "points" (vs/jt
              (vs/jm
                "args" (vs/jm
                  "params" (vs/jt
                    (vs/jm
                      "kind" "param"
                      "name" "id"
                      "orig" "id"
                      "reqd" true
                      "type" "`$STRING`")))
                "kind" "http"
                "method" "GET"
                "orig" "/partners/{id}"
                "parts" (vs/jt
                  "partners"
                  "{id}")
                "select" (vs/jm
                  "exist" (vs/jt
                    "id"))
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`")))))
        "relations" (vs/jm
          "ancestors" (vs/jt)))
      "shipment" (vs/jm
        "fields" (vs/jt
          (vs/jm
            "name" "carrier"
            "short" "The name of the courier."
            "type" "`$STRING`")
          (vs/jm
            "name" "client"
            "short" "Reference to the associated Client resource."
            "type" "`$OBJECT`")
          (vs/jm
            "name" "created"
            "short" "Creation timestamp in ISO 8601 format."
            "type" "`$STRING`")
          (vs/jm
            "name" "dateReceived"
            "short" "The date and time that a package is recieved."
            "type" "`$STRING`")
          (vs/jm
            "name" "dateShipped"
            "short" "The date and time that a package is shipped."
            "type" "`$STRING`")
          (vs/jm
            "name" "dcKif"
            "short" "Reference to the associated KIF resource."
            "type" "`$OBJECT`")
          (vs/jm
            "name" "id"
            "short" "This resource's unique identifier."
            "type" "`$STRING`")
          (vs/jm
            "name" "items"
            "type" "`$ARRAY`")
          (vs/jm
            "name" "kif"
            "short" "Reference to the associated KIF resource."
            "type" "`$OBJECT`")
          (vs/jm
            "name" "modified"
            "short" "Last modified timestamp."
            "type" "`$STRING`")
          (vs/jm
            "name" "partner"
            "short" "Reference to the associated Partner."
            "type" "`$OBJECT`")
          (vs/jm
            "name" "shipmentType"
            "short" "The type of shipment."
            "type" "`$STRING`")
          (vs/jm
            "name" "tracking"
            "short" "The courier's tracking number."
            "type" "`$STRING`")
          (vs/jm
            "name" "version"
            "short" "The number of times that this resource has been updated."
            "type" "`$INTEGER`"))
        "name" "shipment"
        "op" (vs/jm
          "create" (vs/jm
            "input" "data"
            "name" "create"
            "points" (vs/jt
              (vs/jm
                "args" (vs/jm)
                "kind" "http"
                "method" "POST"
                "orig" "/shipments"
                "parts" (vs/jt
                  "shipments")
                "select" (vs/jm)
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`"))))
          "list" (vs/jm
            "input" "data"
            "name" "list"
            "points" (vs/jt
              (vs/jm
                "args" (vs/jm
                  "query" (vs/jt
                    (vs/jm
                      "kind" "query"
                      "name" "kif"
                      "orig" "kif"
                      "reqd" true
                      "type" "`$STRING`")
                    (vs/jm
                      "kind" "query"
                      "name" "mode"
                      "orig" "mode"
                      "type" "`$STRING`")
                    (vs/jm
                      "example" 0
                      "kind" "query"
                      "name" "skip"
                      "orig" "skip"
                      "type" "`$INTEGER`")
                    (vs/jm
                      "example" 10
                      "kind" "query"
                      "name" "take"
                      "orig" "take"
                      "type" "`$INTEGER`")))
                "kind" "http"
                "method" "GET"
                "orig" "/shipments"
                "parts" (vs/jt
                  "shipments")
                "select" (vs/jm
                  "exist" (vs/jt
                    "kif"
                    "mode"
                    "skip"
                    "take"))
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body.data`"))))
          "load" (vs/jm
            "input" "data"
            "name" "load"
            "points" (vs/jt
              (vs/jm
                "args" (vs/jm
                  "params" (vs/jt
                    (vs/jm
                      "kind" "param"
                      "name" "id"
                      "orig" "id"
                      "reqd" true
                      "type" "`$STRING`")))
                "kind" "http"
                "method" "GET"
                "orig" "/shipments/{id}"
                "parts" (vs/jt
                  "shipments"
                  "{id}")
                "select" (vs/jm
                  "exist" (vs/jt
                    "id"))
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`")))))
        "relations" (vs/jm
          "ancestors" (vs/jt)))
      "success" (vs/jm
        "fields" (vs/jt
          (vs/jm
            "name" "success"
            "short" "Indicates if the action was a success."
            "type" "`$BOOLEAN`"))
        "name" "success"
        "op" (vs/jm
          "create" (vs/jm
            "input" "data"
            "name" "create"
            "points" (vs/jt
              (vs/jm
                "args" (vs/jm
                  "params" (vs/jt
                    (vs/jm
                      "kind" "param"
                      "name" "share_partner_to"
                      "orig" "share_partner_to"
                      "reqd" true
                      "type" "`$STRING`")))
                "kind" "http"
                "method" "POST"
                "orig" "/virtualDevices/{sharePartnerTo}"
                "parts" (vs/jt
                  "virtualDevices"
                  "{share_partner_to}")
                "rename" (vs/jm
                  "param" (vs/jm
                    "sharePartnerTo" "share_partner_to"))
                "select" (vs/jm
                  "exist" (vs/jt
                    "share_partner_to"))
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`"))))
          "remove" (vs/jm
            "input" "data"
            "name" "remove"
            "points" (vs/jt
              (vs/jm
                "args" (vs/jm
                  "params" (vs/jt
                    (vs/jm
                      "kind" "param"
                      "name" "share_partner_to"
                      "orig" "share_partner_to"
                      "reqd" true
                      "type" "`$STRING`")))
                "kind" "http"
                "method" "DELETE"
                "orig" "/virtualDevices/{sharePartnerTo}"
                "parts" (vs/jt
                  "virtualDevices"
                  "{share_partner_to}")
                "rename" (vs/jm
                  "param" (vs/jm
                    "sharePartnerTo" "share_partner_to"))
                "select" (vs/jm
                  "exist" (vs/jt
                    "share_partner_to"))
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`")))))
        "relations" (vs/jm
          "ancestors" (vs/jt
            (vs/jt
              "virtual_device"))))
      "transaction" (vs/jm
        "fields" (vs/jt
          (vs/jm
            "name" "alternateKey"
            "short" "The alternative key is used when a Device outputs a different serial number from its firmware/software when compared to the serial number that is printed on the Device's casing or its packaging."
            "type" "`$STRING`")
          (vs/jm
            "name" "client"
            "short" "Reference to the associated Client resource."
            "type" "`$OBJECT`")
          (vs/jm
            "name" "clientRef"
            "short" "Client Reference property that is included in the decrypt API call."
            "type" "`$STRING`")
          (vs/jm
            "name" "created"
            "short" "Creation timestamp in ISO 8601 format."
            "type" "`$STRING`")
          (vs/jm
            "name" "decrypted"
            "short" "A Transcation can process muliple decryptions."
            "type" "`$INTEGER`")
          (vs/jm
            "name" "deviceName"
            "short" "The name of the Device that generated the payload to decrypt."
            "type" "`$STRING`")
          (vs/jm
            "name" "directPartner"
            "short" "Reference to the associated Partner."
            "type" "`$OBJECT`")
          (vs/jm
            "name" "encrypted"
            "short" "A Transcation can process muliple encryptions."
            "type" "`$INTEGER`")
          (vs/jm
            "name" "endDate"
            "short" "Timestamp from the end of the transaction."
            "type" "`$STRING`")
          (vs/jm
            "name" "errCode"
            "short" "The error code that is sent in response to a failed decrypt API call."
            "type" "`$STRING`")
          (vs/jm
            "name" "errMessage"
            "short" "The error messge that is sent in response to a failed decrypt API call."
            "type" "`$STRING`")
          (vs/jm
            "name" "id"
            "short" "This resource's unique identifier."
            "type" "`$STRING`")
          (vs/jm
            "name" "ipAddress"
            "short" "The IP address of the http client that makes the decrypt API call."
            "type" "`$STRING`")
          (vs/jm
            "name" "isVirtual"
            "short" "Indicates if the Transaction came from a virtual Device."
            "type" "`$BOOLEAN`")
          (vs/jm
            "name" "keyType"
            "short" "The type of cipher used during decrytion."
            "type" "`$STRING`")
          (vs/jm
            "name" "location"
            "req" true
            "short" "Reference to the associated Location resource."
            "type" "`$OBJECT`")
          (vs/jm
            "name" "messageId"
            "short" "Message ID."
            "type" "`$STRING`")
          (vs/jm
            "name" "method"
            "short" "The decryption cypher/method."
            "type" "`$STRING`")
          (vs/jm
            "name" "partner"
            "short" "Reference to the associated Partner."
            "type" "`$OBJECT`")
          (vs/jm
            "name" "reference"
            "short" "The reference property that the Client includes in the decrypt API call."
            "type" "`$STRING`")
          (vs/jm
            "name" "serialNumber"
            "short" "The serial number of the Device that generated the payload to decrypt."
            "type" "`$STRING`")
          (vs/jm
            "name" "startDate"
            "short" "Timestamp from the beginning of the transaction."
            "type" "`$STRING`")
          (vs/jm
            "name" "success"
            "short" "The success indicator."
            "type" "`$BOOLEAN`")
          (vs/jm
            "name" "transactionSource"
            "short" "The source of the Transaction."
            "type" "`$STRING`"))
        "name" "transaction"
        "op" (vs/jm
          "create" (vs/jm
            "input" "data"
            "name" "create"
            "points" (vs/jt
              (vs/jm
                "args" (vs/jm)
                "kind" "http"
                "method" "POST"
                "orig" "/transactions"
                "parts" (vs/jt
                  "transactions")
                "select" (vs/jm)
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`"))))
          "list" (vs/jm
            "input" "data"
            "name" "list"
            "points" (vs/jt
              (vs/jm
                "args" (vs/jm
                  "query" (vs/jt
                    (vs/jm
                      "kind" "query"
                      "name" "client"
                      "orig" "client"
                      "type" "`$STRING`")
                    (vs/jm
                      "kind" "query"
                      "name" "client_ref"
                      "orig" "client_ref"
                      "type" "`$STRING`")
                    (vs/jm
                      "kind" "query"
                      "name" "date_from"
                      "orig" "date_from"
                      "type" "`$STRING`")
                    (vs/jm
                      "kind" "query"
                      "name" "date_to"
                      "orig" "date_to"
                      "type" "`$STRING`")
                    (vs/jm
                      "kind" "query"
                      "name" "location"
                      "orig" "location"
                      "type" "`$STRING`")
                    (vs/jm
                      "kind" "query"
                      "name" "message_id"
                      "orig" "message_id"
                      "type" "`$STRING`")
                    (vs/jm
                      "example" "nocount"
                      "kind" "query"
                      "name" "paging_mode"
                      "orig" "paging_mode"
                      "type" "`$STRING`")
                    (vs/jm
                      "kind" "query"
                      "name" "partner"
                      "orig" "partner"
                      "type" "`$STRING`")
                    (vs/jm
                      "kind" "query"
                      "name" "reference"
                      "orig" "reference"
                      "type" "`$STRING`")
                    (vs/jm
                      "kind" "query"
                      "name" "serial_number"
                      "orig" "serial_number"
                      "type" "`$STRING`")
                    (vs/jm
                      "example" 0
                      "kind" "query"
                      "name" "skip"
                      "orig" "skip"
                      "type" "`$INTEGER`")
                    (vs/jm
                      "kind" "query"
                      "name" "success"
                      "orig" "success"
                      "type" "`$BOOLEAN`")
                    (vs/jm
                      "example" 10
                      "kind" "query"
                      "name" "take"
                      "orig" "take"
                      "type" "`$INTEGER`")))
                "kind" "http"
                "method" "GET"
                "orig" "/transactions"
                "parts" (vs/jt
                  "transactions")
                "select" (vs/jm
                  "exist" (vs/jt
                    "client"
                    "client_ref"
                    "date_from"
                    "date_to"
                    "location"
                    "message_id"
                    "paging_mode"
                    "partner"
                    "reference"
                    "serial_number"
                    "skip"
                    "success"
                    "take"))
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body.data`"))))
          "load" (vs/jm
            "input" "data"
            "name" "load"
            "points" (vs/jt
              (vs/jm
                "args" (vs/jm
                  "params" (vs/jt
                    (vs/jm
                      "kind" "param"
                      "name" "id"
                      "orig" "id"
                      "reqd" true
                      "type" "`$STRING`")))
                "kind" "http"
                "method" "GET"
                "orig" "/transactions/{id}"
                "parts" (vs/jt
                  "transactions"
                  "{id}")
                "select" (vs/jm
                  "exist" (vs/jt
                    "id"))
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`")))))
        "relations" (vs/jm
          "ancestors" (vs/jt)))
      "update_result" (vs/jm
        "fields" (vs/jt
          (vs/jm
            "name" "client"
            "short" "Reference to the associated Client resource."
            "type" "`$OBJECT`")
          (vs/jm
            "name" "email"
            "short" "The User's email address."
            "type" "`$STRING`")
          (vs/jm
            "name" "firstName"
            "short" "The User's name."
            "type" "`$STRING`")
          (vs/jm
            "name" "id"
            "short" "ID of newly created resource"
            "type" "`$STRING`")
          (vs/jm
            "name" "isActive"
            "short" "This property indicates if the User account is active or disabled."
            "type" "`$BOOLEAN`")
          (vs/jm
            "name" "kif"
            "short" "Reference to the associated KIF resource."
            "type" "`$OBJECT`")
          (vs/jm
            "name" "lastName"
            "short" "The User's Surname."
            "type" "`$STRING`")
          (vs/jm
            "name" "partner"
            "short" "Reference to the associated Partner."
            "type" "`$OBJECT`")
          (vs/jm
            "name" "phone"
            "short" "The User's phone number without dashes, spaces, or brackets."
            "type" "`$STRING`")
          (vs/jm
            "name" "userName"
            "short" "The User's unique username."
            "type" "`$STRING`")
          (vs/jm
            "name" "userRole"
            "short" "Reference to the associated User Role."
            "type" "`$OBJECT`")
          (vs/jm
            "name" "version"
            "short" "The number of times that this resource has been updated."
            "type" "`$INTEGER`"))
        "name" "update_result"
        "op" (vs/jm
          "create" (vs/jm
            "input" "data"
            "name" "create"
            "points" (vs/jt
              (vs/jm
                "args" (vs/jm)
                "kind" "http"
                "method" "POST"
                "orig" "/users"
                "parts" (vs/jt
                  "users")
                "select" (vs/jm)
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`"))))
          "list" (vs/jm
            "input" "data"
            "name" "list"
            "points" (vs/jt
              (vs/jm
                "args" (vs/jm
                  "query" (vs/jt
                    (vs/jm
                      "kind" "query"
                      "name" "client"
                      "orig" "client"
                      "type" "`$STRING`")
                    (vs/jm
                      "kind" "query"
                      "name" "kif"
                      "orig" "kif"
                      "type" "`$STRING`")
                    (vs/jm
                      "kind" "query"
                      "name" "partner"
                      "orig" "partner"
                      "type" "`$ANY`")
                    (vs/jm
                      "example" 0
                      "kind" "query"
                      "name" "skip"
                      "orig" "skip"
                      "type" "`$INTEGER`")
                    (vs/jm
                      "example" 10
                      "kind" "query"
                      "name" "take"
                      "orig" "take"
                      "type" "`$INTEGER`")))
                "kind" "http"
                "method" "GET"
                "orig" "/users"
                "parts" (vs/jt
                  "users")
                "select" (vs/jm
                  "exist" (vs/jt
                    "client"
                    "kif"
                    "partner"
                    "skip"
                    "take"))
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body.data`"))))
          "update" (vs/jm
            "input" "data"
            "name" "update"
            "points" (vs/jt
              (vs/jm
                "args" (vs/jm
                  "params" (vs/jt
                    (vs/jm
                      "kind" "param"
                      "name" "id"
                      "orig" "id"
                      "reqd" true
                      "type" "`$STRING`")))
                "kind" "http"
                "method" "PATCH"
                "orig" "/clients/{id}"
                "parts" (vs/jt
                  "clients"
                  "{id}")
                "select" (vs/jm
                  "exist" (vs/jt
                    "id"))
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`"))
              (vs/jm
                "args" (vs/jm
                  "params" (vs/jt
                    (vs/jm
                      "kind" "param"
                      "name" "id"
                      "orig" "id"
                      "reqd" true
                      "type" "`$STRING`")))
                "kind" "http"
                "method" "PATCH"
                "orig" "/devices/{id}"
                "parts" (vs/jt
                  "devices"
                  "{id}")
                "select" (vs/jm
                  "exist" (vs/jt
                    "id"))
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`"))
              (vs/jm
                "args" (vs/jm
                  "params" (vs/jt
                    (vs/jm
                      "kind" "param"
                      "name" "id"
                      "orig" "id"
                      "reqd" true
                      "type" "`$STRING`")))
                "kind" "http"
                "method" "PATCH"
                "orig" "/locations/{id}"
                "parts" (vs/jt
                  "locations"
                  "{id}")
                "select" (vs/jm
                  "exist" (vs/jt
                    "id"))
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`"))
              (vs/jm
                "args" (vs/jm
                  "params" (vs/jt
                    (vs/jm
                      "kind" "param"
                      "name" "id"
                      "orig" "id"
                      "reqd" true
                      "type" "`$STRING`")))
                "kind" "http"
                "method" "PATCH"
                "orig" "/partners/{id}"
                "parts" (vs/jt
                  "partners"
                  "{id}")
                "select" (vs/jm
                  "exist" (vs/jt
                    "id"))
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`"))
              (vs/jm
                "args" (vs/jm
                  "params" (vs/jt
                    (vs/jm
                      "kind" "param"
                      "name" "id"
                      "orig" "id"
                      "reqd" true
                      "type" "`$STRING`")))
                "kind" "http"
                "method" "PATCH"
                "orig" "/shipments/{id}"
                "parts" (vs/jt
                  "shipments"
                  "{id}")
                "select" (vs/jm
                  "exist" (vs/jt
                    "id"))
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`"))
              (vs/jm
                "args" (vs/jm
                  "params" (vs/jt
                    (vs/jm
                      "kind" "param"
                      "name" "id"
                      "orig" "id"
                      "reqd" true
                      "type" "`$STRING`")))
                "kind" "http"
                "method" "PATCH"
                "orig" "/transactions/{id}"
                "parts" (vs/jt
                  "transactions"
                  "{id}")
                "select" (vs/jm
                  "exist" (vs/jt
                    "id"))
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`"))
              (vs/jm
                "args" (vs/jm
                  "params" (vs/jt
                    (vs/jm
                      "kind" "param"
                      "name" "id"
                      "orig" "id"
                      "reqd" true
                      "type" "`$STRING`")))
                "kind" "http"
                "method" "PATCH"
                "orig" "/users/{id}"
                "parts" (vs/jt
                  "users"
                  "{id}")
                "select" (vs/jm
                  "exist" (vs/jt
                    "id"))
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`")))))
        "relations" (vs/jm
          "ancestors" (vs/jt)))
      "user" (vs/jm
        "fields" (vs/jt
          (vs/jm
            "name" "client"
            "short" "Reference to the associated Client resource."
            "type" "`$OBJECT`")
          (vs/jm
            "name" "created"
            "short" "Creation timestamp in ISO 8601 format."
            "type" "`$STRING`")
          (vs/jm
            "name" "email"
            "short" "The User's email address."
            "type" "`$STRING`")
          (vs/jm
            "name" "firstName"
            "short" "The User's name."
            "type" "`$STRING`")
          (vs/jm
            "name" "id"
            "short" "This resource's unique identifier."
            "type" "`$STRING`")
          (vs/jm
            "name" "isActive"
            "short" "This property indicates if the User account is active or disabled."
            "type" "`$BOOLEAN`")
          (vs/jm
            "name" "kif"
            "short" "Reference to the associated KIF resource."
            "type" "`$OBJECT`")
          (vs/jm
            "name" "lastName"
            "short" "The User's Surname."
            "type" "`$STRING`")
          (vs/jm
            "name" "modified"
            "short" "Last modified timestamp."
            "type" "`$STRING`")
          (vs/jm
            "name" "partner"
            "short" "Reference to the associated Partner."
            "type" "`$OBJECT`")
          (vs/jm
            "name" "phone"
            "short" "The User's phone number without dashes, spaces, or brackets."
            "type" "`$STRING`")
          (vs/jm
            "name" "userName"
            "short" "The User's unique username."
            "type" "`$STRING`")
          (vs/jm
            "name" "userRole"
            "short" "Reference to the associated User Role."
            "type" "`$OBJECT`")
          (vs/jm
            "name" "version"
            "short" "The number of times that this resource has been updated."
            "type" "`$INTEGER`"))
        "name" "user"
        "op" (vs/jm
          "load" (vs/jm
            "input" "data"
            "name" "load"
            "points" (vs/jt
              (vs/jm
                "args" (vs/jm
                  "params" (vs/jt
                    (vs/jm
                      "kind" "param"
                      "name" "id"
                      "orig" "id"
                      "reqd" true
                      "type" "`$STRING`")))
                "kind" "http"
                "method" "GET"
                "orig" "/users/{id}"
                "parts" (vs/jt
                  "users"
                  "{id}")
                "select" (vs/jm
                  "exist" (vs/jt
                    "id"))
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`"))))
          "remove" (vs/jm
            "input" "data"
            "name" "remove"
            "points" (vs/jt
              (vs/jm
                "args" (vs/jm
                  "params" (vs/jt
                    (vs/jm
                      "kind" "param"
                      "name" "id"
                      "orig" "id"
                      "reqd" true
                      "type" "`$STRING`")))
                "kind" "http"
                "method" "DELETE"
                "orig" "/users/{id}"
                "parts" (vs/jt
                  "users"
                  "{id}")
                "select" (vs/jm
                  "exist" (vs/jt
                    "id"))
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`")))))
        "relations" (vs/jm
          "ancestors" (vs/jt))))
    "feature" (vs/jm
      "test" (vs/jm
        "options" (vs/jm
          "active" false)
        "transport" "base"))
    "main" (vs/jm
      "name" "BluefinDecryptxP2pe"
      "slug" "bluefin-decryptx-p2pe"
      "target" "clojure"
      "version" "0.1.1")
    "options" (vs/jm
      "auth" (vs/jm
        "prefix" "Basic")
      "base" "https://apis.p2pemanager.com/api/v1"
      "entity" (vs/jm
        "attestation" (vs/jm)
        "client" (vs/jm)
        "create_result" (vs/jm)
        "decryption" (vs/jm)
        "device" (vs/jm)
        "device_build" (vs/jm)
        "device_custody_detail" (vs/jm)
        "device_custody_list" (vs/jm)
        "device_list" (vs/jm)
        "device_receive_result" (vs/jm)
        "device_rki_activate_result" (vs/jm)
        "device_state" (vs/jm)
        "device_type" (vs/jm)
        "inject_key" (vs/jm)
        "kif" (vs/jm)
        "location" (vs/jm)
        "partner" (vs/jm)
        "shipment" (vs/jm)
        "success" (vs/jm)
        "transaction" (vs/jm)
        "update_result" (vs/jm)
        "user" (vs/jm))
      "headers" (vs/jm
        "content-type" "application/json"))))
